#!/bin/bash
rm -f 3d_tephra_fall.nc
rm -f Ash3d.lst
rm -f caption.txt
rm -f contourfile_0.1_0_i.xyz
rm -f deposit.gif
rm -f dep_out_t16_g0.grd
rm -f dep_tot_out.grd
rm -f dep_tot_out_t16.grd
rm -f dp_0.1.lev
rm -f dp_0.8.lev
rm -f dp_100.lev
rm -f dp_25.lev
rm -f dp_6.lev
rm -f map_range.txt
rm -f progress.txt
rm -f temp.epsi
rm -f temp.gif
rm -f temp.pdf
rm -f temp.ps
rm -f var.txt
rm -f volc.txt
rm -f world_cities.txt
rm -f contourfile*xyz
rm -f .gmtdefaults4
rm -f .gmtcommands4
rm -f GFSVolc_to_gif_dp.sh
rm -f GFSVolc_to_gif_dp_mm.sh
rm -f NCEP
rm -f Ash3d
