!##############################################################################
!
! Ash3d_PostProc_gnuplot module
!
! This module provides the subroutines that use gnuplot for creating 2d maps,
! 2d vertical profiles, and the little deposit accumulation plots linked to
! the airport arrival kml (ash_arrivaltimes_airports.kml).
! These subroutines create temporary script files that are run if gnuplot is
! installed on the local system.
!   http://www.gnuplot.info
! Third party fortran API is available with ogpf, gnuplotfortran, fplot, gnufor
!
!      subroutine write_2Dmap_PNG_gnuplot
!      subroutine write_2Dprof_PNG_gnuplot
!      subroutine write_DepPOI_TS_PNG_gnuplot
!
!##############################################################################

      module Ash3d_PostProc_gnuplot

      use precis_param

      use io_units

      use global_param,  only : &
         DirDelim,EPS_SMALL

      use io_data,       only : &
         Instit_IconFile,Ash3dHome

      implicit none

        ! Set everything to private by default
      private

        ! Publicly available subroutines/functions
      public write_2Dmap_PNG_gnuplot,   &
             write_2Dprof_PNG_gnuplot,  &
             write_DepPOI_TS_PNG_gnuplot

        ! Publicly available variables
      logical, public :: CleanScripts_gnuplot

      contains
      !------------------------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dmap_PNG_gnuplot
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    nx            = x length of output array OutVar
!    ny            = y length of output array OutVar
!    iprod         = product ID
!    itime         = time index from netcdf data file
!    OutVar        = 2-d array to be written to ASCII file
!    Fill_Value    = NaN value
!    writeContours = logical
!
!  This subroutine creates a png map of the variable in OutVar using the gnuplot
!  graphics package.  Annotations and contour levels are indicated via the
!  product ID (iprod).  If writeContours is set to true, then this subroutine
!  is only used for generating and storing the contours (for gnuplot, this is
!  through output files generated by the script) with no png written.
!  If timestep = -1, then use the last step in file
!
!  To invoke:
!   ASH3DPLOT=3 ./Ash3d_PostProc 3d_tephra_fall.nc 5 3
!
!   Example script:
!     ##########################################################################
!     # Temporary gnuplot script for producing 2d maps for Ash3d_PostProc
!     # Adjust to suit your needs.
!     # You will need the coastline file http://www.gnuplotting.org/data/world_50m.txt
!     # copied to the cwd or ${ASH3DHOME}/share/post_proc/
!     ##########################################################################
!     set terminal pngcairo font 'sans,12' size 854,603
!     set output 'Ash3d_Deposit____final.png'
!     set multiplot
!
!     # Set logo plot
!     set size 0.2, 0.2
!     set origin 0.78, 0.0
!     unset key
!     unset tics
!     unset xlabel
!     unset ylabel
!     unset title
!     #unset border
!     unset label
!     set size ratio -1
!     plot "/opt/USGS/Ash3d/share/post_proc/logo.png" binary filetype=png with rgbalph
!
!     # Now main plot
!     set origin 0.05, .20
!     set size 0.85, 0.8
!     set ylabel 'Latitude'
!     set xlabel 'Longitude'
!     set title 'Final Deposit Thickness (mm)     '
!     set datafile missing 'NaN'
!     XMIN =  -100.0000
!     YMIN =    17.5000
!     XMAX =   -95.0000
!     YMAX =    21.0000
!     set xrange [XMIN:XMAX]
!     set yrange [YMIN:YMAX]
!     set contour base
!     set cntrparam bspline
!     set cntrparam levels discrete \
!             0.01000, \
!             0.03000, \
!             0.10000, \
!             0.30000, \
!             1.00000, \
!             3.00000, \
!            10.00000, \
!            30.00000, \
!           100.00000, \
!     300.000000
!     unset surface
!     set table 'outvar.con'
!     splot 'outvar.dat' using 1:2:3
!     unset table
!     set style line 2 lc rgb '#808080' lt 0 lw 1
!     set grid front ls 2
!     unset key
!     XVAL = XMIN-(XMAX-XMIN)*0.1
!     YVAL = YMIN-(YMAX-YMIN)*0.25
!     set label 'Volcano:  Popocatépetl' at XVAL, YVAL font 'sans,9' offset character 0,2
!     set label 'Run Date: 2026-01-16T21:49:00Z' at XVAL, YVAL font 'sans,9' offset character 0,1
!     set label 'Windfile:    25' at XVAL, YVAL font 'sans,9' offset character 0,0
!     XVAL = XMIN+(XMAX-XMIN)*0.4
!     set label 'Erup. Start Time:   2015-04-04T04:00:00Z' at XVAL, YVAL font 'sans,9' offset character 0,2
!     set label 'Erup. Plume Height: 12.0 km' at XVAL, YVAL font 'sans,9' offset character 0,1
!     set label 'Erup. Duration:      6.0 hours' at XVAL, YVAL font 'sans,9' offset character 0,0
!     set label 'Erup. Volume:        0.03000 km3 (DRE)' at XVAL, YVAL font 'sans,9' offset character 0,-1
!     plot '/opt/USGS/Ash3d/share/post_proc/world_50m.txt' with filledcurves linetype rgb '#dddddd' , \
!     'outvar.con' using 1:2 with l lc rgb '#888888' , \
!     '' every 1000 with labels font ',6' , \
!     'cities.xy' using 1:2 , \
!     '' using 1:2:3 with labels font ',10' point pointtype 7 offset char 1,1, \
!     'volc.dat' using 1:2 , \
!        '' using 1:2:3 with labels point pointtype 22 pointsize 2 lt rgb 'red'
!     unset multiplot
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dmap_PNG_gnuplot(nx,ny,iprod,itime,OutVar,Fill_Value,writeContours)

      use mesh,          only : &
         IsLatLon,lon_cc_pd,lat_cc_pd,de,dn, &
         dx,dy,                              &
         latLL,lonLL,latUR,lonUR,            &
         xLL,yLL,xUR,yUR

      use Output_Vars,   only : &
         !ContourFilled, &
         Con_Cust,Con_Cust_N,Con_Cust_RGB,Con_Cust_Lev,&
         Con_DepThick_mm_N,Con_DepThick_mm_Lev,Con_DepThick_mm_RGB, &
         Con_DepThick_in_N,Con_DepThick_in_Lev,Con_DepThick_in_RGB, &
         Con_DepTime_N,Con_DepTime_Lev,Con_DepTime_RGB, &
         Con_CloudCon_N,Con_CloudCon_Lev,Con_CloudCon_RGB, &
         Con_CloudTop_N,Con_CloudTop_RGB,Con_CloudTop_Lev, &
         Con_CloudBot_N,Con_CloudBot_RGB,Con_CloudBot_Lev, &
         Con_CloudLoad_N,Con_CloudLoad_RGB,Con_CloudLoad_Lev, &
         Con_CloudRef_N,Con_CloudRef_RGB,Con_CloudRef_Lev, &
         Con_CloudTime_N,Con_CloudTime_RGB,Con_CloudTime_Lev, &
         ContourDataX,ContourDataY,ContourDataNcurves,ContourDataNpoints,&
         !CloudArrivalTime,Mask_Deposit,Mask_Cloud,&
         CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS,ContourLev,nConLev

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap

      use io_data,       only : &
         WriteTimes,cdf_b3l1,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight,lon_volcano,lat_volcano

      use citywriter

      integer      ,intent(in) :: nx
      integer      ,intent(in) :: ny
      integer      ,intent(in) :: iprod
      integer      ,intent(in) :: itime
      real(kind=ip),intent(in) :: OutVar(nx,ny)
      real(kind=ip),intent(in) :: Fill_Value
      logical      ,intent(in) :: writeContours

      character (len=  6) :: Fill_Value_str
      character (len=200) :: cmd

      integer :: ii,jj
      real(kind=ip) :: tmp_ip
      integer,dimension(:,:),allocatable :: zrgb
      character (len= 40) :: title_plot
      character (len= 30) :: cstr_xlabel = 'Longitude'
      character (len= 30) :: cstr_ylabel = 'Latitude'
      character (len= 30) :: cstr_zlabel
      character (len= 30) :: cstr_volcname
      character (len= 30) :: cstr_run_date
      character (len= 30) :: cstr_windfile
      character (len= 40) :: cstr_ErStartT
      character (len= 27) :: cstr_ErHeight
      character (len= 30) :: cstr_ErDuratn
      character (len= 38) :: cstr_ErVolume
      character (len= 45) :: cstr_note
      character (len= 20) :: varname
      character (len=  9) :: cio
      character (len=  4) :: outfile_ext = '.png'
      character (len= 10) :: units
      integer             :: ioerr
      integer             :: iostatus
      integer             :: cstat
      character (len=120) :: iomessage
      integer             :: iw,iwf
      logical             :: IsThere1,IsThere2
      logical             :: HaveIconFile
      character (len= 50) :: linebuffer050
      character (len= 80) :: linebuffer080
      character (len=130):: linebuffer130
      character         :: testkey

      ! Plot dimensions
      real(kind=ip)  :: xmin
      real(kind=ip)  :: xmax
      real(kind=ip)  :: ymin
      real(kind=ip)  :: ymax
      logical        :: IsRegGrid

      ! Aux. File names
      character (len=  8) :: filename_root
      character (len= 10) :: filename_script
      character (len= 10) :: filename_outdata
      character (len= 40) :: filename_png
      character (len= 10) :: filename_contourdata
      character (len= 80) :: filename_coastline

      ! Citywriter variables
      integer :: ncities
!      integer :: cityname_offset_px = 30
      real(kind=ip),dimension(:),allocatable     :: lon_cities
      real(kind=ip),dimension(:),allocatable     :: lat_cities
      character (len= 26),dimension(:),allocatable :: name_cities

      ! Contour variables
      integer           :: lev_i,substr_pos1,substr_pos2,substr_pos3  ! for parsing contour text files
      real(kind=sp)     :: lev_r4       ! used for testing contour levels from file
      integer           :: ilev         ! number of contour levels
      integer           :: ignulev      ! level index from gnuplot file
      integer           :: icurve       ! number of curves for level ilev
      integer           :: npts         ! number of points in curve ilev,icurve

      ! Plotting variables

      ! Gnuplot variables
      character(len=25) :: plotcom

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8  ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dmap_PNG_gnuplot"
      endif;enddo

      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)

      ! Test for coastline file
      ! The expected file is made available from http://gnuplotting.org/plotting-the-world-revisited/index.html
      ! The author converted coastline shapefiles from http://www.naturalearthdata.com/downloads/
      ! and provided contour files at three resolutions (110m, 50m, 10m). We only search for
      ! http://www.gnuplotting.org/data/world_50m.txt
      write(filename_coastline,'(a13)')"world_50m.txt"
      inquire(file=filename_coastline,exist=IsThere1)
      if(.not.IsThere1)then
        filename_coastline = trim(Ash3dHome) // &
                          DirDelim // 'share' // &
                          DirDelim // 'post_proc' // &
                          DirDelim // 'world_50m.txt'
        inquire(file=filename_coastline,exist=IsThere2)
        if(.not.IsThere2)then
          do io=1,2;if(VB(io).le.verbosity_error)then
            write(errlog(io),*)"Could not find required file world_50m.txt"
            write(errlog(io),*)"This file is available at:"
            write(errlog(io),*)"  http://www.gnuplotting.org/data/world_50m.txt"
            write(errlog(io),*)"Please download this file to the current working directory or"
#ifdef LINUX
            write(errlog(io),*)"copy to ${ASH3DHOME}/share/post_proc/"
            write(errlog(io),*)" e.g. /opt/USGS/Ash3d/share/post_proc/"
#endif
#ifdef MACOS
            write(errlog(io),*)"copy to ${ASH3DHOME}/share/post_proc/"
            write(errlog(io),*)" e.g. /opt/USGS/Ash3d/share/post_proc/"
#endif
#ifdef WINDOWS
            write(errlog(io),*)"copy to C:\opt\USGS\Ash3d\share\post_proc\"
#endif
          endif;enddo
          stop 1
        endif
      endif

      ncities = 20
      allocate(lon_cities(ncities))
      allocate(lat_cities(ncities))
      allocate(name_cities(ncities))

      filename_root        = "outvar"
      filename_outdata     = trim(adjustl(filename_root)) // ".dat"
      filename_script      = trim(adjustl(filename_root)) // ".gpi"
      filename_contourdata = trim(adjustl(filename_root)) // ".con"


      if(iprod.eq.5.or.iprod.eq.6)then
        cio='____final'
      else
        if (WriteTimes(itime).lt.10.0_ip) then
          write(cio,1) WriteTimes(itime)
1         format('00',f4.2,'hrs')
        elseif (WriteTimes(itime).lt.100.0_ip) then
          write(cio,2) WriteTimes(itime)
2         format('0',f5.2,'hrs')
        else
          write(cio,3) WriteTimes(itime)
3         format(f6.2,'hrs')
        endif
      endif

      if(Con_Cust)then
        nConLev = Con_Cust_N
        allocate(zrgb(nConLev,3))
        allocate(ContourLev(nConLev))
        ContourLev(1:nConLev) = Con_Cust_Lev(1:nConLev)
        zrgb(1:nConLev,1:3) = Con_Cust_RGB(1:nConLev,1:3)
      endif

      if(iprod.eq.3)then       ! deposit at specified times (mm)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.4)then   ! deposit at specified times (inches)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.5)then       ! deposit at final time (mm)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        cstr_zlabel = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.6)then   ! deposit at final time (inches)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        cstr_zlabel = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.7)then   ! ashfall arrival time (hours)
        varname = "depotime"
        write(filename_png,'(a22)')'DepositArrivalTime.png'
        write(title_plot,'(a20)')'Ashfall arrival time'
        cstr_zlabel = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.8)then   ! ashfall arrival at airports/POI (mm)
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for airport arrival time data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_gnuplot"
        endif;enddo
        stop 1
      elseif(iprod.eq.9)then   ! ash-cloud concentration
        varname = "ashcon_max"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudCon_t',cio,outfile_ext
        write(title_plot,'(a26,f7.2,a6)')'Ash-cloud concentration t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Max.Con.(mg/m3)'
        units = " (mg/m3)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudCon_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudCon_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudCon_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.10)then   ! ash-cloud height
        varname = "cloud_height"
        write(filename_png,'(a19,a9,a4)')'Ash3d_CloudHeight_t',cio,outfile_ext
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud height t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Height(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTop_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTop_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTop_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.11)then   ! ash-cloud bottom
        varname = "cloud_bottom"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudBot_t',cio,outfile_ext
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud bottom t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Bot.(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudBot_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudBot_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudBot_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.12)then   ! ash-cloud load
        varname = "cloud_load"
        write(filename_png,'(a17,a9,a4)')'Ash3d_CloudLoad_t',cio,outfile_ext
        write(title_plot,'(a17,f7.2,a6)')'Ash-cloud load t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Load(T/km2)'
        units = " (T/km2)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudLoad_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudLoad_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudLoad_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.13)then  ! radar reflectivity
        varname = "radar_reflectivity"
        write(filename_png,'(a20,a9,a4)')'Ash3d_CloudRadRefl_t',cio,outfile_ext
        write(title_plot,'(a24,f7.2,a6)')'Ash-cloud radar refl. t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Refl.(dBz)'
        units = " (dBz)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudRef_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudRef_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudRef_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.14)then   ! ashcloud arrival time (hours)
        varname = "ash_arrival_time"
        write(filename_png,'(a20)')'CloudArrivalTime.png'
        write(title_plot,'(a22)')'Ash-cloud arrival time'
        cstr_zlabel = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.15)then   ! topography
        varname = "topography"
        write(filename_png,'(a14)')'Topography.png'
        write(title_plot,'(a10)')'Topography'
        cstr_zlabel = 'Elevation (km)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = 8
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev = (/1.0_ip, 2.0_ip, 3.0_ip, 4.0_ip, &
                  5.0_ip, 6.0_ip, 7.0_ip, 8.0_ip/)
        endif
      elseif(iprod.eq.16)then   ! profile plots
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for vertical profile data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_gnuplot"
        endif;enddo
        stop 1
      else
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: unexpected variable"
          write(errlog(io),*)"         iprod = ",iprod
          write(errlog(io),*)"       Cannot map this variable."
        endif;enddo
        stop 1
      endif
      ! Now have string vars (varname,cstr_zlabel, etc.) and contour info (nConLev,zrgb,ContourLev)

      if(writeContours)then
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Running Gnuplot to calculate contours lines"
        endif;enddo
        write(filename_png,'(a14)')'tmp.png'
        allocate(ContourDataNcurves(nConLev))
        allocate(ContourDataNpoints(nConLev,CONTOUR_MAXCURVES))
        allocate(ContourDataX(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        allocate(ContourDataY(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        ContourDataNcurves(:)   = 0
        ContourDataNpoints(:,:) = 0
        ContourDataX(:,:,:)     = 0.0_ip
        ContourDataY(:,:,:)     = 0.0_ip
      else
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Running Gnuplot to generate contour plot"
        endif;enddo
      endif

      ! This is the section where we actually start plotting the map
      ! Evaluate grid
      if(IsLatLon)then
        if(lonUR-lonLL.ge.360.0_ip)then
          lonLL = 0.0_ip
          lonUR = 360.0_ip
        endif
        xmin = lonLL
        ! Make sure xmin is in the range -180->180
        if (xmin.gt.180.0_ip)then
          xmin = lonLL-360.0_ip
          xmax = lonUR-360.0_ip
        else
          xmax = lonUR
        endif
        ymin = latLL
        ymax = latUR
        if(abs(dn-de).lt.1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
      else
        xmin = xLL
        xmax = xUR
        ymin = yLL
        ymax = yUR
        if(abs(dx-dy).lt.1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
        !do io=1,2;if(VB(io).le.verbosity_error)then
        !  write(errlog(io),*)"ERROR: Currenntly, plotting with gnuplot only enabled for lon/lat grids."
        !  write(errlog(io),*)"       Please use GMT to plot projected maps."
        !  write(errlog(io),*)"       ./ASH3DPLOT=4 ./Ash3d_PostProc ...."
        !endif;enddo
        !stop 1
      endif

      ! write out the data in a form that gnuplot can read
      ! 3-column data
      open(unit=fid_outdata,file=filename_outdata,status='replace')
      do ii = 1,nx
        do jj = 1,ny
          if(lon_cc_pd(1).lt.180.0_ip)then
            tmp_ip = lon_cc_pd(ii)
          else
            tmp_ip = lon_cc_pd(ii)-360.0_ip
          endif
          if(abs(OutVar(ii,jj)-Fill_Value).lt.EPS_SMALL)then
            write(fid_outdata,*)tmp_ip,lat_cc_pd(jj),"NaN"
          else
            write(fid_outdata,*)tmp_ip,lat_cc_pd(jj),OutVar(ii,jj)
          endif
        enddo
        write(fid_outdata,*)""
      enddo
      close(fid_outdata)
      ! Finished temporary data file

      call citylist(2,                        &  ! 2 is for external file in gnuplot format
                    xmin,xmax,ymin,ymax,      &
                    ncities,                  &
                    lon_cities,               &
                    lat_cities,               &
                    name_cities)
      if(lon_volcano.gt.xmax)lon_volcano=lon_volcano-360.0_ip
      open(unit=fid_misc,file="volc.dat",status='replace')
      write(fid_misc,*)real(lon_volcano,kind=4),real(lat_volcano,kind=4),'""'
      close(fid_misc)

      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions.gt.1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'


      ! Set up to plot via gnuplot script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary gnuplot script for producing 2d maps for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"# You will need the coastline file http://www.gnuplotting.org/data/world_50m.txt"
      write(fid_script,'(g0)')"# copied to the cwd or ${ASH3DHOME}/share/post_proc/"
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"set terminal pngcairo font 'sans,12' size 854,603"   ! Set the image size
      linebuffer080 = "set output '" // trim(adjustl(filename_png)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      if(HaveIconFile)then
        write(fid_script,'(g0)')"set multiplot"
        write(fid_script,'(g0)')" "
        write(fid_script,'(g0)')"# Set logo plot"
        write(fid_script,'(g0)')"set size 0.2, 0.2"
        write(fid_script,'(g0)')"set origin 0.78, 0.0"
        write(fid_script,'(g0)')"unset key"
        write(fid_script,'(g0)')"unset tics"
        write(fid_script,'(g0)')"unset xlabel"
        write(fid_script,'(g0)')"unset ylabel"
        write(fid_script,'(g0)')"unset title"
        write(fid_script,'(g0)')"#unset border"
        write(fid_script,'(g0)')"unset label"
        write(fid_script,'(g0)')"set size ratio -1"
        linebuffer080 = 'plot "' // trim(adjustl(Instit_IconFile)) // '" binary filetype=png with rgbalpha'
        write(fid_script,'(g0)')trim(adjustl(linebuffer080))
        write(fid_script,'(g0)')" "
      else
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Institution Logo not found."
          write(outlog(io),*)"If you would like your logo on these maps, copy a"
          write(outlog(io),*)"small image (130x50) to ASH3DHOME/share/post_proc/logo.png"
        endif;enddo
      endif

      write(fid_script,'(g0)')"# Now main plot"
      write(fid_script,'(g0)')"set origin 0.05, .20"
      write(fid_script,'(g0)')"set size 0.85, 0.8"              ! Set x and y scale for plot
      linebuffer080 = "set ylabel '" // trim(adjustl(cstr_ylabel)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = "set xlabel '" // trim(adjustl(cstr_xlabel)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = "set title '" // trim(adjustl(title_plot)) // units // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')"set datafile missing 'NaN'"
      write(fid_script,'(a7,f10.4)')"XMIN = ",real(xmin,kind=4)
      write(fid_script,'(a7,f10.4)')"YMIN = ",real(ymin,kind=4)
      write(fid_script,'(a7,f10.4)')"XMAX = ",real(xmax,kind=4)
      write(fid_script,'(a7,f10.4)')"YMAX = ",real(ymax,kind=4)

      write(fid_script,'(g0)')"set xrange [XMIN:XMAX]"
      write(fid_script,'(g0)')"set yrange [YMIN:YMAX]"
      write(fid_script,'(g0)')"set contour base"
      write(fid_script,'(g0)')"set cntrparam bspline"
      linebuffer080 = "set cntrparam levels discrete " // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      do ilev=1,nConLev-1
        write(fid_script,'(f15.5,a2,a1)')real(ContourLev(ilev),kind=4),', ',bs  ! fails with nvhpc
      enddo
      write(fid_script,'(g0)')real(ContourLev(nConLev),kind=4)
      write(fid_script,'(g0)')"unset surface"
      ! Now write out the contours to a datafile
      write(fid_script,'(g0)')"set table 'outvar.con'"
      write(fid_script,'(g0)')"splot 'outvar.dat' using 1:2:3"
      write(fid_script,'(g0)')"unset table"
      write(fid_script,'(g0)')"set style line 2 lc rgb '#808080' lt 0 lw 1"
      write(fid_script,'(g0)')"set grid front ls 2"
      write(fid_script,'(g0)')"unset key"

      write(fid_script,'(g0)')"XVAL = XMIN-(XMAX-XMIN)*0.1"
      write(fid_script,'(g0)')"YVAL = YMIN-(YMAX-YMIN)*0.25"

      linebuffer130 = "set label '" // trim(adjustl(cstr_volcname)) // "' at XVAL, YVAL font 'sans,9' offset character 0,2"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_run_date)) // "' at XVAL, YVAL font 'sans,9' offset character 0,1"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_windfile)) // "' at XVAL, YVAL font 'sans,9' offset character 0,0"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      if(neruptions.gt.1)then
        linebuffer130 = "set label '" // trim(adjustl(cstr_note)) // "' at XVAL, YVAL font 'sans,9' offset character 0,-1"
        write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      endif

      write(fid_script,'(g0)')"XVAL = XMIN+(XMAX-XMIN)*0.4"
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErStartT)) // "' at XVAL, YVAL font 'sans,9' offset character 0,2"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErHeight)) // "' at XVAL, YVAL font 'sans,9' offset character 0,1"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErDuratn)) // "' at XVAL, YVAL font 'sans,9' offset character 0,0"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErVolume)) // "' at XVAL, YVAL font 'sans,9' offset character 0,-1"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))

      linebuffer130 ="plot '" // trim(adjustl(filename_coastline)) // &
                     "' with filledcurves linetype rgb '#dddddd' , " // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "   'outvar.con' using 1:2 with l lc rgb '#888888' , " // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 ="   '' every 1000 with labels font ',6' , " // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 ="   'cities.xy' using 1:2 , " // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 ="   '' using 1:2:3 with labels font ',10' point pointtype 7 offset char 1,1, " // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "   'volc.dat' using 1:2 , " // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      write(fid_script,'(g0)')"   '' using 1:2:3 with labels point pointtype 22 pointsize 2 lt rgb 'red'"
      if(HaveIconFile)then
        ! If we are including a logo via multiplot, close out multiplot environment
        write(fid_script,'(g0)')"unset multiplot"
      endif

      close(fid_script)

      write(plotcom,'(a11,a14)')'gnuplot -p ',filename_script
      call execute_command_line(plotcom,&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      if(writeContours)then

        ! Read outvar.con
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Now reading outvar.con and loading contour data."
        endif;enddo
        open(unit=fid_contourdata,file=filename_contourdata,status='old',err=9001)
        ! In the gnuplot contour file, all contours of a certain level have a header
        ! in the following format:
        !# Contour 0, label:      300
        ! Each curve for that level is separated by a blank line
        ! Gnuplot writes the contour data to file starting with the highest level
        ! so we will need to check with zlev(:) to make sure we populate ContourDat
        ! correctly.
        ilev = -1
        ignulev = -1
        read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080

        linebuffer050 = "Reading line from contour file"
        if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
        do while(iostatus.eq.0)
          ! Check if this is a header line
          read(linebuffer080,*,iostat=ioerr,iomsg=iomessage)testkey
          if(ioerr.lt.0)then
            ! if there was an error trying to read a character, then this is a blank
            ! line; check if we are in a contour block or still in the file header
            if(ignulev.eq.-1)then
              ! Still in file header
              ! Read the next line and cycle
              read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
              !if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
              cycle
            else
              ! Blank line in a contour block means we are starting another curve
              ! Increment the number of curves for this level
              ContourDataNcurves(ilev) = ContourDataNcurves(ilev) + 1
              if(ContourDataNcurves(ilev).gt.CONTOUR_MAXCURVES)then
                do io=1,2;if(VB(io).le.verbosity_error)then
                  write(errlog(io),*)"ERROR: Maximum number of curves for this level exceeded by gnuplot"
                  write(errlog(io),*)"       Current maximum set to CONTOUR_MAXCURVES = ",CONTOUR_MAXCURVES
                  write(errlog(io),*)"       Please increase CONTOUR_MAXCURVES and recompile."
                  write(errlog(io),*)"  Output_Vars.f90:CONTOUR_MAXCURVES"
                endif;enddo
                stop 1
              endif
              ! This is an easier index to use
              icurve = ContourDataNcurves(ilev)
            endif
          elseif(testkey.eq.'#')then
            ! This is a header line
            ! There are two possibilities:
            !  (1) a line of the file header
            !  (2) the start of a contour block
            !   if (2), then it will have this format:# Contour 0, label:      300
            substr_pos1 = index(linebuffer080,'Contour')

            if(substr_pos1.eq.0)then
              ! This is a file header line
              read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
              cycle
            else
              ! Here is the expected format, so start reading from character 10
              !# Contour 10, label:        2
              read(linebuffer080(10:),*,iostat=ioerr,iomsg=iomessage)ignulev
              linebuffer050 = "Reading line from contour file, ignulev"
              if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
              ! Now read the level. Look for the ':' to isolate the last bit
              substr_pos1 = index(linebuffer080,':')
              ! Also look for a '.' or an 'e' to see if the level value is written as a real or int
              substr_pos2 = index(linebuffer080,'.')
              substr_pos3 = index(linebuffer080(substr_pos1:),'e')
              if(substr_pos2.gt.0.or.substr_pos3.gt.0)then
                ! level is written as real
                read(linebuffer080(substr_pos1+1:),*,iostat=iostatus,iomsg=iomessage)lev_r4
                linebuffer050 = "Reading line from contour file, lev_r4"
                if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
              else
                read(linebuffer080(substr_pos1+1:),*,iostat=iostatus,iomsg=iomessage)lev_i
                linebuffer050 = "Reading line from contour file, lev_i"
                if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
                lev_r4 = real(lev_i,kind=4)
              endif
              ! The value for this new level ignulev is lev_r4, but we need to find which
              ! ContourLev this corresponds to
              do ii = 1,nConLev
                if(abs(lev_r4-real(ContourLev(ii),kind=4)).lt.EPS_SMALL)then
                  ilev=ii
                endif
              enddo
              ! When we have a new level, initialize the curve index for this level to 1
              ContourDataNcurves(ilev) = 1
              icurve = ContourDataNcurves(ilev)
            endif
          else
            ! This is the data section
            ! Increment the number of points
            ContourDataNpoints(ilev,icurve) = ContourDataNpoints(ilev,icurve) + 1
            if(ContourDataNpoints(ilev,icurve).gt.CONTOUR_MAXPOINTS)then
              do io=1,2;if(VB(io).le.verbosity_error)then
                write(errlog(io),*)"ERROR: Maximum number of points for this curve exceeded by GMT"
                write(errlog(io),*)"       Current maximum set to CONTOUR_MAXPOINTS = ",CONTOUR_MAXPOINTS
                write(errlog(io),*)"       Please increase CONTOUR_MAXPOINTS and recompile."
                write(errlog(io),*)"  Output_Vars.f90:CONTOUR_MAXPOINTS"
              endif;enddo
              stop 1
            endif
            npts = ContourDataNpoints(ilev,icurve)
            read(linebuffer080,*,iostat=iostatus,iomsg=iomessage) &
                       ContourDataX(ilev,icurve,npts),ContourDataY(ilev,icurve,npts)
            linebuffer050 = "Reading line from contour file, x,y"
            if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
          endif

          ! Try to read the next line
          read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
        enddo
        close(unit=fid_contourdata)

        ! Loop through all the levels and curves and trim any curves with zero length
        do ilev=1,nConLev
          icurve = CONTOUR_MAXCURVES + 1
          do ii = CONTOUR_MAXCURVES,1,-1
            if(ContourDataNpoints(ilev,ii).le.0)then
              ! log each curve number with no points
              icurve = ii
            endif
          enddo
          ContourDataNcurves(ilev) = max(0,icurve-1)
        enddo

      endif

      ! Clean up
      if (CleanScripts_gnuplot) then
        cmd = "rm -f outvar.dat outvar.gpi cities.xy volc.dat"
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      ! clean up memory
      if(allocated(lon_cities))         deallocate(lon_cities)
      if(allocated(lat_cities))         deallocate(lat_cities)
      if(allocated(name_cities))        deallocate(name_cities)
      if(allocated(zrgb))               deallocate(zrgb)

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dmap_PNG_gnuplot"
      endif;enddo

      return

      ! Error traps (starting with 9000)

9001  do io=1,2;if(VB(io).le.verbosity_error)then
        write(errlog(io),*)  'error: cannot open file: ',filename_contourdata
        write(errlog(io),*)  'Program stopped'
      endif;enddo
      stop 1

      end subroutine write_2Dmap_PNG_gnuplot

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dprof_PNG_gnuplot
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    vprof_ID        = ID of the profile (number in list from Ash3d control file)
!
!  This subroutine creates a png plot of the transient vertical profile of ash
!  concentration above the profile point (vprof_ID) using the gnuplot graphics
!  package.
!
!  To invoke:
!   ASH3DPLOT=3 ./Ash3d_PostProc 3d_tephra_fall.nc 16 3
!
!   Example script:
!     ##########################################################################
!     # Temporary gnuplot script for producing vertical profiles for Ash3d_PostProc
!     # Adjust to suit your needs.
!     ##########################################################################
!     set terminal pngcairo font 'sans,12' size 854,603
!     set output 'vprof_0001.png'
!     set multiplot
!
!     # Set logo plot
!     set size 0.2, 0.2
!     set origin 0.78, 0.0
!     unset key
!     unset tics
!     unset xlabel
!     unset ylabel
!     unset title
!     #unset border
!     unset label
!     set size ratio -1
!     plot "/opt/USGS/Ash3d/share/post_proc/logo.png" binary filetype=png with rgbalph
!
!     set origin 0, .15
!     set size 0.85, 0.9
!     set size ratio 0.75
!     set tics
!     set ylabel 'Height (km)'
!     set xlabel 'Time (hours after eruption)'
!     set title 'Cuernavaca (lon= -99.26, lat= 18.83)'
!     set isosamples 50
!     set pm3d
!     set palette cubehelix negative
!     unset surface
!     set view map
!     set key off
!     XMIN = 0.0
!     YMIN = 0.0
!     XMAX =    25.0000
!     YMAX =    14.8000
!     XVAL = -XMAX*0.2
!     YVAL = -YMAX*0.35
!     set label 'Volcano:  Popocatépetl' at XVAL, YVAL font 'sans,9' offset character 0,2
!     set label 'Run Date: 2026-01-16T21:49:00Z' at XVAL, YVAL font 'sans,9' offset character 0,1
!     set label 'Windfile:    25' at XVAL, YVAL font 'sans,9' offset character 0,0
!     XVAL = XMIN+(XMAX-XMIN)*0.4
!     set label 'Erup. Start Time:   2015-04-04T04:00:00Z' at XVAL, YVAL font 'sans,9' offset character 0,2
!     set label 'Erup. Plume Height: 12.0 km' at XVAL, YVAL font 'sans,9' offset character 0,1
!     set label 'Erup. Duration:      6.0 hours' at XVAL, YVAL font 'sans,9' offset character 0,0
!     set label 'Erup. Volume:        0.03000 km3 (DRE)' at XVAL, YVAL font 'sans,9' offset character 0,-1
!     set cblabel 'Ash conc. mg/m3'
!     splot 'vprof_0001.dat'
!     unset multiplot
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dprof_PNG_gnuplot(vprof_ID)

      use global_param,  only : &
         KG_2_MG,KM3_2_M3

      use mesh,          only : &
         IsLatLon,nzmax,z_cc_pd

      use Output_Vars,   only : &
         pr_ash,CLOUDCON_THRESH

      use io_data,       only : &
         Site_vprofile,x_vprofile,y_vprofile,cdf_b3l1,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap,ntmax,time_native

      integer,intent(in) :: vprof_ID

      logical            :: HaveIconFile
      character(len=76)  :: title_plot
      character(len=30)  :: cstr_xlabel = 'Time (hours after eruption)'
      character(len=30)  :: cstr_ylabel = 'Height (km)'
      character(len=30)  :: cstr_zlabel = 'Ash conc. mg/m3'
      character(len=30)  :: cstr_volcname
      character(len=30)  :: cstr_run_date
      character(len=30)  :: cstr_windfile
      character(len=40)  :: cstr_ErStartT
      character(len=27)  :: cstr_ErHeight
      character(len=30)  :: cstr_ErDuratn
      character(len=38)  :: cstr_ErVolume
      character(len=45)  :: cstr_note

      character(len=10)  :: filename_root
      character(len=14)  :: filename_script
      character(len=14)  :: filename_outdata
      character(len=14)  :: filename_png
      integer            :: fid_script   = 55
      integer            :: fid_outdata  = 54
      character(len=27)  :: coord_str
      character(len=80)  :: plotcom
      integer            :: i,k
      integer            :: iostatus
      integer            :: cstat
      character(len=120) :: iomessage
      integer            :: iw,iwf
      character(len= 80) :: linebuffer080
      character(len=130) :: linebuffer130
      character(len=200) :: cmd

      ! Plotting variables

      real(kind=ip) :: tmin    , zmin    , cmin      ! graph minima
      real(kind=ip) :: tmax    , zmax    , cmax      ! graph maxima
      real(kind=ip) :: tlab1   , zlab1   , clab1     ! graph first label
      real(kind=ip) :: tlabstep, zlabstep, clabstep  ! graph label increment
      real(kind=ip) :: cloudcon_thresh_mgm3

      ! Gnuplot variables

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8  ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dprof_PNG_gnuplot"
      endif;enddo

      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)

      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions.gt.1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      else
        write(cstr_note,'(a1)')" "
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'

      write(filename_root,52)vprof_ID
 52   format('vprof_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".gpi"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      ! Get min/max and label interval for all three axies.
      tmin=real(0,kind=ip)
      tmax=real(ceiling(time_native(ntmax)),kind=ip)
      tlab1    = 0.0_ip
      if(tmax.gt.240.0_ip)then
        tlabstep = 48.0_ip
      elseif(tmax.gt.120.0_ip)then
        tlabstep = 24.0_ip
      elseif(tmax.gt.30.0_ip)then
        tlabstep = 10.0_ip
      elseif(tmax.gt.15.0_ip)then
        tlabstep = 5.0_ip
      elseif(tmax.gt.6.0_ip)then
        tlabstep = 2.0_ip
      else
        tlabstep = 1.0_ip
      endif

      zmin=real(0,kind=ip)
      zmax=real(z_cc_pd(nzmax),kind=ip)
      zlab1    = 0.0_ip
      if(zmax.gt.30.0_ip)then
        zlabstep = 10.0_ip
      elseif(zmax.gt.15.0_ip)then
        zlabstep = 5.0_ip
      elseif(zmax.gt.6.0_ip)then
        zlabstep = 2.0_ip
      else
        zlabstep = 1.0_ip
      endif

      cloudcon_thresh_mgm3 = CLOUDCON_THRESH * KG_2_MG / KM3_2_M3  ! convert from kg/km3 to mg/m3
      cmin=real(0,kind=ip)
      cmax=real(maxval(pr_ash(:,:,vprof_ID)),kind=ip)    ! Get the max value for this profile
      cmin=real(min(cmin,cloudcon_thresh_mgm3),kind=ip)  ! Do not let cmax drop below the threshold
      if    (cmax.gt.4.0e4_ip)then
          clabstep = 5.0e3_ip
      elseif(cmax.gt.1.0e4_ip)then
          clabstep = 2.0e3_ip
      elseif(cmax.gt.4.0e3_ip)then
          clabstep = 5.0e2_ip
      elseif(cmax.gt.1.0e3_ip)then
          clabstep = 2.0e2_ip
      elseif(cmax.gt.4.0e2_ip)then
          clabstep = 5.0e1_ip
      elseif(cmax.gt.1.0e2_ip)then
          clabstep = 2.0e1_ip
      elseif(cmax.gt.4.0e1_ip)then
          clabstep = 5.0e0_ip
      elseif(cmax.gt.1.0e1_ip)then
          clabstep = 2.0e0_ip
      elseif(cmax.gt.1.0e0_ip)then
          clabstep = 5.0e-1_ip
      else
          clabstep = 1.0e-1_ip
      endif
      clab1    = 0.0_ip

      ! Prep data: gnuplot will load x y z data in column format
      open(unit=fid_outdata,file=filename_outdata,status='replace')
      do i = 1,ntmax
        do k = 1,nzmax
          write(fid_outdata,*)time_native(i),z_cc_pd(k),pr_ash(k,i,vprof_ID)
        enddo
        write(fid_outdata,*)""
      enddo
      close(fid_outdata)

      ! Build the plot title
      if(IsLatLon)then
        write(coord_str,101)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      else
        write(coord_str,102)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      endif
 101  format(' (lon=',f7.2,', lat=',f6.2,')')
 102  format(' (x=',f9.3,', y=',f9.3,')')
      write(title_plot,*)trim(adjustl(Site_vprofile(vprof_ID))),coord_str

      ! Set up to plot via gnuplot script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary gnuplot script for producing vertical profiles for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"set terminal pngcairo font 'sans,12' size 854,603"   ! Set the image size
      linebuffer080 = "set output '" // filename_png // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      if(HaveIconFile)then
        write(fid_script,'(g0)')"set multiplot"
        write(fid_script,'(g0)')" "
        write(fid_script,'(g0)')"# Set logo plot"
        write(fid_script,'(g0)')"set size 0.2, 0.2"
        write(fid_script,'(g0)')"set origin 0.78, 0.0"
        write(fid_script,'(g0)')"unset key"
        write(fid_script,'(g0)')"unset tics"
        write(fid_script,'(g0)')"unset xlabel"
        write(fid_script,'(g0)')"unset ylabel"
        write(fid_script,'(g0)')"unset title"
        write(fid_script,'(g0)')"#unset border"
        write(fid_script,'(g0)')"unset label"
        write(fid_script,'(g0)')"set size ratio -1"
        linebuffer080 = 'plot "' // trim(adjustl(Instit_IconFile)) // '" binary filetype=png with rgbalpha'
        write(fid_script,'(g0)')trim(adjustl(linebuffer080))
        write(fid_script,'(g0)')" "
      else
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Institution Logo not found."
          write(outlog(io),*)"If you would like your logo on these maps, copy a"
          write(outlog(io),*)"small image (130x50) to ASH3DHOME/share/post_proc/logo.png"
        endif;enddo
      endif

      write(fid_script,'(g0)')"set origin 0, .15"
      write(fid_script,'(g0)')"set size 0.85, 0.9"              ! Set x and y scale for plot
      write(fid_script,'(g0)')"set size ratio 0.75"
      write(fid_script,'(g0)')"set tics"
      linebuffer080 = "set ylabel '" // trim(adjustl(cstr_ylabel)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = "set xlabel '" // trim(adjustl(cstr_xlabel)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = "set title '" // trim(adjustl(title_plot)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')"set isosamples 50"
      write(fid_script,'(g0)')"set pm3d"
      write(fid_script,'(g0)')"set palette cubehelix negative"
      write(fid_script,'(g0)')"unset surface"
      write(fid_script,'(g0)')"set view map"
      write(fid_script,'(g0)')"set key off"

      write(fid_script,'(g0)')"XMIN = 0.0"
      write(fid_script,'(g0)')"YMIN = 0.0"
      write(fid_script,'(a7,f10.4)')"XMAX = ",time_native(ntmax)
      write(fid_script,'(a7,f10.4)')"YMAX = ",z_cc_pd(nzmax)
      write(fid_script,'(g0)')"XVAL = -XMAX*0.2"
      write(fid_script,'(g0)')"YVAL = -YMAX*0.35"

      linebuffer130 = "set label '" // trim(adjustl(cstr_volcname)) // "' at XVAL, YVAL font 'sans,9' offset character 0,2"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_run_date)) // "' at XVAL, YVAL font 'sans,9' offset character 0,1"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 ="set label '" // trim(adjustl(cstr_windfile)) // "' at XVAL, YVAL font 'sans,9' offset character 0,0"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      if(neruptions.gt.1)then
        linebuffer130 = "set label '" // trim(adjustl(cstr_note)) // "' at XVAL, YVAL font 'sans,9' offset character 0,-1"
        write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      endif

      write(fid_script,'(g0)')"XVAL = XMIN+(XMAX-XMIN)*0.4"
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErStartT)) // "' at XVAL, YVAL font 'sans,9' offset character 0,2"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErHeight)) // "' at XVAL, YVAL font 'sans,9' offset character 0,1"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErDuratn)) // "' at XVAL, YVAL font 'sans,9' offset character 0,0"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      linebuffer130 = "set label '" // trim(adjustl(cstr_ErVolume)) // "' at XVAL, YVAL font 'sans,9' offset character 0,-1"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))

      linebuffer080 = "set cblabel '" // trim(adjustl(cstr_zlabel)) // "'"
      write(fid_script,'(g0)')linebuffer080
      !write(fid_script,*)"set cblabel 'Ash con. in mg/m3'"
      linebuffer080 = "splot '" // filename_outdata // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      if(HaveIconFile)then
        ! If we are including a logo via multiplot, close out multiplot environment
        write(fid_script,'(g0)')"unset multiplot"
      endif

      close(fid_script)

      write(plotcom,'(a11,a14)')'gnuplot -p ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      ! Clean up
      if (CleanScripts_gnuplot) then
        cmd = "rm -f vprof_*dat vprof_*gpi"
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dprof_PNG_gnuplot"
      endif;enddo

      return

      end subroutine write_2Dprof_PNG_gnuplot

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_DepPOI_TS_PNG_gnuplot
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    pt_indx       = index of point in Ash3d netcdf output file
!
!  This subroutine creates a png plot of the transient deposit accumulation at
!  the airport/POI given by pt_index using the gnuplot graphics package.
!
!  To invoke:
!   ASH3DPLOT=3 ./Ash3d_PostProc 3d_tephra_fall.nc 8 2
!
!   Example script:
!     ##########################################################################
!     # Temporary gnuplot script for producing deposit time-series plots for Ash3d_PostProc
!     # Adjust to suit your needs.
!     ##########################################################################
!     set terminal png size 400,300
!     set key bmargin left horizontal Right noreverse enhanced autotitles box linetype -1 linewidth 1.000
!     set border 31 lw 2.0 lc rgb '#000000'
!     set style line 1 linecolor rgbcolor '#888888' linewidth 2.0 pt 7
!     set ylabel 'Deposit Thickeness (mm)'
!     set xlabel 'Time (hours after eruption)'
!     set nokey
!     set output 'depTS_0001.png'
!     set title 'Cuernavaca, Mexico                 '
!     plot [0:   25][0:  1] 'depTS_0001.dat' with filledcurve x1 ls 1
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_DepPOI_TS_PNG_gnuplot(pt_indx)

      use Output_Vars,   only : &
         THICKNESS_THRESH

      use Airports,      only : &
         Airport_Name,Airport_Thickness_TS

      use io_data,       only : &
         nWriteTimes,WriteTimes

      use time_data,     only : &
         Simtime_in_hours

      integer,intent(in) :: pt_indx

      real(kind=dp) :: ymaxpl
      character(len=10) :: filename_root
      character(len=14) :: filename_script
      character(len=14) :: filename_outdata
      character(len=14) :: filename_png
      integer           :: fid_outdata  = 54
      integer           :: fid_script  = 55
      integer           :: i
      character(len=25) :: plotcom
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      character(len=200):: cmd
      character(len= 80):: linebuffer080
      character(len=130):: linebuffer130

      integer,save      :: plot_index = 0

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_DepPOI_TS_PNG_gnuplot"
      endif;enddo

      if(Airport_Thickness_TS(pt_indx,nWriteTimes).lt.THICKNESS_THRESH)then
        return
      else
        plot_index = plot_index + 1
      endif

      write(filename_root,52)plot_index
 52   format('depTS_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".gpi"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      open(unit=fid_outdata,file=filename_outdata,status='replace')
      do i = 1,nWriteTimes
        write(fid_outdata,*)WriteTimes(i),Airport_Thickness_TS(pt_indx,i)
      enddo
      close(fid_outdata)

      if(Airport_Thickness_TS(plot_index,nWriteTimes).lt.THICKNESS_THRESH)then
        ymaxpl = 1.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.1.0_dp)then
        ymaxpl = 1.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.5.0_dp)then
        ymaxpl = 5.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.25.0_dp)then
        ymaxpl = 25.0_dp
      else
        ymaxpl = 100.0_dp
      endif

      ! Set up to plot via gnuplot script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary gnuplot script for producing deposit time-series plots for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"set terminal png size 400,300"
      linebuffer130 = "set key bmargin left horizontal Right noreverse enhanced " // &
                              "autotitles box linetype -1 linewidth 1.000"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      write(fid_script,'(g0)')"set border 31 lw 2.0 lc rgb '#000000'"
      write(fid_script,'(g0)')"set style line 1 linecolor rgbcolor '#888888' linewidth 2.0 pt 7"
      write(fid_script,'(g0)')"set ylabel 'Deposit Thickeness (mm)'"
      write(fid_script,'(g0)')"set xlabel 'Time (hours after eruption)'"
      write(fid_script,'(g0)')"set nokey"
      linebuffer080 = "set output '" // filename_png // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = "set title '" // Airport_Name(pt_indx) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
!      linebuffer080 = "plot [0:",ceiling(Simtime_in_hours),"][0:",&
!                      nint(ymaxpl),
      linebuffer080 = "] '" // filename_outdata // "' with filledcurve x1 ls 1"
      write(fid_script,'(a8,i5,a4,i3,a)')"plot [0:",ceiling(Simtime_in_hours),"][0:",&
                              nint(ymaxpl),trim(adjustl(linebuffer080))
      close(fid_script)

      write(plotcom,'(a11,a14)')'gnuplot -p ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      ! Clean up
      if (CleanScripts_gnuplot) then
        cmd = "rm -f depTS_*.dat depTS_*.gpi"
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_DepPOI_TS_PNG_gnuplot"
      endif;enddo

      return

      end subroutine write_DepPOI_TS_PNG_gnuplot

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      end module Ash3d_PostProc_gnuplot

!##############################################################################
