!##############################################################################
!
! Ash3d_PostProc_python module
!
! This module provides the subroutines that use python for creating 2d maps,
! 2d vertical profiles, and the little deposit accumulation plots linked to
! the airport arrival kml (ash_arrivaltimes_airports.kml).  Although a few
! third party API's are available, these subroutines create temporary script
! files that are run if python/matplotlib/cartopy are installed on the local system.
!
!      subroutine write_2Dmap_PNG_python
!      subroutine write_2Dprof_PNG_python
!      subroutine write_DepPOI_TS_PNG_python
!
!##############################################################################

      module Ash3d_PostProc_python

      use precis_param

      use io_units

      use global_param,  only : &
         DirDelim,EPS_SMALL

      use io_data,       only : &
         Ash3dHome

      implicit none

        ! Set everything to private by default
      private

        ! Publicly available subroutines/functions
      public write_2Dmap_PNG_python,   &
             write_2Dprof_PNG_python,  &
             write_DepPOI_TS_PNG_python

        ! Publicly available variables

      character(100) :: Instit_IconFile
      logical, public :: CleanScripts_python

      contains
      !------------------------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dmap_PNG_python
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    nx            = x length of output array OutVar
!    ny            = y length of output array OutVar
!    iprod         = product ID
!    itime         = time index from netcdf data file
!    OutVar        = 2-d array to be written to ASCII file
!    Fill_Value    = NaN value
!    writeContours = logical
!
!  This subroutine creates a png map of the variable in OutVar using the python
!  graphics package.  Annotations and contour levels are indicated via the
!  product ID (iprod).  If writeContours is set to true, then this subroutine
!  is only used for generating and storing the contours (for python, this is
!  through output files generated by the script) with no png written. If timestep = -1,
!  then use the last step in file
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dmap_PNG_python(nx,ny,iprod,itime,OutVar,Fill_Value,writeContours)

      use mesh,          only : &
         IsLatLon,lon_cc_pd,lat_cc_pd,de,dn, &
         x_cc_pd,y_cc_pd,lon_cc_pd,lat_cc_pd

      use Output_Vars,   only : &
         !ContourFilled, &
         Con_Cust,Con_Cust_N,Con_Cust_RGB,Con_Cust_Lev,&
         Con_DepThick_mm_N,Con_DepThick_mm_Lev,Con_DepThick_mm_RGB, &
         Con_DepThick_in_N,Con_DepThick_in_Lev,Con_DepThick_in_RGB, &
         Con_DepTime_N,Con_DepTime_Lev,Con_DepTime_RGB, &
         Con_CloudCon_N,Con_CloudCon_Lev,Con_CloudCon_RGB, &
         Con_CloudTop_N,Con_CloudTop_RGB,Con_CloudTop_Lev, &
         Con_CloudBot_N,Con_CloudBot_RGB,Con_CloudBot_Lev, &
         Con_CloudLoad_N,Con_CloudLoad_RGB,Con_CloudLoad_Lev, &
         Con_CloudRef_N,Con_CloudRef_RGB,Con_CloudRef_Lev, &
         Con_CloudTime_N,Con_CloudTime_RGB,Con_CloudTime_Lev, &
         ContourDataX,ContourDataY,ContourDataNcurves,ContourDataNpoints,&
         !CloudArrivalTime,Mask_Deposit,Mask_Cloud,&
         CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS,ContourLev,nConLev

      use io_units,      only : &
         fid_script,fid_outdata,fid_contourdata,fid_misc

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap

      use io_data,       only : &
         WriteTimes,cdf_b3l1,VolcanoName

      use Source,        only : &
         e_Volume,e_Duration,e_StartTime,e_PlumeHeight,lon_volcano,lat_volcano

      use citywriter

      use Ash3d_ASCII_IO,  only : &
          write_2D_ASCII_flt

      integer      ,intent(in) :: nx
      integer      ,intent(in) :: ny
      integer      ,intent(in) :: iprod
      integer      ,intent(in) :: itime
      real(kind=ip),intent(in) :: OutVar(nx,ny)
      real(kind=ip),intent(in) :: Fill_Value
      logical      ,intent(in) :: writeContours

      character(len=6)   :: Fill_Value_str
      character(len=200) :: cmd

      integer :: i,j,ii
      real(kind=ip) :: tmp_ip
      integer     , dimension(:,:),allocatable :: zrgb
      character(len=40) :: title_plot
      character(len=15) :: title_legend
      character(len=40) :: outfile_name
      character(len= 9) :: cio
      character(len= 4) :: outfile_ext = '.png'
      character(len=10) :: units

      real(kind=ip)  :: xmin
      real(kind=ip)  :: xmax
      real(kind=ip)  :: ymin
      real(kind=ip)  :: ymax

      character(len=9)  :: filename_script
      character(len=20) :: filename_outdata
      character(len=10) :: filename_contourdata

      !character(len=26) :: coord_str
      character(len=25) :: plotcom
      character(len=80) :: coastfile
      integer           :: ioerr
      integer           :: iostatus
      character(len=120):: iomessage
      integer           :: iw,iwf

      integer :: ncities
      real(kind=ip),dimension(:),allocatable     :: lon_cities
      real(kind=ip),dimension(:),allocatable     :: lat_cities
      character(len=26),dimension(:),allocatable :: name_cities
      logical           :: IsThere1,IsThere2
      character(len= 50):: linebuffer050 
      character(len= 80):: linebuffer080
      character(len=130):: linebuffer130,linebuffer130_2
      character(len=8)  :: outstr
      character         :: testkey
      integer           :: ilev,ignulev
      integer           :: lev_i,substr_pos1,substr_pos2,substr_pos3
      real(kind=4)      :: lev_r4
      integer           :: icurve,ipt

      character(len=20) :: varname

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          real(kind=8),intent(in) :: HoursSince
          integer     ,intent(in) :: byear
          logical     ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      !write(coastfile,'(a13)')"world_50m.txt"
      !inquire(file=coastfile,exist=IsThere1)
      !if(.not.IsThere1)then
      !  coastfile = trim(Ash3dHome) // &
      !                    DirDelim // 'share' // &
      !                    DirDelim // 'post_proc' // &
      !                    DirDelim // 'world_50m.txt'
      !  inquire(file=coastfile,exist=IsThere2)
      !  if(.not.IsThere2)then
      !    do io=1,2;if(VB(io).le.verbosity_error)then
      !      write(errlog(io),*)"Could not find required file world_50m.txt"
      !      write(errlog(io),*)"This file is available at:"
      !      write(errlog(io),*)"  http://www.pythonting.org/data/world_50m.txt"
      !      write(errlog(io),*)"Please download this file to the current working directory or"
!#ifdef! LINUX
      !      write(errlog(io),*)"copy to ${ASH3DHOME}/share/post_proc/"
      !      write(errlog(io),*)" e.g. /opt/USGS/Ash3d/share/post_proc/"
!#endif!
!#ifdef! MACOS
      !      write(errlog(io),*)"copy to ${ASH3DHOME}/share/post_proc/"
      !      write(errlog(io),*)" e.g. /opt/USGS/Ash3d/share/post_proc/"
!#endif!
!#ifdef! WINDOWS
      !      write(errlog(io),*)"copy to C:\opt\USGS\Ash3d\share\post_proc\"
!#endif!
      !    endif;enddo
      !    stop 1
      !  endif
      !endif

      ncities = 20
      allocate(lon_cities(ncities))
      allocate(lat_cities(ncities))
      allocate(name_cities(ncities))

      if(iprod.eq.5.or.iprod.eq.6)then
        cio='____final'
      else
        if (WriteTimes(itime).lt.10.0_ip) then
          write(cio,1) WriteTimes(itime)
1         format('00',f4.2,'hrs')
        elseif (WriteTimes(itime).lt.100.0_ip) then
          write(cio,2) WriteTimes(itime)
2         format('0',f5.2,'hrs')
        else
          write(cio,3) WriteTimes(itime)
3         format(f6.2,'hrs')
        endif
      endif

      if(Con_Cust)then
        nConLev = Con_Cust_N
        allocate(zrgb(nConLev,3))
        allocate(ContourLev(nConLev))
        ContourLev(1:nConLev) = Con_Cust_Lev(1:nConLev)
        zrgb(1:nConLev,1:3) = Con_Cust_RGB(1:nConLev,1:3)
      endif

      if(iprod.eq.3)then       ! deposit at specified times (mm)
        varname = "depothick"
        write(outfile_name,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f5.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        title_legend = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.4)then   ! deposit at specified times (inches)
        varname = "depothick"
        write(outfile_name,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f5.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        title_legend = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.5)then       ! deposit at final time (mm)
        varname = "depothickFin"
        write(outfile_name,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        title_legend = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.6)then   ! deposit at final time (inches)
        varname = "depothickFin"
        write(outfile_name,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        title_legend = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.7)then   ! ashfall arrival time (hours)
        varname = "depotime"
        write(outfile_name,'(a22)')'DepositArrivalTime.png'
        write(title_plot,'(a20)')'Ashfall arrival time'
        title_legend = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.8)then   ! ashfall arrival at airports/POI (mm)
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for airport arrival time data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_python"
        endif;enddo
        stop 1
      elseif(iprod.eq.9)then   ! ash-cloud concentration
        varname = "ashcon_max"
        write(outfile_name,'(a16,a9,a4)')'Ash3d_CloudCon_t',cio,outfile_ext
        write(title_plot,'(a26,f5.2,a6)')'Ash-cloud concentration t=',WriteTimes(itime),' hours'
        title_legend = 'Max.Con.(mg/m3)'
        units = " (mg/m3)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudCon_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudCon_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudCon_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.10)then   ! ash-cloud height
        varname = "cloud_height"
        write(outfile_name,'(a19,a9,a4)')'Ash3d_CloudHeight_t',cio,outfile_ext
        write(title_plot,'(a19,f5.2,a6)')'Ash-cloud height t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Height(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTop_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTop_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTop_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.11)then   ! ash-cloud bottom
        varname = "cloud_bottom"
        write(outfile_name,'(a16,a9,a4)')'Ash3d_CloudBot_t',cio,outfile_ext
        write(title_plot,'(a19,f5.2,a6)')'Ash-cloud bottom t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Bot.(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudBot_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudBot_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudBot_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.12)then   ! ash-cloud load
        varname = "cloud_load"
        write(outfile_name,'(a17,a9,a4)')'Ash3d_CloudLoad_t',cio,outfile_ext
        write(title_plot,'(a17,f5.2,a6)')'Ash-cloud load t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Load(T/km2)'
        units = " (T/km2)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudLoad_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudLoad_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudLoad_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.13)then  ! radar reflectivity
        varname = "radar_reflectivity"
        write(outfile_name,'(a20,a9,a4)')'Ash3d_CloudRadRefl_t',cio,outfile_ext
        write(title_plot,'(a24,f5.2,a6)')'Ash-cloud radar refl. t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Refl.(dBz)'
        units = " (dBz)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudRef_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudRef_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudRef_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.14)then   ! ashcloud arrival time (hours)
        varname = "ash_arrival_time"
        write(outfile_name,'(a20)')'CloudArrivalTime.png'
        write(title_plot,'(a22)')'Ash-cloud arrival time'
        title_legend = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.15)then   ! topography
        varname = "topography"
        write(outfile_name,'(a14)')'Topography.png'
        write(title_plot,'(a10)')'Topography'
        title_legend = 'Elevation (km)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = 8
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev = (/1.0_ip, 2.0_ip, 3.0_ip, 4.0_ip, &
                  5.0_ip, 6.0_ip, 7.0_ip, 8.0_ip/)
        endif
      elseif(iprod.eq.16)then   ! profile plots
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for vertical profile data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_python"
        endif;enddo
        stop 1
      else
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: unexpected variable"
          write(errlog(io),*)"         iprod = ",iprod
          write(errlog(io),*)"       Cannot map this variable."
        endif;enddo
        stop 1
      endif

      if(writeContours)then
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(outlog(io),*)"Running python to calculate contours lines"
        endif;enddo
        write(outfile_name,'(a14)')'tmp.png'
        allocate(ContourDataNcurves(nConLev))
        allocate(ContourDataNpoints(nConLev,CONTOUR_MAXCURVES))
        allocate(ContourDataX(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        allocate(ContourDataY(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        ContourDataNcurves(:)   = 0
        ContourDataNpoints(:,:) = 0
        ContourDataX(:,:,:)     = 0.0_ip
        ContourDataY(:,:,:)     = 0.0_ip
      else
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(outlog(io),*)"Running python to generate contour plot"
        endif;enddo
      endif

      write(filename_outdata,52) "          outvar.dat"
      write(filename_contourdata,53) "outvar.con"
      write(filename_script,54) "outvar.py"
 52   format(a20)
 53   format(a10)
 54   format(a9)

      if(IsLatLon)then
        xmin = minval(lon_cc_pd(1:nx))
        ! Make sure xmin is in the range -180->180
        if (xmin.gt.180.0_ip)then
          xmin = minval(lon_cc_pd(1:nx))-360.0_ip
          xmax = maxval(lon_cc_pd(1:nx))-360.0_ip
        else
          xmax = maxval(lon_cc_pd(1:nx))
        endif
        ymin = minval(lat_cc_pd(1:ny))
        ymax = maxval(lat_cc_pd(1:ny))
      else
        xmin = minval(x_cc_pd(1:nx))
        xmax = maxval(x_cc_pd(1:nx))
        ymin = minval(y_cc_pd(1:ny))
        ymax = maxval(y_cc_pd(1:ny))
      endif
      call citylist(2,xmin,xmax,ymin,ymax, &
                      ncities,                        &
                      lon_cities,lat_cities,          &
                      name_cities)

      if(lon_volcano.gt.xmax)lon_volcano=lon_volcano-360.0_ip

      !  Local Logo
      !   First check is a local logo in installed on this system
      Instit_IconFile= trim(Ash3dHome) // &
                        DirDelim // 'share' // &
                        DirDelim // 'post_proc' // &
                        DirDelim // 'logo.png'
      inquire( file=trim(adjustl(Instit_IconFile)), exist=IsThere1)

      if (.not.IsThere1) then
        !  USGS Logo (130x49)
        !   No local logo, open the USGS version
        Instit_IconFile= trim(Ash3dHome) // &
                          DirDelim // 'share' // &
                          DirDelim // 'post_proc' // &
                          DirDelim // 'USGSvid.png'
        inquire( file=trim(adjustl(Instit_IconFile)), exist=IsThere1)
      endif

      ! write out the data in a form that python can read
      ! Python script expects an ESRI ASCII data file
      call write_2D_ASCII_flt(nx,ny,IsLatLon,real(xmin,kind=sp),real(ymin,kind=sp),.true., &
                         real(de,kind=sp),real(dn,kind=sp),Fill_Value_str,&
                         real(OutVar,kind=sp),filename_outdata)

      open(unit=fid_misc,file="volc.dat",status='replace')
      write(fid_misc,*)real(lon_volcano,kind=4),real(lat_volcano,kind=4),'""'
      close(fid_misc)

      ! Set up to plot via python script
      open(unit=fid_script,file=filename_script,status='replace')

      ! Python mapping expects matplotlib and cartopy for geographic mapping.
      ! Additinoally, gdal and geopandas are needed for loading ASCII files
      ! and handling geospatial data. We recommend using Anaconda:
      !
      ! (1) Download anaconda:
      !   curl -O https://repo.anaconda.com/archive/Anaconda3-2025.06-0-Linux-x86_64.sh
      ! 
      ! (2) Install:
      !   bash ~/Anaconda3-2025.06-0-Linux-x86_64.sh
      !  Accept terms of service.
      !  Accept default install location: ~/anaconda3
      !  Choose 'no' when asked about editing start-up scripts.
      ! 
      ! (3) Initialize anaconda manually.
      !   export PATH="$HOME/anaconda3/bin:$PATH"
      !   conda init
      ! 
      ! (4) Install the packages your script needs:
      !   conda install -c conda-forge geopandas
      !   conda install -c scitools cartopy
      !   conda install -c gdal

      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary python/cartopy script for producing 2d maps for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"# This script draws heavily from scripts created by Tyler Paladino."
      write(fid_script,'(g0)')"# You will need the packages conda-forge, geopandas, scitools, cartopy, gdal"
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"import cartopy.feature as cfeature"
      write(fid_script,'(g0)')"import cartopy.crs as ccrs"
      write(fid_script,'(g0)')"import matplotlib.pyplot as plt"
      write(fid_script,'(g0)')"from mpl_toolkits.axes_grid1.inset_locator import inset_axes"
      write(fid_script,'(g0)')"import matplotlib.image as mpimg"
      write(fid_script,'(g0)')"from matplotlib.colors import LinearSegmentedColormap"
      write(fid_script,'(g0)')"from matplotlib.offsetbox import OffsetImage, AnnotationBbox, TextArea"
      write(fid_script,'(g0)')"import numpy as np"
      write(fid_script,'(g0)')"from osgeo import gdal, osr"
      write(fid_script,'(g0)')"import linecache"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"def get_extent(gdal_ds, A3D_input_fn):"
      write(fid_script,'(g0)')"    Xsize = gdal_ds.RasterXSize"
      write(fid_script,'(g0)')"    Ysize = gdal_ds.RasterYSize"
      write(fid_script,'(g0)')"    cellsize = gdal_ds.GetGeoTransform()[1]"
      write(fid_script,'(g0)')"    xcorner, ycorner = get_proj_info(A3D_input_fn)"
      write(fid_script,'(g0)')"    minx = xcorner+cellsize"
      write(fid_script,'(g0)')"    miny = ycorner+cellsize"
      write(fid_script,'(g0)')"    maxx = minx + (cellsize*Xsize)"
      write(fid_script,'(g0)')"    maxy = miny + (cellsize*Ysize)"
      write(fid_script,'(g0)')"    return [minx, maxx, miny, maxy]"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"def get_proj_info(fn):"
      write(fid_script,'(g0)')"    xl_corner = linecache.getline(fn, 3)"
      write(fid_script,'(g0)')"    yl_corner = linecache.getline(fn, 4)"
      write(fid_script,'(g0)')"    return float(xl_corner.split()[1]), float(yl_corner.split()[1])"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"def draw_logo(ax,fn):"
      write(fid_script,'(g0)')"    # Create background box"
      write(fid_script,'(g0)')"    ax_inset = inset_axes("
      write(fid_script,'(g0)')"        ax,"
      write(fid_script,'(g0)')'        width="18%",'
      write(fid_script,'(g0)')'        height="7%",'
      write(fid_script,'(g0)')"        borderpad=.5,"
      write(fid_script,'(g0)')'        loc="upper right"'
      write(fid_script,'(g0)')"    )"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    img = mpimg.imread(fn)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    # ax.patch.set_alpha(0.5)"
      write(fid_script,'(g0)')"    # Remove axis borders"
      write(fid_script,'(g0)')"    # ax_inset.set_axis_off()"
      write(fid_script,'(g0)')"    ax_inset.set_xticks([])"
      write(fid_script,'(g0)')"    ax_inset.set_yticks([])"
      write(fid_script,'(g0)')"    ax_inset.set_facecolor([1,1,1,0.8])"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    ax_logo = inset_axes("
      write(fid_script,'(g0)')"        ax_inset,"
      write(fid_script,'(g0)')'        width="90%",'
      write(fid_script,'(g0)')'        height="90%",'
      write(fid_script,'(g0)')'        loc="center"'
      write(fid_script,'(g0)')"    )"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    ax_logo.imshow(img)"
      write(fid_script,'(g0)')"    ax_logo.set_axis_off()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    return None"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Institutional logo (Defaults to USGS)"
      linebuffer080 = "logo_file = '" // trim(adjustl(Instit_IconFile)) // "'"
      write(fid_script,'(g0)')linebuffer080
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Run values"
      write(fid_script,'(g0,f10.3)')"srcx=",lon_volcano
      write(fid_script,'(g0,f10.3)')"srcy=",lat_volcano
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"#######################################"
      write(fid_script,'(g0)')"# Product values"
      write(fid_script,'(g0)')'grid_file="outvar.dat"'
      linebuffer080 = 'title_plot="'// trim(adjustl(title_plot)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 = 'title_legend="' // trim(adjustl(title_legend)) // '"'
      write(fid_script,'(g0)')linebuffer080

      linebuffer130  ="clevels=["
      linebuffer130_2="tlevels=['"
      do i=1,nConLev
        write(outstr,'(e8.3)')ContourLev(i)
        linebuffer130 = trim(adjustl(linebuffer130)) // outstr
        if(i.lt.nConLev) linebuffer130 = trim(adjustl(linebuffer130)) // ','
        linebuffer130_2 = trim(adjustl(linebuffer130_2)) // outstr
        if(i.lt.nConLev) then
          linebuffer130_2 = trim(adjustl(linebuffer130_2)) // "','"
        else
          linebuffer130_2 = trim(adjustl(linebuffer130_2)) // "']"
        endif
      enddo
      linebuffer130 = trim(adjustl(linebuffer130)) // ']'
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      do i=1,nConLev
        if (i.eq.1)then
          write(linebuffer080,101)real(zrgb(i,1:3)/255.0,kind=4)
        elseif(i.eq.nConLev)then
          write(linebuffer080,103)real(zrgb(i,1:3)/255.0,kind=4)
        else
          write(linebuffer080,102)real(zrgb(i,1:3)/255.0,kind=4)
        endif
        write(fid_script,'(g0)')linebuffer080
      enddo
 101  format('ccolors=[( ',f5.2,',',f5.2,',',f5.2,'),' )
 102  format('         ( ',f5.2,',',f5.2,',',f5.2,'),' )
 103  format('         ( ',f5.2,',',f5.2,',',f5.2,')]' )
      write(fid_script,'(g0)')trim(adjustl(linebuffer130_2))
      write(fid_script,'(g0)')" "
      linebuffer080 = 'txt_vname_dat="' // trim(adjustl(VolcanoName)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 = 'txt_RunDate_dat="' // trim(adjustl(os_time_log)) // '"'
      write(fid_script,'(g0)')linebuffer080
      read(cdf_b3l1,*,iostat=ioerr) iw,iwf
      write(linebuffer080,'(a18,i2,a1)')'txt_Windfile_dat="' , iwf , '"'
      write(fid_script,'(g0)')linebuffer080
      write(linebuffer080,'(a18,a20,a1)')'txt_ESrtTime_dat="',HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap),'"'
      write(fid_script,'(g0)')linebuffer080
      write(linebuffer080,'(a15,g10.5,a1)')'txt_EPlmH_dat="',real(e_PlumeHeight(1),kind=4),'"'
      write(fid_script,'(g0)')linebuffer080
      write(linebuffer080,'(a14,g10.5,a1)')'txt_EDur_dat="',real(e_Duration(1),kind=4),'"'
      write(fid_script,'(g0)')linebuffer080
      write(linebuffer080,'(a14,g10.5,a1)')'txt_EVol_dat="',real(e_Volume(1),kind=4),'"'
      write(fid_script,'(g0)')linebuffer080
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"#######################################"
      write(fid_script,'(g0)')'txt_vname="Volcano: "'
      write(fid_script,'(g0)')'txt_RunDate="Run Date: "'
      write(fid_script,'(g0)')'txt_Windfile="Windfile: "'
      write(fid_script,'(g0)')'txt_ESrtTime="Erup. Start Time: "'
      write(fid_script,'(g0)')'txt_EPlmH="Erup Plume Height: "'
      write(fid_script,'(g0)')'txt_EDur="Erup. Duration: "'
      write(fid_script,'(g0)')'txt_EVol="Erup. Volume: "'
      write(fid_script,'(g0)')'txt_EPlmH_unit=" km"'
      write(fid_script,'(g0)')'txt_EDur_unit=" hours"'
      write(fid_script,'(g0)')'txt_EVol_unit=" km3 (DRE)"'
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')'annotation_text1 = txt_vname    + txt_vname_dat   + "\n" + \'
      write(fid_script,'(g0)')'                   txt_RunDate  + txt_RunDate_dat + "\n" + \'
      write(fid_script,'(g0)')'                   txt_Windfile + txt_Windfile_dat'
      write(fid_script,'(g0)')'annotation_text2 = txt_ESrtTime + txt_ESrtTime_dat + "\n" + \'
      write(fid_script,'(g0)')'                   txt_EPlmH    + txt_EPlmH_dat    + txt_EPlmH_unit + "\n" + \'
      write(fid_script,'(g0)')'                   txt_EDur     + txt_EDur_dat     + txt_EDur_unit  + "\n" + \'
      write(fid_script,'(g0)')'                   txt_EVol     + txt_EVol_dat     + txt_EVol_unit'
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"###################### OPEN ASH DATA FILE AND GET GEOTRANSFORM #######################"
      write(fid_script,'(g0)')"# Open raster with GDAL"
      write(fid_script,'(g0)')"raster = gdal.Open(grid_file)"
      write(fid_script,'(g0)')"# Get lat/lon extent of raster"
      write(fid_script,'(g0)')"extent = get_extent(raster, grid_file)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"############################# PLOT ######################################"
      write(fid_script,'(g0)')"# Create figure"
      write(fid_script,'(g0)')"main_fig = plt.figure(figsize=(8.5, 6))"
      write(fid_script,'(g0)')"# Create geospatial matplotlib axes with CartoPy."
      write(fid_script,'(g0)')"# Use a PlateCarree projection for now"
      write(fid_script,'(g0)')"cen_lon=0.5*(sum(extent))"
      write(fid_script,'(g0)')"img_extent = extent"
      write(fid_script,'(g0)')"projection = ccrs.PlateCarree(central_longitude=cen_lon)  ",&
                        "# this is the Cartopy bit"
      write(fid_script,'(g0)')"map_ax = main_fig.add_subplot(4,1,(1,3),projection=projection) ",&
                        "# create the matplotlib mapping with this projection"
      write(fid_script,'(g0)')"map_ax.set_extent(img_extent)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Add coastlines and water"
      write(fid_script,'(g0)')"map_ax.add_feature(cfeature.LAND, facecolor='lightgrey')"
      write(fid_script,'(g0)')"map_ax.coastlines()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Add gridlines"
      write(fid_script,'(g0)')"gl = map_ax.gridlines(draw_labels=True,"
      write(fid_script,'(g0)')"                      x_inline=False,"
      write(fid_script,'(g0)')"                      y_inline=False,"
      write(fid_script,'(g0)')"                      color='black',"
      write(fid_script,'(g0)')"                      alpha=0.5,"
      write(fid_script,'(g0)')"                      linestyle='--')"
      write(fid_script,'(g0)')"# Get rid of top and right side labels"
      write(fid_script,'(g0)')"gl.top_labels = False"
      write(fid_script,'(g0)')"gl.right_labels = False"
      write(fid_script,'(g0)')"# Get grided data from GDAL dataset"
      write(fid_script,'(g0)')"data = raster.GetRasterBand(1).ReadAsArray()"
      write(fid_script,'(g0)')"# Mask out any values that are = to fill_value"
      write(fid_script,'(g0)')"Fill_Value=0"
      write(fid_script,'(g0)')"data_masked = np.ma.masked_where(data==Fill_Value, data)"
      write(fid_script,'(g0)')"# Plot filled contours onto axes"
      write(fid_script,'(g0)')"filled_contours = map_ax.contourf(data_masked,"
      write(fid_script,'(g0)')"                                  extent=extent,"
      write(fid_script,'(g0)')"                                  origin='upper',"
      write(fid_script,'(g0)')"                                  transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                                  levels=clevels,"
      write(fid_script,'(g0)')"                                  colors=ccolors,"
      write(fid_script,'(g0)')"                                  alpha=0.6)"
      write(fid_script,'(g0)')"# Also add line contours"
      write(fid_script,'(g0)')'custom_cmap = LinearSegmentedColormap.from_list("my_cmap", ccolors)'
      write(fid_script,'(g0)')"line_contours = map_ax.contour(data_masked,"
      write(fid_script,'(g0)')"                               extent=extent,"
      write(fid_script,'(g0)')"                               origin='upper',"
      write(fid_script,'(g0)')"                               levels=clevels,"
      write(fid_script,'(g0)')"                               colors='black',"
      write(fid_script,'(g0)')"                               linewidths=0.5,"
      write(fid_script,'(g0)')"                               transform=ccrs.PlateCarree())"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Create proxies for contour colors for legend later on"
      write(fid_script,'(g0)')"proxy = [plt.Rectangle((0,0),1,1,fc = pc.get_facecolor()[0])"
      write(fid_script,'(g0)')"    for pc in filled_contours.collections]"
      write(fid_script,'(g0)')"# Plot source location as red triangle"
      write(fid_script,'(g0)')"volc_map = map_ax.scatter(srcx,srcy,"
      write(fid_script,'(g0)')"                          s=60,"
      write(fid_script,'(g0)')"                          color = 'm',"
      write(fid_script,'(g0)')"                          marker='^',"
      write(fid_script,'(g0)')"                          transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                          edgecolors='black',"
      write(fid_script,'(g0)')"                          zorder=3)"
      write(fid_script,'(g0)')"city_x=[]"
      write(fid_script,'(g0)')"city_y=[]"
      write(fid_script,'(g0)')"city_n=[]"
      write(fid_script,'(g0)')"try:"
      write(fid_script,'(g0)')"  with open('cities.xy','r') as f:"
      write(fid_script,'(g0)')"    for line in f:"
      write(fid_script,'(g0)')"      parts = line.strip().split()"
      write(fid_script,'(g0)')"      if len(parts) == 3:"
      write(fid_script,'(g0)')"        city_x.append(float(parts[0]))"
      write(fid_script,'(g0)')"        city_y.append(float(parts[1]))"
      write(fid_script,'(g0)')"        city_n.append(parts[2])"
      write(fid_script,'(g0)')"except FileNotFoundError:"
      write(fid_script,'(g0)')'    print("Error: cities.xy not found.")'
      write(fid_script,'(g0)')"    exit()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"city_map = map_ax.scatter(city_x,city_y,"
      write(fid_script,'(g0)')"                          s=40,"
      write(fid_script,'(g0)')"                          color = 'k',"
      write(fid_script,'(g0)')"                          marker='o',"
      write(fid_script,'(g0)')"                          transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                          edgecolors='black',"
      write(fid_script,'(g0)')"                          zorder=3)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"for i, label in enumerate(city_n):"
      write(fid_script,'(g0)')'    city_name=label.replace("\"", "")'
      write(fid_script,'(g0)')"    map_ax.annotate(city_name,"
      write(fid_script,'(g0)')"                    xy=(city_x[i], city_y[i]),"
      write(fid_script,'(g0)')"                    xytext=(3, 3),"
      write(fid_script,'(g0)')'                    textcoords="offset points",'
      write(fid_script,'(g0)')"                    transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                    annotation_clip=True,"
      write(fid_script,'(g0)')"                    fontsize=10,"
      write(fid_script,'(g0)')"                    fontweight=300,"
      write(fid_script,'(g0)')'                    color="black")'
      write(fid_script,'(g0)')"# Draw legend"
      write(fid_script,'(g0)')"map_ax.legend(proxy,tlevels,loc='center left', bbox_to_anchor=(1.05, 0.5),"
      write(fid_script,'(g0)')"                framealpha=0.9,title=title_legend)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Draw USGS logo"
      write(fid_script,'(g0)')"logo = mpimg.imread(logo_file)"
      write(fid_script,'(g0)')"main_fig.figimage(logo, 700, 50, zorder=3, alpha=0.7) ",&
                        "# Adjust position, zorder, and alpha as needed"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Annotations"
      write(fid_script,'(g0)')"map_ax.annotate(annotation_text1,"
      write(fid_script,'(g0)')"            xy=(0.1, 0.05),xycoords='figure fraction',xytext=(20, 20),"
      write(fid_script,'(g0)')"            textcoords='offset points',va='bottom',ha='left')"
      write(fid_script,'(g0)')"map_ax.annotate(annotation_text2,"
      write(fid_script,'(g0)')"            xy=(0.4, 0.05),xycoords='figure fraction',xytext=(20, 20),"
      write(fid_script,'(g0)')"            textcoords='offset points',va='bottom',ha='left')"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"main_fig.tight_layout()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"plt.title(title_plot)"
      linebuffer080 = "main_fig.savefig(f'" // trim(adjustl(outfile_name)) // "',dpi=100)"
      write(fid_script,'(g0)')linebuffer080

      ! before exiting the script, write out contour data if needed.
!for c in range(len(contours)):
!    n_contour = contours[c]
!    for d in range(len(n_contour)):
!        XY_Coordinates = n_contour[d]
!        print(XY_Coordinates)

      close(fid_script)

      write(plotcom,'(a11,a14)')'python ',filename_script
      call execute_command_line(plotcom,exitstat=iostatus)

!      if(writeContours)then
!
!        ! Read outvar.con
!        do io=1,2;if(VB(io).le.verbosity_info)then
!          write(outlog(io),*)"Now reading outvar.con and loading contour data."
!        endif;enddo
!        open(unit=fid_contourdata,file=filename_contourdata,status='old',err=9001)
!        ! In the python contour file, all contours of a certain level have a header
!        ! in the following format:
!        !# Contour 0, label:      300
!        ! Each curve for that level is separated by a blank line
!        ! Gnuplot writes the contour data to file starting with the highest level
!        ! so we will need to check with zlev(:) to make sure we populate ContourDat
!        ! correctly.
!        ilev = -1
!        ignulev = -1
!        read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
!
!        linebuffer050 = "Reading line from contour file"
!        if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
!        do while(iostatus.eq.0)
!          ! Check if this is a header line
!          read(linebuffer080,*,iostat=ioerr,iomsg=iomessage)testkey
!          if(ioerr.lt.0)then
!            ! if there was an error trying to read a character, then this is a blank
!            ! line; check if we are in a contour block or still in the file header
!            if(ignulev.eq.-1)then
!              ! Still in file header
!              ! Read the next line and cycle
!              read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
!              !if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
!              cycle
!            else
!              ! Blank line in a contour block means we are starting another curve
!              ! Increment the number of curves for this level
!              ContourDataNcurves(ilev) = ContourDataNcurves(ilev) + 1
!              if(ContourDataNcurves(ilev).gt.CONTOUR_MAXCURVES)then
!                do io=1,2;if(VB(io).le.verbosity_error)then
!                  write(errlog(io),*)"ERROR: Maximum number of curves for this level exceeded by python"
!                  write(errlog(io),*)"       Current maximum set to CONTOUR_MAXCURVES = ",CONTOUR_MAXCURVES
!                  write(errlog(io),*)"       Please increase CONTOUR_MAXCURVES and recompile."
!                  write(errlog(io),*)"  Output_Vars.f90:CONTOUR_MAXCURVES"
!                endif;enddo
!                stop 1
!              endif
!              ! This is an easier index to used
!              icurve = ContourDataNcurves(ilev)
!            endif
!          elseif(testkey.eq.'#')then
!            ! This is a header line
!            ! There are two possibilities:
!            !  (1) a line of the file header
!            !  (2) the start of a contour block
!            !   if (2), then it will have this format:# Contour 0, label:      300
!            substr_pos1 = index(linebuffer080,'Contour')
!
!            if(substr_pos1.eq.0)then
!              ! This is a file header line
!              read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
!              cycle
!            else
!              ! Here is the expected format, so start reading from character 10
!              !# Contour 10, label:        2
!              read(linebuffer080(10:),*,iostat=ioerr,iomsg=iomessage)ignulev
!              linebuffer050 = "Reading line from contour file, ignulev"
!              if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
!              ! Now read the level. Look for the ':' to isolate the last bit
!              substr_pos1 = index(linebuffer080,':')
!              ! Also look for a '.' or an 'e' to see if the level value is written as a real or int
!              substr_pos2 = index(linebuffer080,'.')
!              substr_pos3 = index(linebuffer080(substr_pos1:),'e')
!              if(substr_pos2.gt.0.or.substr_pos3.gt.0)then
!                ! level is written as real
!                read(linebuffer080(substr_pos1+1:),*,iostat=iostatus,iomsg=iomessage)lev_r4
!                linebuffer050 = "Reading line from contour file, lev_r4"
!                if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
!              else
!                read(linebuffer080(substr_pos1+1:),*,iostat=iostatus,iomsg=iomessage)lev_i
!                linebuffer050 = "Reading line from contour file, lev_i"
!                if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
!                lev_r4 = real(lev_i,kind=4)
!              endif
!              ! The value for this new level ignulev is lev_r4, but we need to find which
!              ! ContourLev this corresponds to
!              do ii = 1,nConLev
!                if(abs(lev_r4-real(ContourLev(ii),kind=4)).lt.EPS_SMALL)then
!                  ilev=ii
!                endif
!              enddo
!              ! When we have a new level, initialize the curve index for this level to 1
!              ContourDataNcurves(ilev) = 1
!              icurve = ContourDataNcurves(ilev)
!            endif
!          else
!            ! This is the data section
!            ! Increment the number of points
!            ContourDataNpoints(ilev,icurve) = ContourDataNpoints(ilev,icurve) + 1
!            if(ContourDataNpoints(ilev,icurve).gt.CONTOUR_MAXPOINTS)then
!              do io=1,2;if(VB(io).le.verbosity_error)then
!                write(errlog(io),*)"ERROR: Maximum number of points for this curve exceeded by GMT"
!                write(errlog(io),*)"       Current maximum set to CONTOUR_MAXPOINTS = ",CONTOUR_MAXPOINTS
!                write(errlog(io),*)"       Please increase CONTOUR_MAXPOINTS and recompile."
!                write(errlog(io),*)"  Output_Vars.f90:CONTOUR_MAXPOINTS"
!              endif;enddo
!              stop 1
!            endif
!            ipt = ContourDataNpoints(ilev,icurve)
!            read(linebuffer080,*,iostat=iostatus,iomsg=iomessage) &
!                       ContourDataX(ilev,icurve,ipt),ContourDataY(ilev,icurve,ipt)
!            linebuffer050 = "Reading line from contour file, x,y"
!            if(iostatus.ne.0) call FileIO_Error_Handler(iostatus,linebuffer050,linebuffer080,iomessage)
!          endif
!
!          ! Try to read the next line
!          read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
!        enddo
!        close(unit=fid_contourdata)
!
!        ! Loop through all the levels and curves and trim any curves with zero length
!        do i=1,nConLev
!          icurve = CONTOUR_MAXCURVES + 1
!          do ii = CONTOUR_MAXCURVES,1,-1
!            if(ContourDataNpoints(i,ii).le.0)then
!              ! log each curve number with no points
!              icurve = ii
!            endif
!          enddo
!          ContourDataNcurves(i) = max(0,icurve-1)
!        enddo
!
!      endif

      ! Clean up
      if (CleanScripts_python) then
        cmd = "rm -f outvar.* cities.xy volc.dat"
        call execute_command_line(trim(adjustl(cmd)))
      endif

      ! clean up memory
      if(allocated(lon_cities))         deallocate(lon_cities)
      if(allocated(lat_cities))         deallocate(lat_cities)
      if(allocated(name_cities))        deallocate(name_cities)
      if(allocated(zrgb))               deallocate(zrgb)

      return

      ! Error traps (starting with 9000)
      ! For this subroutine, the 100's position refers to block # of control file

9001  do io=1,2;if(VB(io).le.verbosity_error)then
        write(errlog(io),*)  'error: cannot open file: ',filename_contourdata
        write(errlog(io),*)  'Program stopped'
      endif;enddo
      stop 1

      end subroutine write_2Dmap_PNG_python

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dprof_PNG_python
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    vprof_ID        = ID of the profile (number in list from Ash3d control file)
!
!  This subroutine creates a png plot of the transient vertical profile of ash
!  concentration above the profile point (vprof_ID) using the python graphics
!  package.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dprof_PNG_python(vprof_ID)

      use global_param,  only : &
         KG_2_MG,KM3_2_M3

      use mesh,          only : &
         IsLatLon,nzmax,z_cc_pd

      use Output_Vars,   only : &
         pr_ash,CLOUDCON_THRESH

      use io_data,       only : &
         Site_vprofile,x_vprofile,y_vprofile,cdf_b3l1,VolcanoName

      use Source,        only : &
         e_Volume,e_Duration,e_StartTime,e_PlumeHeight

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap,ntmax,time_native

      integer, intent (in) :: vprof_ID

!      character(len=14) :: filename_script
!      character(len=14) :: filename_outdata
!      character(len=14) :: dp_pngfile
!      integer           :: fid_script  = 55
!      integer           :: fid_outdata  = 54
!      !integer           :: dp_pngfileID  = 53
!      character(len=27) :: coord_str
!      character(len=25) :: plotcom
!      integer :: k,i
!      integer :: ioerr,iw,iwf
!      character(len=200) :: cmd
!
!      real(kind=ip)  :: tmin
!      real(kind=ip)  :: tmax
!      real(kind=ip)  :: zmin
!      real(kind=ip)  :: zmax
!      real(kind=ip)  :: cloudcon_thresh_mgm3
!      real(kind=ip)  :: cmin
!      real(kind=ip)  :: cmax
!
!      INTERFACE
!        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
!          real(kind=8),intent(in) :: HoursSince
!          integer     ,intent(in) :: byear
!          logical     ,intent(in) :: useLeaps
!        end function HS_xmltime
!      END INTERFACE
!
!      write(filename_outdata,53) vprof_ID,".dat"
!      write(filename_script,53) vprof_ID,".gpi"
!      write(dp_pngfile,54) vprof_ID,".png"
! 53   format('vprof_',i4.4,a4)
! 54   format('gnupl_',i4.4,a4)
!
!      cloudcon_thresh_mgm3 = CLOUDCON_THRESH * KG_2_MG / KM3_2_M3 !convert from kg/km3 to mg/m3
!
!      tmin=real(0.0,kind=ip)
!      tmax=real(ceiling(time_native(ntmax)),kind=ip)
!      zmin=real(0.0,kind=ip)
!      zmax=real(z_cc_pd(nzmax),kind=ip)
!      cmin=real(0.0,kind=ip)
!      cmax=real(maxval(pr_ash(:,:,vprof_ID)),kind=ip)       ! Get the max value for this profile
!      cmax=real(max(cmax,cloudcon_thresh_mgm3),kind=ip)  ! Do not let cmax drop below the threshold
!
!      open(fid_outdata,file=filename_outdata,status='replace')
!      do i = 1,ntmax
!        do k = 1,nzmax
!          write(fid_outdata,*)time_native(i),z_cc_pd(k),pr_ash(k,i,vprof_ID)
!        enddo
!        write(fid_outdata,*)""
!      enddo
!      close(fid_outdata)
!
!      if(IsLatLon)then
!        write(coord_str,101)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
!      else
!        write(coord_str,102)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
!      endif
! 101  format(' (lon=',f7.2,',  lat=',f6.2,')')
! 102  format(' (x=',f9.3,', y=',f9.3,')')
!      ! Set up to plot via python script
!      open(fid_script,file=filename_script,status='replace')
!      write(fid_script,*)"set terminal pngcairo font 'sans,12' size 854,603"   ! Set the image size
!      write(fid_script,*)"set origin 0, .10"
!      write(fid_script,*)"set size 0.85, 0.9"              ! Set x and y scale for plot
!      write(fid_script,*)"set ylabel 'Height (km)'"
!      write(fid_script,*)"set xlabel 'Time (hours after eruption)'"
!      write(fid_script,*)"set output '",dp_pngfile,"'"
!      write(fid_script,*)"set title '",&
!                           trim(adjustl(Site_vprofile(vprof_ID))),&
!                           coord_str,"'"
!      write(fid_script,*)"set isosamples 50"
!      write(fid_script,*)"set pm3d"
!      write(fid_script,*)"set palette cubehelix negative"
!      write(fid_script,*)"unset surface"
!      write(fid_script,*)"set view map"
!      write(fid_script,*)"set key off"
!
!      write(fid_script,*)"XMIN = 0.0"
!      write(fid_script,*)"YMIN = 0.0"
!      write(fid_script,*)"XMAX = ",time_native(ntmax)
!      write(fid_script,*)"YMAX = ",z_cc_pd(nzmax)
!      write(fid_script,*)"XVAL = -XMAX*0.1"
!      write(fid_script,*)"YVAL = -YMAX*0.25"
!      
!      write(fid_script,*)"set label 'Volcano: " ,VolcanoName,&
!                           "' at XVAL, YVAL font 'sans,9'"
!      write(fid_script,*)"set label 'Run Date: ",os_time_log,&
!                  "' at XVAL, YVAL font 'sans,9' offset character 0,-1"
!      read(cdf_b3l1,*,iostat=ioerr) iw,iwf
!      write(fid_script,*)"set label 'Windfile: ",iwf,&
!                "' at XVAL, YVAL font 'sans,9' offset character 0,-2"
!
!      write(fid_script,*)"XVAL = XMAX*0.4"
!      write(fid_script,*)"set label 'Erup. Start Time: ",HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap),&
!                "' at XVAL, YVAL font 'sans,9'"
!      write(fid_script,*)"set label 'Erup. Plume Height: ",real(e_PlumeHeight(1),kind=4),&
!                " km' at XVAL, YVAL font 'sans,9' offset character 0,-1"
!      write(fid_script,*)"set label 'Erup. Duration: ",real(e_Duration(1),kind=4),&
!                " hours' at XVAL, YVAL font 'sans,9' offset character 0,-2"
!      write(fid_script,*)"set label 'Erup. Volume: ",real(e_Volume(1),kind=4),&
!                " km3 (DRE)' at XVAL, YVAL font 'sans,9' offset character 0,-3"
!
!      write(fid_script,*)"set cblabel 'Ash con. in mg/m3'"
!      write(fid_script,*)"splot '",filename_outdata,"'"
!
!      close(fid_script)
!
!      write(plotcom,'(a11,a14)')'python -p ',filename_script
!      call execute_command_line(plotcom)
!
!      ! Clean up
!      if (CleanScripts_python) then
!        cmd = "rm -f outvar.* volc.dat vprof_*dat vprof_*gpi"
!        call execute_command_line(trim(adjustl(cmd)))
!      endif
!
      end subroutine write_2Dprof_PNG_python

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_DepPOI_TS_PNG_python
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    pt_indx       = index of point in Ash3d netcdf output file
!
!  This subroutine creates a png plot of the transient deposit accumulation at
!  the airport/POI given by pt_index using the python graphics package.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_DepPOI_TS_PNG_python(pt_indx)

      use Output_Vars,   only : &
         THICKNESS_THRESH

      use Airports,      only : &
         Airport_Name,Airport_Thickness_TS

      use io_data,       only : &
         nWriteTimes,WriteTimes

      use time_data,     only : &
         Simtime_in_hours

      integer :: pt_indx,i

      real(kind=dp) :: ymaxpl
      character(len=14) :: filename_script
      character(len=14) :: filename_outdata
      character(len=14) :: dp_pngfile
      integer           :: fid_outdata  = 54
      integer           :: fid_script  = 55
      character(len=25) :: plotcom
      integer,save      :: plot_index = 0
      character(len=200) :: cmd

!      if(Airport_Thickness_TS(pt_indx,nWriteTimes).lt.THICKNESS_THRESH)then
!        return
!      else
!        plot_index = plot_index + 1
!      endif
!
!      write(filename_outdata,53) plot_index,".dat"
!      write(filename_script,53) plot_index,".gpi"
!      write(dp_pngfile,54) plot_index,".png"
! 53   format('depTS_',i4.4,a4)
! 54   format('gnupl_',i4.4,a4)
!
!      open(fid_outdata,file=filename_outdata,status='replace')
!      do i = 1,nWriteTimes
!        write(fid_outdata,*)WriteTimes(i),Airport_Thickness_TS(pt_indx,i)
!      enddo
!      close(fid_outdata)
!
!      if(Airport_Thickness_TS(plot_index,nWriteTimes).lt.THICKNESS_THRESH)then
!        ymaxpl = 1.0_dp
!      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.1.0_dp)then
!        ymaxpl = 1.0_dp
!      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.5.0_dp)then
!        ymaxpl = 5.0_dp
!      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.25.0_dp)then
!        ymaxpl = 25.0_dp
!      else
!        ymaxpl = 100.0_dp
!      endif
!
!      ! Set up to plot via python script
!      open(fid_script,file=filename_script,status='replace')
!      write(fid_script,*)"set terminal png size 400,300"
!      write(fid_script,*)"set key bmargin left horizontal Right noreverse enhanced ",&
!               "autotitles box linetype -1 linewidth 1.000"
!      write(fid_script,*)"set border 31 lw 2.0 lc rgb '#000000'"
!      write(fid_script,*)"set style line 1 linecolor rgbcolor '#888888' linewidth 2.0 pt 7"
!      write(fid_script,*)"set ylabel 'Deposit Thickeness (mm)'"
!      write(fid_script,*)"set xlabel 'Time (hours after eruption)'"
!      write(fid_script,*)"set nokey"
!      write(fid_script,*)"set output '",dp_pngfile,"'"
!      write(fid_script,*)"set title '",Airport_Name(pt_indx),"'"
!      write(fid_script,*)"plot [0:",ceiling(Simtime_in_hours),"][0:",&
!               nint(ymaxpl),"] '",filename_outdata,"' with filledcurve x1 ls 1"
!      close(fid_script)
!
!      write(plotcom,'(a11,a14)')'python -p ',filename_script
!      call execute_command_line(plotcom)
!
!      ! Clean up
!      if (CleanScripts_python) then
!        cmd = "rm -f outvar.* cities.xy volc.dat"
!        call execute_command_line(trim(adjustl(cmd)))
!      endif
!
      end subroutine write_DepPOI_TS_PNG_python

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      end module Ash3d_PostProc_python

!##############################################################################
