!##############################################################################
!
! Ash3d_PostProc_matlab module
!
! This module provides the subroutines that use matlab for creating 2d maps,
! 2d vertical profiles, and the little deposit accumulation plots linked to
! the airport arrival kml (ash_arrivaltimes_airports.kml).
! These subroutines create temporary script files that are run if matlab/octave is
! installed on the local system.
!   http://www.mathworks.com
!   http://www.ocatave.org
!
!      subroutine write_2Dmap_PNG_matlab
!      subroutine write_2Dprof_PNG_matlab
!      subroutine write_DepPOI_TS_PNG_matlab
!
!##############################################################################

      module Ash3d_PostProc_matlab

      use precis_param

      use io_units

      use global_param,  only : &
         EPS_SMALL,usematlab,useoctave

      use io_data,       only : &
         Instit_IconFile

      implicit none

        ! Set everything to private by default
      private

        ! Publicly available subroutines/functions
      public write_2Dmap_PNG_matlab,   &
             write_2Dprof_PNG_matlab,  &
             write_DepPOI_TS_PNG_matlab

        ! Publicly available variables
      logical, public :: CleanScripts_matlab
        ! Sometimes, you need to over-ride the default graphics driver used by octave
      logical, public :: SetOctaveGraphics = .true.

      contains
      !------------------------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dmap_PNG_matlab
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    nx            = x length of output array OutVar
!    ny            = y length of output array OutVar
!    iprod         = product ID
!    itime         = time index from netcdf data file
!    OutVar        = 2-d array to be written to ASCII file
!    Fill_Value    = NaN value
!    writeContours = logical
!
!  This subroutine creates a png map of the variable in OutVar using the matlab/octave
!  graphics package.  Annotations and contour levels are indicated via the
!  product ID (iprod).  If writeContours is set to true, then this subroutine
!  is only used for generating and storing the contours (for matlab, this is
!  through output files generated by the script) with no png written. If timestep = -1,
!  then use the last step in file
!  Note: For matlab, the mapping toolbox must be installed
!        For octave, the mapping package must be installed, which requires io,geometry and matgeom
!        These can be installed within octave by running:
!   pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/matgeom-1.2.4.tar.gz"
!   pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/geometry-4.1.0.tar.gz"
!   pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/io-2.7.0.tar.gz"
!   pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/mapping-1.4.3.tar.gz"
!
! http//www.naturalearthdata.com/download/50m/physical/ne_50m_land.zip
!
!  To invoke:
!   ASH3DPLOT=5 ./Ash3d_PostProc 3d_tephra_fall.nc 5 3
!
!   Example script:
!      %##########################################################################
!      %# Temporary matlab script for producing 2d maps for Ash3d_PostProc
!      %# Adjust to suit your needs.
!      %# You will need the mapping toolbox installed as well as the base MatLab.
!      %##########################################################################
!      clear all;
!      land   = readgeotable('landareas.shp');
!      [A,R]=readgeoraster('outvar.dat','CoordinateSystemType','geographic','OutputType','double');
!      latlim = R.LatitudeLimits;
!      lonlim = R.LongitudeLimits;
!
!      figure
!      worldmap(latlim,lonlim);hold on;
!      geoshow(land,'FaceColor',[0.9 0.9 0.9])
!      colormap(jet)
!       levels = [   9.99999978E-03   2.99999993E-02  0.100000001      0.300000012       1.00000000       3.00000000       10.0000000       30.0000000       100.000000     ];
!      colormap lines;
!      [C,h]=contourm(A,R,levels,'-');
!      xlabel('Longitude');
!      ylabel('Latitude');
!      title('Final Deposit Thickness');
!      leg = clegendm(C,h,-1);
!      leg.Title.String = 'Dep.Thick.(mm)';
!      annstr1 = sprintf('Volcano:  Popocatépetl\nRun Date: 2026-01-16T21:49:00Z\nWindfile:    25\n'); % annotation text
!      annpos1 = [0.05 0.025 0.1 0.1]; % annotation position in figure coordinates
!      ha1 = annotation('textbox',annpos1,'string',annstr1);
!      ha1.HorizontalAlignment = 'left';
!      annstr2 = sprintf('Erup. Start Time:   2015-04-04T04:00:00Z\nErup. Plume Height: 12.0 km\nErup. Duration:      6.0 hours\nErup. Volume:        0.03000 km3 (DRE)'); % annotation text
!      annpos2 = [0.65 0.025 0.1 0.1]; % annotation position in figure coordinates
!      ha2 = annotation('textbox',annpos2,'string',annstr2);
!      ha2.HorizontalAlignment = 'left';
!      print -dpng Ash3d_Deposit____final.png
!      exit
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dmap_PNG_matlab(nx,ny,iprod,itime,OutVar,Fill_Value,writeContours)

      use mesh,          only : &
         IsLatLon,de,dn, &
         dx,dy,                              &
         latLL,lonLL,latUR,lonUR,            &
         xLL,yLL,xUR,yUR

      use Output_Vars,   only : &
         !ContourFilled, &
         Con_Cust,Con_Cust_N,Con_Cust_RGB,Con_Cust_Lev,&
         Con_DepThick_mm_N,Con_DepThick_mm_Lev,Con_DepThick_mm_RGB, &
         Con_DepThick_in_N,Con_DepThick_in_Lev,Con_DepThick_in_RGB, &
         Con_DepTime_N,Con_DepTime_Lev,Con_DepTime_RGB, &
         Con_CloudCon_N,Con_CloudCon_Lev,Con_CloudCon_RGB, &
         Con_CloudTop_N,Con_CloudTop_RGB,Con_CloudTop_Lev, &
         Con_CloudBot_N,Con_CloudBot_RGB,Con_CloudBot_Lev, &
         Con_CloudLoad_N,Con_CloudLoad_RGB,Con_CloudLoad_Lev, &
         Con_CloudRef_N,Con_CloudRef_RGB,Con_CloudRef_Lev, &
         Con_CloudTime_N,Con_CloudTime_RGB,Con_CloudTime_Lev, &
         ContourDataX,ContourDataY,ContourDataNcurves,ContourDataNpoints,&
!         CloudArrivalTime,Mask_Deposit,Mask_Cloud,&
         CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS,ContourLev,nConLev

!      use io_units,      only : &
!         fid_script,fid_outdata,fid_contourdata,fid_misc

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap

      use io_data,       only : &
         WriteTimes ,cdf_b3l1 ,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight,lon_volcano

      use citywriter

      use Ash3d_ASCII_IO,  only : &
          write_2D_ASCII,         &
          write_2D_ASCII_flt,     &
          write_2D_ASCII_flt_regular

      integer      ,intent(in) :: nx
      integer      ,intent(in) :: ny
      integer      ,intent(in) :: iprod
      integer      ,intent(in) :: itime
      real(kind=ip),intent(in) :: OutVar(nx,ny)
      real(kind=ip),intent(in) :: Fill_Value
      logical      ,intent(in) :: writeContours

!      logical            :: mask(nx,ny)
      character(len=6)   :: Fill_Value_str
      character(len=200) :: cmd

      !real(kind=ip) :: tmp_ip
      integer,dimension(:,:),allocatable :: zrgb
      character(len=40) :: title_plot
      character(len=15) :: title_legend
      character(len=30) :: cstr_volcname
      character(len=30) :: cstr_run_date
      character(len=30) :: cstr_windfile
      character(len=40) :: cstr_ErStartT
      character(len=27) :: cstr_ErHeight
      character(len=30) :: cstr_ErDuratn
      character(len=38) :: cstr_ErVolume
      character(len=45) :: cstr_note
      character(len=20) :: varname
      character(len= 9) :: cio
      character(len= 4) :: outfile_ext = '.png'
      character(len=10) :: units
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      integer           :: iw,iwf
!      logical           :: IsThere1,IsThere2
      logical           :: HaveIconFile
!      character(len=50) :: linebuffer050
      character(len=80) :: linebuffer080
      character(len=130):: linebuffer130
      character(len=400):: linebuffer400
      !character         :: testkey

      ! Plot dimensions
      real(kind=ip)  :: xmin
      real(kind=ip)  :: xmax
      real(kind=ip)  :: ymin
      real(kind=ip)  :: ymax
      logical        :: IsRegGrid

      ! Aux. File names
      character(len= 8) :: filename_root
      character(len=10) :: filename_script
      character(len=20) :: filename_outdata  ! length of this variable is due to write_2D_ASCII_flt()
      character(len=40) :: filename_png

!      character(len=10) :: filename_contourdata
      !character(len=80) :: filename_coastline

      ! Citywriter variables
!      integer :: icty
      integer :: ncities
!      integer :: cityname_offset_px = 30
      real(kind=ip),dimension(:),allocatable     :: lon_cities
      real(kind=ip),dimension(:),allocatable     :: lat_cities
      character(len=26),dimension(:),allocatable :: name_cities

      ! Contour variables
      !integer           :: ilev,imatlev
      !integer           :: lev_i,substr_pos1,substr_pos2,substr_pos3
      !real(kind=4)      :: lev_r4
      !integer           :: icurve,ipt

      ! MatLab/Octave variables
      character(len=80) :: plotcom

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8 ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dmap_PNG_matlab"
      endif;enddo

      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)

      if(useoctave.and..not.usematlab)then
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)'Map plotting with matlab/octave requires MatLab with the'
          write(errlog(io),*)'mapping toolbox. Currently, the mapping script for octave'
          write(errlog(io),*)'is not functional. Please rerun program specifying a different'
          write(errlog(io),*)'plotting package.'
          write(errlog(io),*)'e.g. ./ASH3DPLOT=4 ./Ash3d_PostProc 3d_tephra_fall.nc 6 3'
        endif;enddo
        stop 1
      endif

      ncities = 20
      allocate(lon_cities(ncities))
      allocate(lat_cities(ncities))
      allocate(name_cities(ncities))

      filename_root        = "outvar"
      filename_outdata     = trim(adjustl(filename_root)) // ".dat"
      filename_script      = trim(adjustl(filename_root)) // ".m"
      !filename_contourdata = trim(adjustl(filename_root)) // ".con"

      if(iprod.eq.5.or.iprod.eq.6)then
        cio='____final'
      else
        if (WriteTimes(itime).lt.10.0_ip) then
          write(cio,1) WriteTimes(itime)
1         format('00',f4.2,'hrs')
        elseif (WriteTimes(itime).lt.100.0_ip) then
          write(cio,2) WriteTimes(itime)
2         format('0',f5.2,'hrs')
        else
          write(cio,3) WriteTimes(itime)
3         format(f6.2,'hrs')
        endif
      endif

      if(Con_Cust)then
        nConLev = Con_Cust_N
        allocate(zrgb(nConLev,3))
        allocate(ContourLev(nConLev))
        ContourLev(1:nConLev) = Con_Cust_Lev(1:nConLev)
        zrgb(1:nConLev,1:3) = Con_Cust_RGB(1:nConLev,1:3)
      endif

      if(iprod.eq.3)then       ! deposit at specified times (mm)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        title_legend = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.4)then   ! deposit at specified times (inches)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        title_legend = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.5)then       ! deposit at final time (mm)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        title_legend = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.6)then   ! deposit at final time (inches)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        title_legend = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.7)then   ! ashfall arrival time (hours)
        varname = "depotime"
        write(filename_png,'(a22)')'DepositArrivalTime.png'
        write(title_plot,'(a20)')'Ashfall arrival time'
        title_legend = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.8)then   ! ashfall arrival at airports/POI (mm)
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for airport arrival time data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_matlab"
        endif;enddo
        stop 1
      elseif(iprod.eq.9)then   ! ash-cloud concentration
        varname = "ashcon_max"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudCon_t',cio,outfile_ext
        write(title_plot,'(a26,f7.2,a6)')'Ash-cloud concentration t=',WriteTimes(itime),' hours'
        title_legend = 'Max.Con.(mg/m3)'
        units = " (mg/m3)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudCon_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudCon_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudCon_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.10)then   ! ash-cloud height
        varname = "cloud_height"
        write(filename_png,'(a19,a9,a4)')'Ash3d_CloudHeight_t',cio,outfile_ext
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud height t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Height(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTop_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTop_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTop_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.11)then   ! ash-cloud bottom
        varname = "cloud_bottom"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudBot_t',cio,outfile_ext
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud bottom t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Bot.(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudBot_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudBot_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudBot_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.12)then   ! ash-cloud load
        varname = "cloud_load"
        write(filename_png,'(a17,a9,a4)')'Ash3d_CloudLoad_t',cio,outfile_ext
        write(title_plot,'(a17,f7.2,a6)')'Ash-cloud load t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Load(T/km2)'
        units = " (T/km2)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudLoad_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudLoad_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudLoad_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.13)then  ! radar reflectivity
        varname = "radar_reflectivity"
        write(filename_png,'(a20,a9,a4)')'Ash3d_CloudRadRefl_t',cio,outfile_ext
        write(title_plot,'(a24,f7.2,a6)')'Ash-cloud radar refl. t=',WriteTimes(itime),' hours'
        title_legend = 'Cld.Refl.(dBz)'
        units = " (dBz)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudRef_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudRef_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudRef_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.14)then   ! ashcloud arrival time (hours)
        varname = "ash_arrival_time"
        write(filename_png,'(a20)')'CloudArrivalTime.png'
        write(title_plot,'(a22)')'Ash-cloud arrival time'
        title_legend = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod.eq.15)then   ! topography
        varname = "topography"
        write(filename_png,'(a14)')'Topography.png'
        write(title_plot,'(a10)')'Topography'
        title_legend = 'Elevation (km)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = 8
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev = (/1.0_ip, 2.0_ip, 3.0_ip, 4.0_ip, &
                  5.0_ip, 6.0_ip, 7.0_ip, 8.0_ip/)
        endif
      elseif(iprod.eq.16)then   ! profile plots
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for vertical profile data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_matlab"
        endif;enddo
        stop 1
      else
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"ERROR: unexpected variable"
          write(errlog(io),*)"         iprod = ",iprod
          write(errlog(io),*)"       Cannot map this variable."
        endif;enddo
        stop 1
      endif
      ! Now have string vars (varname,title_legend, etc.) and contour info (nConLev,zrgb,ContourLev)

      if(writeContours)then
        do io=1,2;if(VB(io).le.verbosity_error)then
          write(errlog(io),*)"Running matlab to calculate contours lines"
          write(errlog(io),*)"Not sure yet how to save contour data with matlab"
          write(errlog(io),*)"If you want shapefiles, recompile without matlab or"
          write(errlog(io),*)" reset the plot_pref_shp variable."
          write(errlog(io),*)"Exiting"
        endif;enddo
        stop 1
      else
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Running matlab to generate contour plot"
        endif;enddo
      endif

      ! This is the section where we actually start plotting the map
      ! Evaluate grid
      if(IsLatLon)then
        xmin = lonLL
        ! Make sure xmin is in the range -180->180
        if (xmin.gt.180.0_ip)then
          xmin = lonLL-360.0_ip
          xmax = lonUR-360.0_ip
        else
          xmax = lonUR
        endif
        ymin = latLL
        ymax = latUR
        if(abs(dn-de).lt.1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
      else
        xmin = xLL
        xmax = xUR
        ymin = yLL
        ymax = yUR
        if(abs(dx-dy).lt.1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
        !do io=1,2;if(VB(io).le.verbosity_error)then
        !  write(errlog(io),*)"ERROR: Currenntly, plotting with matlab only enabled for lon/lat grids."
        !  write(errlog(io),*)"       Please use GMT to plot projected maps."
        !  write(errlog(io),*)"       ./ASH3DPLOT=4 ./Ash3d_PostProc ...."
        !endif;enddo
        !stop 1
      endif

      ! write out the data in a form that matlab can read
      ! matlab script expects an ESRI ASCII data file; force regular
      if(IsRegGrid)then
        ! If the grid is regular (dx=dy) then we can write an ESRI ASCII file and convert to grd
        varname = "outvar"
        call write_2D_ASCII_flt(nx,ny,IsLatLon,real(xmin,kind=sp),real(ymin,kind=sp),.true., &
                           real(de,kind=sp),real(dn,kind=sp),Fill_Value_str,&
                           real(OutVar,kind=sp),filename_outdata)
      else
        ! MatLab expects GeoTIFF, Esri Binary Grid, GRIB, or DTED
        ! Irregular grids are problematic, call special ASCII interpolator
        call write_2D_ASCII_flt_regular(nx,ny,IsLatLon,real(xmin,kind=sp),real(ymin,kind=sp),.true., &
                           real(de,kind=sp),real(dn,kind=sp),Fill_Value_str,&
                           real(OutVar,kind=sp),filename_outdata)
      endif
      ! Finished temporary data file

      call citylist(2,                        & ! 2 is for external file in gnuplot format
                    xmin,xmax,ymin,ymax,      &
                    ncities,                  &
                    lon_cities,               &
                    lat_cities,               &
                    name_cities)
      if(lon_volcano.gt.xmax)lon_volcano=lon_volcano-360.0_ip

      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions.gt.1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      else
        write(cstr_note,'(a1)')" "
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'

      if(writeContours)then
        write(filename_png,'(a14)')'tmp.png'
        allocate(ContourDataNcurves(nConLev))
        allocate(ContourDataNpoints(nConLev,CONTOUR_MAXCURVES))
        allocate(ContourDataX(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        allocate(ContourDataY(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        ContourDataNcurves(:)   = 0
        ContourDataNpoints(:,:) = 0
        ContourDataX(:,:,:)     = 0.0_ip
        ContourDataY(:,:,:)     = 0.0_ip
      endif

      ! Set up to plot via matlab script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"%##########################################################################"
      write(fid_script,'(g0)')"%# Temporary matlab script for producing 2d maps for Ash3d_PostProc"
      write(fid_script,'(g0)')"%# Adjust to suit your needs."
      write(fid_script,'(g0)')"%# You will need the mapping toolbox installed as well as the base MatLab."
      write(fid_script,'(g0)')"%##########################################################################"
      write(fid_script,'(g0)')"clear all;"
      write(fid_script,'(g0)')"land   = readgeotable('landareas.shp');"
      write(fid_script,'(g0)')"[A,R]=readgeoraster('outvar.dat','CoordinateSystemType','geographic','OutputType','double');"
      write(fid_script,'(g0)')"latlim = R.LatitudeLimits;"
      write(fid_script,'(g0)')"lonlim = R.LongitudeLimits;"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"figure"
      write(fid_script,'(g0)')"worldmap(latlim,lonlim);hold on;"
      write(fid_script,'(g0)')"geoshow(land,'FaceColor',[0.9 0.9 0.9])"
      write(fid_script,'(g0)')"colormap(jet)"
      !write(fid_script,'(a10,f15.5,a2)')"levels = [",real(ContourLev(1:nConLev-1),kind=4),"];"
      write(fid_script,*)"levels = [",real(ContourLev(1:nConLev-1),kind=4),"];"
      write(fid_script,'(g0)')"colormap lines;"
      write(fid_script,'(g0)')"[C,h]=contourm(A,R,levels,'-');"
      write(fid_script,'(g0)')"xlabel('Longitude');"
      write(fid_script,'(g0)')"ylabel('Latitude');"
      linebuffer080 = "title('" // adjustl(trim(title_plot)) // "');"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')"leg = clegendm(C,h,-1);"
      linebuffer080 = "leg.Title.String = '" // adjustl(trim(title_legend)) // "';"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      ! Annotation box 1
      cmd = trim(adjustl(cstr_volcname)) // '\n' // &
            trim(adjustl(cstr_run_date)) // '\n' // &
            trim(adjustl(cstr_windfile)) // '\n' // &
            trim(adjustl(cstr_note))
      linebuffer130 = "annstr1 = sprintf('" // trim(adjustl(cmd)) // "'); % annotation text"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      write(fid_script,'(g0)')"annpos1 = [0.05 0.025 0.1 0.1]; % annotation position in figure coordinates"
      write(fid_script,'(g0)')"ha1 = annotation('textbox',annpos1,'string',annstr1);"
      write(fid_script,'(g0)')"ha1.HorizontalAlignment = 'left';"
      ! Annotation box 2
      cmd = trim(adjustl(cstr_ErStartT)) // '\n' // &
            trim(adjustl(cstr_ErHeight)) // '\n' // &
            trim(adjustl(cstr_ErDuratn)) // '\n' // &
            trim(adjustl(cstr_ErVolume))
      linebuffer400 = "annstr2 = sprintf('" // trim(adjustl(cmd)) // "'); % annotation text"
      write(fid_script,'(g0)')trim(adjustl(linebuffer400))
      write(fid_script,'(g0)')"annpos2 = [0.65 0.025 0.1 0.1]; % annotation position in figure coordinates"
      write(fid_script,'(g0)')"ha2 = annotation('textbox',annpos2,'string',annstr2);"
      write(fid_script,'(g0)')"ha2.HorizontalAlignment = 'left';"
      linebuffer130 = "print -dpng " // adjustl(trim(filename_png))
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))
      write(fid_script,'(g0)')"exit"

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !
      !    Set up MatLab annotation boxes
      !
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      close(fid_script)

      ! syscall = matlab -nodisplay -nosplash -r tmp
      write(plotcom,'(a37)')'matlab -nodisplay -nosplash -r outvar'
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      ! Clean up
      if (CleanScripts_matlab) then
        cmd = "rm -f outvar.dat outvar.m cities.xy volc.dat"
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      ! clean up memory
      if(allocated(lon_cities))         deallocate(lon_cities)
      if(allocated(lat_cities))         deallocate(lat_cities)
      if(allocated(name_cities))        deallocate(name_cities)
      if(allocated(zrgb))               deallocate(zrgb)

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dmap_PNG_matlab"
      endif;enddo

      return

      end subroutine write_2Dmap_PNG_matlab

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dprof_PNG_matlab
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    vprof_ID        = ID of the profile (number in list from Ash3d control file)
!
!  This subroutine creates a png plot of the transient vertical profile of ash
!  concentration above the profile point (vprof_ID) using the matlab or octave graphics
!  package.
!
!  To invoke:
!   ASH3DPLOT=5 ./Ash3d_PostProc 3d_tephra_fall.nc 16 3
!
!   Example script:
!      %##########################################################################
!      %# Temporary matlab/octave script for producing vertical profiles for Ash3d_PostProc
!      %# Adjust to suit your needs.
!      %##########################################################################
!      clear all;
!      graphics_toolkit('gnuplot')
!      titstr='Cuernavaca (lon= -99.26, lat= 18.83)';
!      xstr='Time (hours after eruption)';
!      ystr='Height (km)';
!      zstr='Ash conc. mg/m3';
!      vp=load('vprof_0001.dat');
!      ns=max(size(vp));
!      % Time will be irregular, so we need to regrid the data.
!      t_reg = linspace(0, vp(ns,1), 101);
!      z_reg = linspace(0, vp(ns,2), 101);
!      [T_reg, Z_reg] = meshgrid(t_reg, z_reg);
!
!      % Interpolate the data onto the regular grid
!      C_reg = griddata(vp(:,1), vp(:,2), vp(:,3), T_reg, Z_reg);
!      Cmask=C_reg(:,:)<0.001;
!      C_reg(Cmask)=NaN;
!
!      colormap jet
!      contourf(T_reg, Z_reg, C_reg);
!      xlabel(xstr,'FontSize',16);
!      ylabel(ystr,'FontSize',16);
!      title(titstr,'FontSize',12);
!      print -dpng vprof_0001.png
!      exit
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dprof_PNG_matlab(vprof_ID)

      use global_param,  only : &
         KG_2_MG,KM3_2_M3

      use mesh,          only : &
         IsLatLon,nzmax,z_cc_pd

      use Output_Vars,   only : &
         pr_ash,CLOUDCON_THRESH

      use io_data,       only : &
         Site_vprofile,x_vprofile,y_vprofile,cdf_b3l1,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap,ntmax,time_native

      integer,intent (in) :: vprof_ID

      logical           :: HaveIconFile
      character(len=76) :: title_plot
      character(len=30) :: cstr_xlabel = 'Time (hours after eruption)'
      character(len=30) :: cstr_ylabel = 'Height (km)'
      character(len=30) :: cstr_zlabel = 'Ash conc. mg/m3'
      character(len=30) :: cstr_volcname
      character(len=30) :: cstr_run_date
      character(len=30) :: cstr_windfile
      character(len=40) :: cstr_ErStartT
      character(len=27) :: cstr_ErHeight
      character(len=30) :: cstr_ErDuratn
      character(len=38) :: cstr_ErVolume
      character(len=45) :: cstr_note

      character(len=10) :: filename_root
      character(len=12) :: filename_script
      character(len=14) :: filename_outdata
      character(len=14) :: filename_png
      integer           :: fid_script   = 55
      integer           :: fid_outdata  = 54
      character(len=27) :: coord_str
      character(len=80) :: plotcom
      integer           :: i,k
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      integer           :: iw,iwf
      character(len= 80):: linebuffer080
      character(len=200):: cmd

      ! Plotting variables

      real(kind=ip) :: tmin    , zmin    , cmin     ! graph minima
      real(kind=ip) :: tmax    , zmax    , cmax     ! graph maxima
      real(kind=ip) :: tlab1   , zlab1   , clab1    ! graph first label
      real(kind=ip) :: tlabstep, zlabstep, clabstep ! graph label increment
      real(kind=ip) :: cloudcon_thresh_mgm3

      ! Matlab/Octave variables

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8 ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dprof_PNG_matlab"
      endif;enddo

      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)

      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions.gt.1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      else
        write(cstr_note,'(a1)')" "
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'

      write(filename_root,52)vprof_ID
 52   format('vprof_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".m"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      ! Get min/max and label interval for all three axies.
      tmin=real(0,kind=ip)
      tmax=real(ceiling(time_native(ntmax)),kind=ip)
      tlab1    = 0.0_ip
      if(tmax.gt.240.0_ip)then
        tlabstep = 48.0_ip
      elseif(tmax.gt.120.0_ip)then
        tlabstep = 24.0_ip
      elseif(tmax.gt.30.0_ip)then
        tlabstep = 10.0_ip
      elseif(tmax.gt.15.0_ip)then
        tlabstep = 5.0_ip
      elseif(tmax.gt.6.0_ip)then
        tlabstep = 2.0_ip
      else
        tlabstep = 1.0_ip
      endif

      zmin=real(0,kind=ip)
      zmax=real(z_cc_pd(nzmax),kind=ip)
      zlab1    = 0.0_ip
      if(zmax.gt.30.0_ip)then
        zlabstep = 10.0_ip
      elseif(zmax.gt.15.0_ip)then
        zlabstep = 5.0_ip
      elseif(zmax.gt.6.0_ip)then
        zlabstep = 2.0_ip
      else
        zlabstep = 1.0_ip
      endif

      cloudcon_thresh_mgm3 = CLOUDCON_THRESH * KG_2_MG / KM3_2_M3 !convert from kg/km3 to mg/m3
      cmin=real(0,kind=ip)
      cmax=real(maxval(pr_ash(:,:,vprof_ID)),kind=ip)    ! Get the max value for this profile
      cmin=real(min(cmin,cloudcon_thresh_mgm3),kind=ip)  ! Do not let cmax drop below the threshold
      if    (cmax.gt.4.0e4_ip)then
          clabstep = 5.0e3_ip
      elseif(cmax.gt.1.0e4_ip)then
          clabstep = 2.0e3_ip
      elseif(cmax.gt.4.0e3_ip)then
          clabstep = 5.0e2_ip
      elseif(cmax.gt.1.0e3_ip)then
          clabstep = 2.0e2_ip
      elseif(cmax.gt.4.0e2_ip)then
          clabstep = 5.0e1_ip
      elseif(cmax.gt.1.0e2_ip)then
          clabstep = 2.0e1_ip
      elseif(cmax.gt.4.0e1_ip)then
          clabstep = 5.0e0_ip
      elseif(cmax.gt.1.0e1_ip)then
          clabstep = 2.0e0_ip
      elseif(cmax.gt.1.0e0_ip)then
          clabstep = 5.0e-1_ip
      else
          clabstep = 1.0e-1_ip
      endif
      clab1    = 0.0_ip

      ! Prep data: matlab/octave will load x y z data in column format
      open(unit=fid_outdata,file=filename_outdata,status='replace')
      do i = 1,ntmax
        do k = 1,nzmax
          write(fid_outdata,*)time_native(i),z_cc_pd(k),pr_ash(k,i,vprof_ID)
        enddo
      enddo
      close(fid_outdata)

      ! Build the plot title
      if(IsLatLon)then
        write(coord_str,101)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      else
        write(coord_str,102)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      endif
 101  format(' (lon=',f7.2,', lat=',f6.2,')')
 102  format(' (x=',f9.3,', y=',f9.3,')')
      title_plot = trim(adjustl(Site_vprofile(vprof_ID))) // coord_str
      !write(title_plot,*)trim(adjustl(Site_vprofile(vprof_ID))),coord_str

      ! Set up to plot via matlab script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"%##########################################################################"
      write(fid_script,'(g0)')"%# Temporary matlab/octave script for producing vertical profiles for Ash3d_PostProc"
      write(fid_script,'(g0)')"%# Adjust to suit your needs."
      write(fid_script,'(g0)')"%##########################################################################"
      write(fid_script,'(g0)')"clear all;"
      if(SetOctaveGraphics)then
        write(fid_script,'(g0)')"graphics_toolkit('gnuplot')"
      else
        write(fid_script,'(g0)')"%graphics_toolkit('gnuplot')"
      endif
      !cmd = "titstr='" // trim(adjustl(Site_vprofile(vprof_ID))) // coord_str // "';"
      cmd = "titstr='" // trim(adjustl(title_plot)) // "';"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "xstr='" // trim(adjustl(cstr_xlabel)) // "';"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "ystr='" // trim(adjustl(cstr_ylabel)) // "';"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "zstr='" // trim(adjustl(cstr_zlabel)) // "';"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "vp=load('" // trim(adjustl(filename_outdata)) // "');"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      write(fid_script,'(g0)')"ns=max(size(vp));"
      write(fid_script,'(g0)')"% Time will be irregular, so we need to regrid the data."
      write(fid_script,'(g0)')"t_reg = linspace(0, vp(ns,1), 101);"
      write(fid_script,'(g0)')"z_reg = linspace(0, vp(ns,2), 101);"
      write(fid_script,'(g0)')"[T_reg, Z_reg] = meshgrid(t_reg, z_reg);"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"% Interpolate the data onto the regular grid"
      write(fid_script,'(g0)')"C_reg = griddata(vp(:,1), vp(:,2), vp(:,3), T_reg, Z_reg);"
      write(fid_script,'(g0)')"Cmask=C_reg(:,:)<0.001;"
      write(fid_script,'(g0)')"C_reg(Cmask)=NaN;"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"colormap jet"
      write(fid_script,'(g0)')"contourf(T_reg, Z_reg, C_reg);"
      write(fid_script,'(g0)')"xlabel(xstr,'FontSize',16);"
      write(fid_script,'(g0)')"ylabel(ystr,'FontSize',16);"
      write(fid_script,'(g0)')"title(titstr,'FontSize',12);"

!      ! Annotation box 1
!      cmd = trim(adjustl(cstr_volcname)) // '\n' // &
!            trim(adjustl(cstr_run_date)) // '\n' // &
!            trim(adjustl(cstr_windfile)) // '\n' // &
!            trim(adjustl(cstr_note))
!      write(fid_script,*)"annstr1 = sprintf('",trim(adjustl(cmd)),"'); % annotation text"
!      write(fid_script,*)"annpos1 = [0.1 0.075 0.1 0.1]; % annotation position in figure coordinates"
!      write(fid_script,*)"ha1 = annotation('textbox',annpos1,'string',annstr1);"
!      write(fid_script,*)"ha1.HorizontalAlignment = 'left';"
!      ! Annotation box 2
!      cmd = trim(adjustl(cstr_ErStartT)) // '\n' // &
!            trim(adjustl(cstr_ErHeight)) // '\n' // &
!            trim(adjustl(cstr_ErDuratn)) // '\n' // &
!            trim(adjustl(cstr_ErVolume))
!      write(fid_script,*)"annstr2 = sprintf('",trim(adjustl(cmd)),"'); % annotation text"
!      write(fid_script,*)"annpos2 = [0.4 0.075 0.1 0.1]; % annotation position in figure coordinates"
!      write(fid_script,*)"ha2 = annotation('textbox',annpos2,'string',annstr2);"
!      write(fid_script,*)"ha2.HorizontalAlignment = 'left';"
!
!      write(fid_script,'(g0)')"cb = colorbar();"
!      write(fid_script,'(g0)')"ylabel(cb,zstr,'FontSize',16,'Rotation',90)"

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !
      !    Set up MatLab annotation boxes
      !
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      linebuffer080 = "print -dpng " // adjustl(trim(filename_png))
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')"exit"

      if(useoctave.and..not.usematlab)then
        ! This is the case where we prefer octave over matlab
        write(plotcom,'(a11,a14)')'octave ',filename_script
      elseif(usematlab.and.useoctave.and..not.SetOctaveGraphics)then
        ! This is the case where both are installed, but we prefer matlab
        write(plotcom,'(a31,a12)')'matlab -nodisplay -nosplash -r ',filename_root
      else
        ! This is the case where we prefer octave over matlab, but need extra graphics directives
        write(plotcom,'(a11,a14)')'octave ',filename_script
      endif
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      ! Clean up
      if (CleanScripts_matlab) then
        cmd = "rm -f vprof_*.m vprof_*.dat"
        do io=1,2;if(VB(io).le.verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dprof_PNG_matlab"
      endif;enddo

      return
      end subroutine write_2Dprof_PNG_matlab

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_DepPOI_TS_PNG_matlab
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    pt_indx       = index of point in Ash3d netcdf output file
!
!  This subroutine creates a png plot of the transient deposit accumulation at
!  the airport/POI given by pt_index using the matlab graphics package.
!
!  To invoke:
!   ASH3DPLOT=5 ./Ash3d_PostProc 3d_tephra_fall.nc 8 2
!
!   Example script:
!      %##########################################################################
!      %# Temporary matlab/octave script for producing deposit time-series plots for Ash3d_PostProc
!      %# Adjust to suit your needs.
!      %##########################################################################
!      clear all;
!      graphics_toolkit('gnuplot')
!      titstr='Cuernavaca, Mexico';
!      dp=load('depTS_0001.dat');
!      ns=max(size(dp));
!      x=dp(:,1);
!      y=dp(:,2);
!      area (x, y, "FaceColor", [0.5, 0.5, 0.5]);
!      axis([0.0,  25,0.0,   1])
!      xlabel('Time (hours after eruption)','FontSize',16);
!      ylabel('Deposit Thickness (mm)','FontSize',16);
!      title(titstr,'FontSize',12);
!      print -dpng 'depTS_0001.png'
!      exit
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_DepPOI_TS_PNG_matlab(pt_indx)

      use Output_Vars,   only : &
         THICKNESS_THRESH

      use Airports,      only : &
         Airport_Name,Airport_Thickness_TS

      use io_data,       only : &
         nWriteTimes,WriteTimes

      use time_data,     only : &
         Simtime_in_hours

      integer,intent(in) :: pt_indx

      real(kind=dp) :: ymaxpl
!      character(len=40) :: title_plot
      character(len=10) :: filename_root
      character(len=14) :: filename_script
      character(len=14) :: filename_outdata
      character(len=14) :: filename_png
      integer           :: fid_outdata  = 54
      integer           :: fid_script  = 55
      integer           :: i
      character(len=25) :: plotcom
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      character(len=200):: cmd
      character(len=080):: linebuffer080

      integer,save      :: plot_index = 0

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_DepPOI_TS_PNG_matlab"
      endif;enddo

      if(Airport_Thickness_TS(pt_indx,nWriteTimes).lt.THICKNESS_THRESH)then
        return
      else
        plot_index = plot_index + 1
      endif

      write(filename_root,52)plot_index
 52   format('depTS_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".m"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      open(unit=fid_outdata,file=filename_outdata,status='replace')
      do i = 1,nWriteTimes
        write(fid_outdata,*)WriteTimes(i),Airport_Thickness_TS(pt_indx,i)
      enddo
      close(fid_outdata)

      if(Airport_Thickness_TS(plot_index,nWriteTimes).lt.THICKNESS_THRESH)then
        ymaxpl = 1.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.1.0_dp)then
        ymaxpl = 1.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.5.0_dp)then
        ymaxpl = 5.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes).lt.25.0_dp)then
        ymaxpl = 25.0_dp
      else
        ymaxpl = 100.0_dp
      endif

      ! Set up to plot via matlab script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"%##########################################################################"
      write(fid_script,'(g0)')"%# Temporary matlab/octave script for producing deposit time-series plots for Ash3d_PostProc"
      write(fid_script,'(g0)')"%# Adjust to suit your needs."
      write(fid_script,'(g0)')"%##########################################################################"
      write(fid_script,'(g0)')"clear all;"
      if(SetOctaveGraphics)then
        write(fid_script,'(g0)')"graphics_toolkit('gnuplot')"
      else
        write(fid_script,'(g0)')"%graphics_toolkit('gnuplot')"
      endif
      !cmd = "titstr='" // trim(adjustl(Site_vprofile(vprof_ID))) // coord_str // "';"
      cmd = "titstr='" // trim(adjustl(Airport_Name(pt_indx))) // "';"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "dp=load('" // trim(adjustl(filename_outdata)) // "');"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      write(fid_script,'(g0)')"ns=max(size(dp));"
      write(fid_script,'(g0)')"x=dp(:,1);"
      write(fid_script,'(g0)')"y=dp(:,2);"
      write(fid_script,'(g0)')'area (x, y, "FaceColor", [0.5, 0.5, 0.5]);'
      write(fid_script,'(a11,i3,a6,i3,a2)')'axis([0.0, ',ceiling(Simtime_in_hours), ',0.0, ',nint(ymaxpl),'])'
      write(fid_script,'(g0)')"xlabel('Time (hours after eruption)','FontSize',16);"
      write(fid_script,'(g0)')"ylabel('Deposit Thickness (mm)','FontSize',16);"
      write(fid_script,'(g0)')"title(titstr,'FontSize',12);"
      linebuffer080 = "print -dpng '" // filename_png // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')"exit"

      close(fid_script)

      if(useoctave.and..not.usematlab)then
        ! This is the case where we prefer octave over matlab
        write(plotcom,'(a11,a14)')'octave ',filename_script
      elseif(usematlab.and.useoctave.and..not.SetOctaveGraphics)then
        ! This is the case where both are installed, but we prefer matlab
        write(plotcom,'(a31,a12)')'matlab -nodisplay -nosplash -r ',filename_root
      else
        ! This is the case where we prefer octave over matlab, but need extra graphics directives
        write(plotcom,'(a11,a14)')'octave ',filename_script
      endif

      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      ! Clean up
      if (CleanScripts_matlab) then
        cmd = "rm -f depTS_*.dat depTS_*.m"
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io).le.verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_DepPOI_TS_PNG_matlab"
      endif;enddo

      return
      end subroutine write_DepPOI_TS_PNG_matlab

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      end module Ash3d_PostProc_matlab

!##############################################################################
