!##############################################################################
!
! Ash3d_PostProc_python module
!
! This module provides the subroutines that use python for creating 2d maps,
! 2d vertical profiles, and the little deposit accumulation plots linked to
! the airport arrival kml (ash_arrivaltimes_airports.kml).
! These subroutines create temporary script files that are run if python/matplotlib/cartopy are
! installed on the local system.
!
!      subroutine write_2Dmap_PNG_python
!      subroutine write_2Dprof_PNG_python
!      subroutine write_DepPOI_TS_PNG_python
!
! Python mapping expects matplotlib and cartopy for geographic mapping.
! Additinoally, gdal and geopandas are needed for loading ASCII files
! and handling geospatial data. We recommend using Anaconda:
!
! (1) Download anaconda:
!   curl -O https://repo.anaconda.com/archive/Anaconda3-2025.06-0-Linux-x86_64.sh
!
! (2) Install:
!   bash ~/Anaconda3-2025.06-0-Linux-x86_64.sh
!  Accept terms of service.
!  Accept default install location: ~/anaconda3
!  Choose 'no' when asked about editing start-up scripts.
!
! (3) Initialize anaconda manually.
!   export PATH="$HOME/anaconda3/bin:$PATH"
!   conda init
!
! (4) Install the packages your script needs:
!   conda install -c conda-forge scipy
!   conda install -c conda-forge geopandas
!   conda install -c scitools cartopy
!   conda install -c conda-forge gdal
!
! conda create --name geo_env
! conda activate geo_env
!
! If you have SSL errors, you might need to fix them, or run:
!  conda config --set ssl_verify false
!
!##############################################################################

      module Ash3d_PostProc_python

      use precis_param

      use io_units

      use global_param,  only : &
         EPS_SMALL

      use io_data,       only : &
         Instit_IconFile

      implicit none
      !implicit none (type, external)

        ! Set everything to private by default
      private

        ! Publicly available subroutines/functions
      public write_2Dmap_PNG_python,   &
             write_2Dprof_PNG_python,  &
             write_DepPOI_TS_PNG_python

        ! Publicly available variables
      logical, public :: CleanScripts_python

      contains
      !------------------------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dmap_PNG_python
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    nx            = x length of output array OutVar
!    ny            = y length of output array OutVar
!    iprod         = product ID
!    itime         = time index from netcdf data file
!    OutVar        = 2-d array to be written to ASCII file
!    Fill_Value    = NaN value
!    writeContours = logical
!
!  This subroutine creates a png map of the variable in OutVar using the python
!  graphics package.  Annotations and contour levels are indicated via the
!  product ID (iprod).  If writeContours is set to true, then this subroutine
!  is only used for generating and storing the contours (for python, this is
!  through output files generated by the script) with no png written. If timestep = -1,
!  then use the last step in file
!
!  To invoke:
!   ASH3DPLOT=6 ./Ash3d_PostProc 3d_tephra_fall.nc 5 3
!
!   Example script:
!     ##########################################################################
!     # Temporary python/cartopy script for producing 2d maps for Ash3d_PostProc
!     # Adjust to suit your needs.
!     # This script draws heavily from scripts created by Tyler Paladino.
!     # You will need the packages conda-forge, geopandas, scitools, cartopy, gdal
!     ##########################################################################
!     import cartopy.feature as cfeature
!     import cartopy.crs as ccrs
!     import matplotlib.pyplot as plt
!     from mpl_toolkits.axes_grid1.inset_locator import inset_axes
!     import matplotlib.image as mpimg
!     from matplotlib.colors import LinearSegmentedColormap
!     from matplotlib.offsetbox import OffsetImage, AnnotationBbox, TextArea
!     import numpy as np
!     import scipy.ndimage
!     from osgeo import gdal, osr
!     import linecache
!
!     def get_extent(gdal_ds, A3D_input_fn):
!         Xsize = gdal_ds.RasterXSize
!         Ysize = gdal_ds.RasterYSize
!         cellsize = gdal_ds.GetGeoTransform()[1]
!         xcorner, ycorner = get_proj_info(A3D_input_fn)
!         minx = xcorner+cellsize
!         miny = ycorner+cellsize
!         maxx = minx + (cellsize*Xsize)
!         maxy = miny + (cellsize*Ysize)
!         return [minx, maxx, miny, maxy]
!
!     def get_proj_info(fn):
!         xl_corner = linecache.getline(fn, 3)
!         yl_corner = linecache.getline(fn, 4)
!         return float(xl_corner.split()[1]), float(yl_corner.split()[1])
!
!     def draw_logo(ax,fn):
!         # Create background box
!         ax_inset = inset_axes(
!             ax,
!             width="18%",
!             height="7%",
!             borderpad=.5,
!             loc="upper right"
!         )
!
!         img = mpimg.imread(fn)
!
!         # ax.patch.set_alpha(0.5)
!         # Remove axis borders
!         # ax_inset.set_axis_off()
!         ax_inset.set_xticks([])
!         ax_inset.set_yticks([])
!         ax_inset.set_facecolor([1,1,1,0.8])
!
!         ax_logo = inset_axes(
!             ax_inset,
!             width="90%",
!             height="90%",
!             loc="center"
!         )
!
!         ax_logo.imshow(img)
!         ax_logo.set_axis_off()
!
!         return None
!
!     # Institutional logo (Defaults to USGS)
!     logo_file = '/opt/USGS/Ash3d/share/post_proc/logo.png'
!
!     # Run values
!     srcx=   -98.622
!     srcy=    19.023
!
!     #######################################
!     # Product values
!     grid_file="outvar.dat"
!     title_plot="Final Deposit Thickness"
!     title_legend="Dep.Thick.(mm)"
!     clevels=[.100E-01,.300E-01,.100E+00,.300E+00,.100E+01,.300E+01,.100E+02,.300E+02,.100E+03,.300E+03]
!     ccolors=[(  0.84, 0.87, 0.41),
!              (  0.98, 0.65, 0.44),
!              (  0.50, 0.00, 0.50),
!              (  0.00, 0.00, 1.00),
!              (  0.00, 0.50, 1.00),
!              (  0.00, 1.00, 0.50),
!              (  0.76, 0.76, 0.00),
!              (  1.00, 0.50, 0.00),
!              (  1.00, 0.00, 0.00),
!              (  0.50, 0.00, 0.00)]
!     tlevels=['.100E-01','.300E-01','.100E+00','.300E+00','.100E+01','.300E+01','.100E+02','.300E+02','.100E+03','.300E+03']
!
!     #######################################
!     txt_vname="Volcano:  Popocatépetl"
!     txt_RunDate="Run Date: 2026-01-16T21:49:00Z"
!     txt_Windfile="Windfile:    25"
!     txt_ESrtTime="Erup. Start Time:   2015-04-04T04:00:00Z"
!     txt_EPlmH="Erup. Plume Height: 12.0 km"
!     txt_EDur="Erup. Duration:      6.0 hours"
!     txt_EVol="Erup. Volume:        0.03000 km3 (DRE)"
!
!     annotation_text1 = txt_vname    + "\n" + \
!     txt_RunDate  + "\n" + \
!     txt_Windfile
!     annotation_text2 = txt_ESrtTime + "\n" + \
!     txt_EPlmH    + "\n" + \
!     txt_EDur     + "\n" + \
!     txt_EVol
!
!     ###################### OPEN ASH DATA FILE AND GET GEOTRANSFORM #######################
!     # Open raster with GDAL
!     raster = gdal.Open(grid_file)
!     # Get lat/lon extent of raster
!     extent = get_extent(raster, grid_file)
!
!     ############################# PLOT ######################################
!     # Create figure
!     main_fig = plt.figure(figsize=(8.5, 6))
!     # Create geospatial matplotlib axes with CartoPy.
!     # Use a PlateCarree projection for now
!     cen_lon=0.5*(sum(extent))
!     img_extent = extent
!     # Hard-code map limits here, if needed
!     #img_extent =  [-165.0, -162.0, 53.0, 56.0]
!     projection = ccrs.PlateCarree(central_longitude=cen_lon)
!     # this is the Cartopy bit
!     map_ax = main_fig.add_subplot(4,1,(1,3),projection=projection)
!     # create the matplotlib mapping with this projection
!     map_ax.set_extent(img_extent)
!
!     # Add coastlines and water
!     map_ax.add_feature(cfeature.LAND, facecolor='lightgrey')
!     map_ax.coastlines()
!
!     # Add gridlines
!     gl = map_ax.gridlines(draw_labels=True,
!                           x_inline=False,
!                           y_inline=False,
!                           color='black',
!                           alpha=0.5,
!                           linestyle='--')
!     # Get rid of top and right side labels
!     gl.top_labels = False
!     gl.right_labels = False
!     # Get grided data from GDAL dataset
!     data = raster.GetRasterBand(1).ReadAsArray()
!     data = scipy.ndimage.zoom(data, 1.00)
!     # Mask out any values that are = to fill_value
!     Fill_Value=0
!     data_masked = np.ma.masked_where(data==Fill_Value, data)
!     # Plot filled contours onto axes
!     filled_contours = map_ax.contourf(data_masked,
!                                       extent=extent,
!                                       origin='upper',
!                                       transform=ccrs.PlateCarree(),
!                                       levels=clevels,
!                                       colors=ccolors,
!                                       alpha=0.6)
!     # Also add line contours
!     custom_cmap = LinearSegmentedColormap.from_list("my_cmap", ccolors)
!     line_contours = map_ax.contour(data_masked,
!                                    extent=extent,
!                                    origin='upper',
!                                    levels=clevels,
!                                    colors='black',
!                                    linewidths=0.5,
!                                    transform=ccrs.PlateCarree())
!
!     # Create proxies for contour colors for legend later on
!     #  (for matplotlib < 3.8)
!     #proxy = [plt.Rectangle((0,0),1,1,fc = pc.get_facecolor()[0])
!     #    for pc in filled_contours.collections]
!     #  (for matplotlib >= 3.8) 
!     proxy = [plt.Rectangle((0,0),1,1,fc = color)
!          for color in filled_contours.get_facecolors()]
!
!     # Plot source location as red triangle
!     volc_map = map_ax.scatter(srcx,srcy,
!                               s=60,
!                               color = 'm',
!                               marker='^',
!                               transform=ccrs.PlateCarree(),
!                               edgecolors='black',
!                               zorder=3)
!     city_x=[]
!     city_y=[]
!     city_n=[]
!     try:
!       with open('cities.xy','r') as f:
!         for line in f:
!           parts = line.strip().split()
!           if len(parts) == 3:
!             city_x.append(float(parts[0]))
!             city_y.append(float(parts[1]))
!             city_n.append(parts[2])
!     except FileNotFoundError:
!         print("Error: cities.xy not found.")
!         exit()
!
!     city_map = map_ax.scatter(city_x,city_y,
!                               s=40,
!                               color = 'k',
!                               marker='o',
!                               transform=ccrs.PlateCarree(),
!                               edgecolors='black',
!                               zorder=3)
!
!     for i, label in enumerate(city_n):
!         city_name=label.replace("\"", "")
!         map_ax.annotate(city_name,
!                         xy=(city_x[i], city_y[i]),
!                         xytext=(3, 3),
!                         textcoords="offset points",
!                         transform=ccrs.PlateCarree(),
!                         annotation_clip=True,
!                         fontsize=10,
!                         fontweight=300,
!                         color="black")
!     # Draw legend
!     map_ax.legend(proxy,tlevels,loc='center left', bbox_to_anchor=(1.05, 0.5),
!                     framealpha=0.9,title=title_legend)
!
!     # Draw USGS logo
!     logo = mpimg.imread(logo_file)
!     main_fig.figimage(logo, 700, 50, zorder=3, alpha=0.7)
!     # Adjust position, zorder, and alpha as needed
!
!     # Annotations
!     map_ax.annotate(annotation_text1,
!                 xy=(0.1, 0.05),xycoords='figure fraction',xytext=(20, 20),
!                 textcoords='offset points',va='bottom',ha='left')
!     map_ax.annotate(annotation_text2,
!                 xy=(0.4, 0.05),xycoords='figure fraction',xytext=(20, 20),
!                 textcoords='offset points',va='bottom',ha='left')
!
!     main_fig.tight_layout()
!
!     plt.title(title_plot)
!     main_fig.savefig('Ash3d_Deposit____final.png',dpi=100)
!     main_fig.savefig('Ash3d_Deposit____final.pdf',dpi=100,format='pdf',bbox_inches='tight')
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dmap_PNG_python(nx,ny,iprod,itime,OutVar,Fill_Value,writeContours)

      use mesh,          only : &
         IsLatLon,de,dn, &
         dx,dy,                              &
         latLL,lonLL,latUR,lonUR,            &
         xLL,yLL,xUR,yUR

      use Output_Vars,   only : &
         !ContourFilled, &
         Con_Cust,Con_Cust_N,Con_Cust_RGB,Con_Cust_Lev,&
         Con_DepThick_mm_N,Con_DepThick_mm_Lev,Con_DepThick_mm_RGB, &
         Con_DepThick_in_N,Con_DepThick_in_Lev,Con_DepThick_in_RGB, &
         Con_DepTime_N,Con_DepTime_Lev,Con_DepTime_RGB, &
         Con_CloudCon_N,Con_CloudCon_Lev,Con_CloudCon_RGB, &
         Con_CloudTop_N,Con_CloudTop_RGB,Con_CloudTop_Lev, &
         Con_CloudBot_N,Con_CloudBot_RGB,Con_CloudBot_Lev, &
         Con_CloudLoad_N,Con_CloudLoad_RGB,Con_CloudLoad_Lev, &
         Con_CloudRef_N,Con_CloudRef_RGB,Con_CloudRef_Lev, &
         Con_CloudTime_N,Con_CloudTime_RGB,Con_CloudTime_Lev, &
         ContourDataX,ContourDataY,ContourDataNcurves,ContourDataNpoints,&
         Extra2dVar,Extra2dVarName,Extra2dVar_Min,Extra2dVar_Max, &
         Extra2dVar_unit,Extra2dVar_lname,&
         !CloudArrivalTime,Mask_Deposit,Mask_Cloud,&
         CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS,ContourLev,nConLev

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap

      use io_data,       only : &
         WriteTimes,cdf_b3l1,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight,lon_volcano,lat_volcano

      use citywriter

      use Ash3d_ASCII_IO,  only : &
          write_2D_ASCII_flt,     &
          write_2D_ASCII_flt_regular

      integer      ,intent(in) :: nx
      integer      ,intent(in) :: ny
      integer      ,intent(in) :: iprod
      integer      ,intent(in) :: itime
      real(kind=ip),intent(in) :: OutVar(nx,ny)
      real(kind=ip),intent(in) :: Fill_Value
      logical      ,intent(in) :: writeContours

      !logical            :: mask(nx,ny)
      character(len=6)   :: Fill_Value_str
      character(len=200) :: cmd

      !real(kind=ip) :: tmp_ip
      integer,dimension(:,:),allocatable :: zrgb
      character(len=40) :: title_plot
      !character(len=30) :: cstr_xlabel = 'Longitude'
      !character(len=30) :: cstr_ylabel = 'Latitude'
      character(len=30) :: cstr_zlabel
      character(len=30) :: cstr_volcname
      character(len=30) :: cstr_run_date
      character(len=30) :: cstr_windfile
      character(len=40) :: cstr_ErStartT
      character(len=27) :: cstr_ErHeight
      character(len=30) :: cstr_ErDuratn
      character(len=38) :: cstr_ErVolume
      character(len=45) :: cstr_note
      character(len=20) :: varname
      character(len= 7) :: tmpstr
      character(len= 9) :: cio
      character(len= 4),parameter :: outfile_ext = '.png'
      character(len=10) :: units
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      integer           :: iw,iwf
      logical           :: HaveIconFile
      character(len=  8):: linebuffer008
      character(len= 12):: linebuffer012
      character(len= 80):: linebuffer080
      character(len=130):: linebuffer130,linebuffer130_2
      character(len=500):: linebuffer500,linebuffer500_2

      ! Plot dimensions
      real(kind=ip)  :: xmin
      real(kind=ip)  :: xmax
      real(kind=ip)  :: ymin
      real(kind=ip)  :: ymax
      logical        :: IsRegGrid

      ! Aux. File names
      character(len=10) :: filename_root
      character(len=9)  :: filename_script
      character(len=20) :: filename_outdata
      character(len=40) :: filename_png
      character(len=40) :: filename_pdf
      !character(len=10) :: filename_contourdata
      !character(len=80) :: filename_coastline

      ! Citywriter variables
      !integer :: icty
      integer :: ncities
      !integer :: cityname_offset_px = 30
      real(kind=ip),dimension(:),allocatable     :: lon_cities
      real(kind=ip),dimension(:),allocatable     :: lat_cities
      character(len=26),dimension(:),allocatable :: name_cities

      ! Contour variables
      integer            :: ilev
      !integer           :: lev_i,substr_pos1,substr_pos2,substr_pos3
      !real(kind=4)      :: lev_r4
      !integer           :: icurve,ipt

      ! Python/Cartopy variables
      character(len=25) :: plotcom
      real(kind=ip)     :: zoomfac   ! zoom factor for resampling the data with
                                     ! a cubic spline interpolant. Can smooth rough
                                     ! contours

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8  ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dmap_PNG_python"
      endif;enddo

      ! Initialization
      zoomfac = 1.0_ip

      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)

      ncities = 20
      allocate(lon_cities(ncities))
      allocate(lat_cities(ncities))
      allocate(name_cities(ncities))

      filename_root        = "outvar"
      filename_outdata     = trim(adjustl(filename_root)) // ".dat"
      filename_script      = trim(adjustl(filename_root)) // ".py"
      !filename_contourdata = trim(adjustl(filename_root)) // ".con"

      if(iprod == 5.or.iprod == 6)then
        cio='____final'
      else
        if (WriteTimes(itime) < 10.0_ip) then
          write(cio,1) WriteTimes(itime)
1         format('00',f4.2,'hrs')
        elseif (WriteTimes(itime) < 100.0_ip) then
          write(cio,2) WriteTimes(itime)
2         format('0',f5.2,'hrs')
        else
          write(cio,3) WriteTimes(itime)
3         format(f6.2,'hrs')
        endif
      endif

      if(Con_Cust)then
        nConLev = Con_Cust_N
        allocate(zrgb(nConLev,3))
        allocate(ContourLev(nConLev))
        ContourLev(1:nConLev) = Con_Cust_Lev(1:nConLev)
        zrgb(1:nConLev,1:3) = Con_Cust_RGB(1:nConLev,1:3)
      endif

      if(iprod == 0)then           ! custom variable
        varname = Extra2dVarName(1:20)
        filename_png = trim(adjustl(Extra2dVarName)) // '_' // cio // outfile_ext
        filename_pdf = trim(adjustl(Extra2dVarName)) // '_' // cio // '.pdf'
        write(tmpstr,'(f7.2)')WriteTimes(itime)
        title_plot = trim(adjustl(Extra2dVar_lname)) // " t=" // tmpstr // " hours"
        units = trim(adjustl(Extra2dVar_unit))
        cstr_zlabel = trim(adjustl(Extra2dVar_lname)) // " (" // trim(adjustl(units)) // ")"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          ! Absent custom contours from a control file, use the 10 levels from deposit (mm), but
          ! evenly spaced between min and max
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          do ilev=1,nConLev
            ContourLev(ilev) = Extra2dVar_Min + (ilev-1)/float(nConLev-1) * (Extra2dVar_Max-Extra2dVar_Min)
          enddo
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 3)then       ! deposit at specified times (mm)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(filename_pdf,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,'.pdf'
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 4)then   ! deposit at specified times (inches)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(filename_pdf,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,'.pdf'
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 5)then       ! deposit at final time (mm)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        write(filename_pdf,'(a13,a9,a4)')'Ash3d_Deposit',cio,'.pdf'
        title_plot = 'Final Deposit Thickness'
        cstr_zlabel = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 6)then   ! deposit at final time (inches)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        write(filename_pdf,'(a13,a9,a4)')'Ash3d_Deposit',cio,'.pdf'
        title_plot = 'Final Deposit Thickness'
        cstr_zlabel = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 7)then   ! ashfall arrival time (hours)
        varname = "depotime"
        write(filename_png,'(a22)')'DepositArrivalTime.png'
        write(filename_pdf,'(a22)')'DepositArrivalTime.pdf'
        write(title_plot,'(a20)')'Ashfall arrival time'
        cstr_zlabel = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 8)then   ! ashfall arrival at airports/POI (mm)
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for airport arrival time data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_python"
        endif;enddo
        stop 1
      elseif(iprod == 9)then   ! ash-cloud concentration
        varname = "ashcon_max"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudCon_t',cio,outfile_ext
        write(filename_pdf,'(a16,a9,a4)')'Ash3d_CloudCon_t',cio,'.pdf'
        write(title_plot,'(a26,f7.2,a6)')'Ash-cloud concentration t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Max.Con.(mg/m3)'
        units = " (mg/m3)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudCon_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudCon_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudCon_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 10)then   ! ash-cloud height
        varname = "cloud_height"
        write(filename_png,'(a19,a9,a4)')'Ash3d_CloudHeight_t',cio,outfile_ext
        write(filename_pdf,'(a19,a9,a4)')'Ash3d_CloudHeight_t',cio,'.pdf'
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud height t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Height(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTop_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTop_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTop_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 11)then   ! ash-cloud bottom
        varname = "cloud_bottom"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudBot_t',cio,outfile_ext
        write(filename_pdf,'(a16,a9,a4)')'Ash3d_CloudBot_t',cio,'.pdf'
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud bottom t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Bot.(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudBot_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudBot_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudBot_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 12)then   ! ash-cloud load
        varname = "cloud_load"
        write(filename_png,'(a17,a9,a4)')'Ash3d_CloudLoad_t',cio,outfile_ext
        write(filename_pdf,'(a17,a9,a4)')'Ash3d_CloudLoad_t',cio,'.pdf'
        write(title_plot,'(a17,f7.2,a6)')'Ash-cloud load t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Load(T/km2)'
        units = " (T/km2)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudLoad_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudLoad_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudLoad_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 13)then  ! radar reflectivity
        varname = "radar_reflectivity"
        write(filename_png,'(a20,a9,a4)')'Ash3d_CloudRadRefl_t',cio,outfile_ext
        write(filename_pdf,'(a20,a9,a4)')'Ash3d_CloudRadRefl_t',cio,'.pdf'
        write(title_plot,'(a24,f7.2,a6)')'Ash-cloud radar refl. t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Refl.(dBz)'
        units = " (dBz)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudRef_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudRef_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudRef_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 14)then   ! ashcloud arrival time (hours)
        varname = "ash_arrival_time"
        write(filename_png,'(a20)')'CloudArrivalTime.png'
        write(filename_pdf,'(a20)')'CloudArrivalTime.pdf'
        write(title_plot,'(a22)')'Ash-cloud arrival time'
        cstr_zlabel = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 15)then   ! topography
        varname = "topography"
        write(filename_png,'(a14)')'Topography.png'
        write(filename_pdf,'(a14)')'Topography.pdf'
        write(title_plot,'(a10)')'Topography'
        cstr_zlabel = 'Elevation (km)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = 8
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev = [1.0_ip, 2.0_ip, 3.0_ip, 4.0_ip, &
                        5.0_ip, 6.0_ip, 7.0_ip, 8.0_ip]
        endif
      elseif(iprod == 16)then   ! profile plots
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for vertical profile data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_python"
        endif;enddo
        stop 1
      else
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"ERROR: unexpected variable"
          write(errlog(io),*)"         iprod = ",iprod
          write(errlog(io),*)"       Cannot map this variable."
        endif;enddo
        stop 1
      endif
      ! Now have string vars (varname,cstr_zlabel, etc.) and contour info (nConLev,zrgb,ContourLev)

      if(writeContours)then
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"Running cartopy to calculate contours lines"
          write(errlog(io),*)"Not sure yet how to save contour data with cartopy"
          write(errlog(io),*)"If you want shapefiles, recompile without cartopy or"
          write(errlog(io),*)" reset the plot_pref_shp variable."
          write(errlog(io),*)"Exiting"
        endif;enddo
        stop 1
      else
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Running cartopy to generate contour plot"
        endif;enddo
      endif

      ! This is the section where we actually start plotting the map
      ! Evaluate grid
      if(IsLatLon)then
        if(lonUR-lonLL >= 360.0_ip)then
          lonLL = 0.0_ip
          lonUR = 360.0_ip
        endif
        xmin = lonLL
        ! Make sure xmin is in the range -180->180
        if (xmin > 180.0_ip)then
          xmin = lonLL-360.0_ip
          xmax = lonUR-360.0_ip
        else
          xmax = lonUR
        endif
        ymin = latLL
        ymax = latUR
        if(abs(dn-de) < 1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
      else
        xmin = xLL
        xmax = xUR
        ymin = yLL
        ymax = yUR
        if(abs(dx-dy) < 1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
        !do io=1,2;if(VB(io) <= verbosity_error)then
        !  write(errlog(io),*)"ERROR: Currenntly, plotting with cartopy only enabled for lon/lat grids."
        !  write(errlog(io),*)"       Please use GMT to plot projected maps."
        !  write(errlog(io),*)"       ./ASH3DPLOT=4 ./Ash3d_PostProc ...."
        !endif;enddo
        !stop 1
      endif

      ! write out the data in a form that python can read
      ! Python script expects an ESRI ASCII data file; force regular
      if(IsRegGrid)then
        ! If the grid is regular (dx=dy) then we can write an ESRI ASCII file and convert to grd
        varname = "outvar"
        call write_2D_ASCII_flt(nx,ny,IsLatLon,real(xmin,kind=sp),real(ymin,kind=sp),.true., &
                           real(de,kind=sp),real(dn,kind=sp),Fill_Value_str,&
                           real(OutVar,kind=sp),filename_outdata)
      else
        ! Irregular grids are problematic, call special ASCII interpolator
        call write_2D_ASCII_flt_regular(nx,ny,IsLatLon,real(xmin,kind=sp),real(ymin,kind=sp),.true., &
                           real(de,kind=sp),real(dn,kind=sp),Fill_Value_str,&
                           real(OutVar,kind=sp),filename_outdata)
      endif
      ! Finished temporary data file

      call citylist(2,                        &  ! 2 is for external file in gnuplot format
                    xmin,xmax,ymin,ymax,      &
                    ncities,                  &
                    lon_cities,               &
                    lat_cities,               &
                    name_cities)
      if(lon_volcano > xmax)lon_volcano=lon_volcano-360.0_ip

      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions > 1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'

      if(writeContours)then
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Running python to calculate contours lines"
        endif;enddo
        write(filename_png,'(a14)')'tmp.png'
        allocate(ContourDataNcurves(nConLev))
        allocate(ContourDataNpoints(nConLev,CONTOUR_MAXCURVES))
        allocate(ContourDataX(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        allocate(ContourDataY(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        ContourDataNcurves(:)   = 0
        ContourDataNpoints(:,:) = 0
        ContourDataX(:,:,:)     = 0.0_ip
        ContourDataY(:,:,:)     = 0.0_ip
      else
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Running python to generate contour plot"
        endif;enddo
      endif

      ! Set up to plot via python script
      open(unit=fid_script,file=filename_script,status='replace')

      ! Python mapping expects matplotlib and cartopy for geographic mapping.
      ! Additinoally, gdal and geopandas are needed for loading ASCII files
      ! and handling geospatial data. We recommend using Anaconda:
      !
      ! (1) Download anaconda:
      !   curl -O https://repo.anaconda.com/archive/Anaconda3-2025.06-0-Linux-x86_64.sh
      !
      ! (2) Install:
      !   bash ~/Anaconda3-2025.06-0-Linux-x86_64.sh
      !  Accept terms of service.
      !  Accept default install location: ~/anaconda3
      !  Choose 'no' when asked about editing start-up scripts.
      !
      ! (3) Initialize anaconda manually.
      !   export PATH="$HOME/anaconda3/bin:$PATH"
      !   conda init
      !
      ! (4) Install the packages your script needs:
      !   conda install -c conda-forge geopandas
      !   conda install -c scitools cartopy
      !   conda install -c gdal

      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary python/cartopy script for producing 2d maps for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"# This script draws heavily from scripts created by Tyler Paladino."
      write(fid_script,'(g0)')"# You will need the packages conda-forge, geopandas, scitools, cartopy, gdal"
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"import cartopy.feature as cfeature"
      write(fid_script,'(g0)')"import cartopy.crs as ccrs"
      write(fid_script,'(g0)')"import matplotlib.pyplot as plt"
      write(fid_script,'(g0)')"from mpl_toolkits.axes_grid1.inset_locator import inset_axes"
      write(fid_script,'(g0)')"import matplotlib.image as mpimg"
      write(fid_script,'(g0)')"from matplotlib.colors import LinearSegmentedColormap"
      write(fid_script,'(g0)')"from matplotlib.offsetbox import OffsetImage, AnnotationBbox, TextArea"
      write(fid_script,'(g0)')"import numpy as np"
      write(fid_script,'(g0)')"import scipy.ndimage"
      write(fid_script,'(g0)')"from osgeo import gdal, osr"
      write(fid_script,'(g0)')"import linecache"
      write(fid_script,'(g0)')"import sys"  ! This is not really needed unless you are debugging the script
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"def get_extent(gdal_ds, A3D_input_fn):"
      write(fid_script,'(g0)')"    Xsize = gdal_ds.RasterXSize"
      write(fid_script,'(g0)')"    Ysize = gdal_ds.RasterYSize"
      write(fid_script,'(g0)')"    cellsize = gdal_ds.GetGeoTransform()[1]"
      write(fid_script,'(g0)')"    xcorner, ycorner = get_proj_info(A3D_input_fn)"
      write(fid_script,'(g0)')"    minx = xcorner+cellsize"
      write(fid_script,'(g0)')"    miny = ycorner+cellsize"
      write(fid_script,'(g0)')"    maxx = minx + (cellsize*Xsize)"
      write(fid_script,'(g0)')"    maxy = miny + (cellsize*Ysize)"
      write(fid_script,'(g0)')"    return [minx, maxx, miny, maxy]"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"def get_proj_info(fn):"
      write(fid_script,'(g0)')"    xl_corner = linecache.getline(fn, 3)"
      write(fid_script,'(g0)')"    yl_corner = linecache.getline(fn, 4)"
      write(fid_script,'(g0)')"    return float(xl_corner.split()[1]), float(yl_corner.split()[1])"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"def draw_logo(ax,fn):"
      write(fid_script,'(g0)')"    # Create background box"
      write(fid_script,'(g0)')"    ax_inset = inset_axes("
      write(fid_script,'(g0)')"        ax,"
      write(fid_script,'(g0)')'        width="18%",'
      write(fid_script,'(g0)')'        height="7%",'
      write(fid_script,'(g0)')"        borderpad=.5,"
      write(fid_script,'(g0)')'        loc="upper right"'
      write(fid_script,'(g0)')"    )"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    img = mpimg.imread(fn)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    # ax.patch.set_alpha(0.5)"
      write(fid_script,'(g0)')"    # Remove axis borders"
      write(fid_script,'(g0)')"    # ax_inset.set_axis_off()"
      write(fid_script,'(g0)')"    ax_inset.set_xticks([])"
      write(fid_script,'(g0)')"    ax_inset.set_yticks([])"
      write(fid_script,'(g0)')"    ax_inset.set_facecolor([1,1,1,0.8])"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    ax_logo = inset_axes("
      write(fid_script,'(g0)')"        ax_inset,"
      write(fid_script,'(g0)')'        width="90%",'
      write(fid_script,'(g0)')'        height="90%",'
      write(fid_script,'(g0)')'        loc="center"'
      write(fid_script,'(g0)')"    )"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    ax_logo.imshow(img)"
      write(fid_script,'(g0)')"    ax_logo.set_axis_off()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"    return None"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Turn on gdal exceptions"
      write(fid_script,'(g0)')"gdal.UseExceptions()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Institutional logo (Defaults to USGS)"
      linebuffer080 = "logo_file = '" // trim(adjustl(Instit_IconFile)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Run values"
      write(fid_script,'(g0,f10.3)')"srcx=",lon_volcano
      write(fid_script,'(g0,f10.3)')"srcy=",lat_volcano
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"#######################################"
      write(fid_script,'(g0)')"# Product values"
      write(fid_script,'(g0)')'grid_file="outvar.dat"'
      linebuffer080 = 'title_plot="'// trim(adjustl(title_plot)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = 'title_legend="' // trim(adjustl(cstr_zlabel)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))

      linebuffer500  ="clevels=["
      linebuffer500_2="tlevels=['"
      do ilev=1,nConLev
        write(linebuffer012,'(e12.3)')ContourLev(ilev)
        linebuffer500 = trim(adjustl(linebuffer500)) // linebuffer012
        if(ilev < nConLev) linebuffer500 = trim(adjustl(linebuffer500)) // ','
        linebuffer500_2 = trim(adjustl(linebuffer500_2)) // linebuffer012
        if(ilev < nConLev) then
          linebuffer500_2 = trim(adjustl(linebuffer500_2)) // "','"
        else
          linebuffer500_2 = trim(adjustl(linebuffer500_2)) // "']"
        endif
      enddo
      linebuffer500 = trim(adjustl(linebuffer500)) // ']'
      write(fid_script,'(g0)')trim(adjustl(linebuffer500))
      do ilev=1,nConLev
        if(ilev == 1)then
          write(linebuffer080,101)real(zrgb(ilev,1:3)/255.0,kind=4)
        elseif(ilev == nConLev)then
          write(linebuffer080,103)real(zrgb(ilev,1:3)/255.0,kind=4)
        else
          write(linebuffer080,102)real(zrgb(ilev,1:3)/255.0,kind=4)
        endif
        write(fid_script,'(g0)')linebuffer080
      enddo
 101  format('ccolors=[( ',f5.2,',',f5.2,',',f5.2,'),' )
 102  format('         ( ',f5.2,',',f5.2,',',f5.2,'),' )
 103  format('         ( ',f5.2,',',f5.2,',',f5.2,')]' )
      write(fid_script,'(g0)')trim(adjustl(linebuffer500_2))
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"#######################################"

      linebuffer080 ='txt_vname="'    // trim(adjustl(cstr_volcname)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 ='txt_RunDate="'  // trim(adjustl(cstr_run_date)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 ='txt_Windfile="' // trim(adjustl(cstr_windfile)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 ='txt_ESrtTime="' // trim(adjustl(cstr_ErStartT)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 ='txt_EPlmH="'    // trim(adjustl(cstr_ErHeight)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 ='txt_EDur="'     // trim(adjustl(cstr_ErDuratn)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 ='txt_EVol="'     // trim(adjustl(cstr_ErVolume)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))

      write(fid_script,'(g0)')" "
      linebuffer080 = 'annotation_text1 = txt_vname    + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_RunDate  + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_Windfile'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = 'annotation_text2 = txt_ESrtTime + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_EPlmH    + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_EDur     + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_EVol'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"###################### OPEN ASH DATA FILE AND GET GEOTRANSFORM #######################"
      write(fid_script,'(g0)')"# Open raster with GDAL"
      write(fid_script,'(g0)')"raster = gdal.Open(grid_file)"
      write(fid_script,'(g0)')"# Get lat/lon extent of raster"
      write(fid_script,'(g0)')"extent = get_extent(raster, grid_file)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"############################# PLOT ######################################"
      write(fid_script,'(g0)')"# Create figure"
      write(fid_script,'(g0)')"main_fig = plt.figure(figsize=(8.5, 6))"
      write(fid_script,'(g0)')"# Create geospatial matplotlib axes with CartoPy."
      write(fid_script,'(g0)')"# Use a PlateCarree projection for now"
      write(fid_script,'(g0)')"cen_lon=0.5*(sum(extent))"
      write(fid_script,'(g0)')"img_extent = extent"
      write(fid_script,'(g0)')"# Hard-code map limits here, if needed"
      write(fid_script,'(g0)')"#img_extent =  [-165.0, -162.0, 53.0, 56.0]"
      write(fid_script,'(g0)')"projection = ccrs.PlateCarree(central_longitude=cen_lon)  ",&
                        "# this is the Cartopy bit"
      write(fid_script,'(g0)')"map_ax = main_fig.add_subplot(4,1,(1,3),projection=projection) ",&
                        "# create the matplotlib mapping with this projection"
      write(fid_script,'(g0)')"map_ax.set_extent(img_extent)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Add coastlines and water"
      write(fid_script,'(g0)')"map_ax.add_feature(cfeature.LAND, facecolor='lightgrey')"
      write(fid_script,'(g0)')"map_ax.coastlines()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Add gridlines"
      write(fid_script,'(g0)')"gl = map_ax.gridlines(draw_labels=True,"
      write(fid_script,'(g0)')"                      x_inline=False,"
      write(fid_script,'(g0)')"                      y_inline=False,"
      write(fid_script,'(g0)')"                      color='black',"
      write(fid_script,'(g0)')"                      alpha=0.5,"
      write(fid_script,'(g0)')"                      linestyle='--')"
      write(fid_script,'(g0)')"# Get rid of top and right side labels"
      write(fid_script,'(g0)')"gl.top_labels = False"
      write(fid_script,'(g0)')"gl.right_labels = False"
      write(fid_script,'(g0)')"# Get grided data from GDAL dataset"
      write(fid_script,'(g0)')"data = raster.GetRasterBand(1).ReadAsArray()"
      write(fid_script,'(a31,f5.2,a1)')"data = scipy.ndimage.zoom(data,",zoomfac,")"
      write(fid_script,'(g0)')"# Mask out any values that are = to fill_value"
      write(fid_script,'(g0)')"Fill_Value=0"
      write(fid_script,'(g0)')"data_masked = np.ma.masked_where(data==Fill_Value, data)"
      write(fid_script,'(g0)')"# Plot filled contours onto axes"
      write(fid_script,'(g0)')"filled_contours = map_ax.contourf(data_masked,"
      write(fid_script,'(g0)')"                                  extent=extent,"
      write(fid_script,'(g0)')"                                  origin='upper',"
      write(fid_script,'(g0)')"                                  transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                                  levels=clevels,"
      write(fid_script,'(g0)')"                                  colors=ccolors,"
      write(fid_script,'(g0)')"                                  alpha=0.6)"
      write(fid_script,'(g0)')"# Also add line contours"
      write(fid_script,'(g0)')'custom_cmap = LinearSegmentedColormap.from_list("my_cmap", ccolors)'
      write(fid_script,'(g0)')"line_contours = map_ax.contour(data_masked,"
      write(fid_script,'(g0)')"                               extent=extent,"
      write(fid_script,'(g0)')"                               origin='upper',"
      write(fid_script,'(g0)')"                               levels=clevels,"
      write(fid_script,'(g0)')"                               colors='black',"
      write(fid_script,'(g0)')"                               linewidths=0.5,"
      write(fid_script,'(g0)')"                               transform=ccrs.PlateCarree())"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Create proxies for contour colors for legend later on"
      write(fid_script,'(g0)')"#  (for matplotlib < 3.8)"
      write(fid_script,'(g0)')"#proxy = [plt.Rectangle((0,0),1,1,fc = pc.get_facecolor()[0])"
      write(fid_script,'(g0)')"#    for pc in filled_contours.collections]"
      write(fid_script,'(g0)')"#  (for matplotlib >= 3.8)"
      write(fid_script,'(g0)')"proxy = [plt.Rectangle((0,0),1,1,fc = color)"
      write(fid_script,'(g0)')"     for color in filled_contours.get_facecolors()]"
      write(fid_script,'(g0)')"# Plot source location as red triangle"
      write(fid_script,'(g0)')"volc_map = map_ax.scatter(srcx,srcy,"
      write(fid_script,'(g0)')"                          s=60,"
      write(fid_script,'(g0)')"                          color = 'm',"
      write(fid_script,'(g0)')"                          marker='^',"
      write(fid_script,'(g0)')"                          transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                          edgecolors='black',"
      write(fid_script,'(g0)')"                          zorder=3)"
      write(fid_script,'(g0)')"city_x=[]"
      write(fid_script,'(g0)')"city_y=[]"
      write(fid_script,'(g0)')"city_n=[]"
      write(fid_script,'(g0)')"try:"
      write(fid_script,'(g0)')"  with open('cities.xy','r') as f:"
      write(fid_script,'(g0)')"    for line in f:"
      write(fid_script,'(g0)')"      parts = line.strip().split()"
      write(fid_script,'(g0)')"      if len(parts) == 3:"
      write(fid_script,'(g0)')"        city_x.append(float(parts[0]))"
      write(fid_script,'(g0)')"        city_y.append(float(parts[1]))"
      write(fid_script,'(g0)')"        city_n.append(parts[2])"
      write(fid_script,'(g0)')"except FileNotFoundError:"
      write(fid_script,'(g0)')'    print("Error: cities.xy not found.")'
      write(fid_script,'(g0)')"    exit()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"city_map = map_ax.scatter(city_x,city_y,"
      write(fid_script,'(g0)')"                          s=40,"
      write(fid_script,'(g0)')"                          color = 'k',"
      write(fid_script,'(g0)')"                          marker='o',"
      write(fid_script,'(g0)')"                          transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                          edgecolors='black',"
      write(fid_script,'(g0)')"                          zorder=3)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"for i, label in enumerate(city_n):"
      write(fid_script,'(g0)')'    city_name=label.replace("\"", "")'
      write(fid_script,'(g0)')"    map_ax.annotate(city_name,"
      write(fid_script,'(g0)')"                    xy=(city_x[i], city_y[i]),"
      write(fid_script,'(g0)')"                    xytext=(3, 3),"
      write(fid_script,'(g0)')'                    textcoords="offset points",'
      write(fid_script,'(g0)')"                    transform=ccrs.PlateCarree(),"
      write(fid_script,'(g0)')"                    annotation_clip=True,"
      write(fid_script,'(g0)')"                    fontsize=10,"
      write(fid_script,'(g0)')"                    fontweight=300,"
      write(fid_script,'(g0)')'                    color="black")'
      write(fid_script,'(g0)')"# Draw legend"
      write(fid_script,'(g0)')"map_ax.legend(proxy,tlevels,loc='center left', bbox_to_anchor=(1.05, 0.5),"
      write(fid_script,'(g0)')"                framealpha=0.9,title=title_legend)"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Draw USGS logo"
      write(fid_script,'(g0)')"logo = mpimg.imread(logo_file)"
      write(fid_script,'(g0)')"main_fig.figimage(logo, 700, 50, zorder=3, alpha=0.7) ",&
                        "# Adjust position, zorder, and alpha as needed"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Annotations"
      write(fid_script,'(g0)')"map_ax.annotate(annotation_text1,"
      write(fid_script,'(g0)')"            xy=(0.1, 0.05),xycoords='figure fraction',xytext=(20, 20),"
      write(fid_script,'(g0)')"            textcoords='offset points',va='bottom',ha='left')"
      write(fid_script,'(g0)')"map_ax.annotate(annotation_text2,"
      write(fid_script,'(g0)')"            xy=(0.4, 0.05),xycoords='figure fraction',xytext=(20, 20),"
      write(fid_script,'(g0)')"            textcoords='offset points',va='bottom',ha='left')"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"main_fig.tight_layout()"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"plt.title(title_plot)"
      linebuffer080 = "main_fig.savefig(f'" // trim(adjustl(filename_png)) // "',dpi=100)"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer130 = "#main_fig.savefig(f'" // trim(adjustl(filename_pdf)) // "',dpi=100,format='pdf',bbox_inches='tight')"
      write(fid_script,'(g0)')trim(adjustl(linebuffer130))

      close(fid_script)

      write(plotcom,'(a11,a14)')'python ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      if(iostatus /= 0)then
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"WARNING: python command is returing a non-zero error code:", iostatus
          write(errlog(io),*)"         Maybe your python installation is incomplete"
          write(errlog(io),*)"         Make sure you install the following in your conda environment:"
          write(errlog(io),*)"           conda install -c conda-forge geopandas"
          write(errlog(io),*)"           conda install -c scitools cartopy"
          write(errlog(io),*)"           conda install -c conda-forge gdal"
          write(errlog(io),*)"         Then activate your environment:"
          write(errlog(io),*)"           conda create --name geo_env"
          write(errlog(io),*)"           conda activate geo_env"
        endif;enddo
        stop 1
      endif

      ! Clean up
      if (CleanScripts_python) then
        cmd = "rm -f outvar.dat outvar.py cities.xy"
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      ! clean up memory
      if(allocated(lon_cities))         deallocate(lon_cities)
      if(allocated(lat_cities))         deallocate(lat_cities)
      if(allocated(name_cities))        deallocate(name_cities)
      if(allocated(zrgb))               deallocate(zrgb)

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dmap_PNG_python"
      endif;enddo

      return

      end subroutine write_2Dmap_PNG_python

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dprof_PNG_python
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    vprof_ID        = ID of the profile (number in list from Ash3d control file)
!
!  This subroutine creates a png plot of the transient vertical profile of ash
!  concentration above the profile point (vprof_ID) using the python graphics
!  package.
!
!  To invoke:
!   ASH3DPLOT=6 ./Ash3d_PostProc 3d_tephra_fall.nc 16 3
!
!   Example script:
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dprof_PNG_python(vprof_ID)

      use global_param,  only : &
         KG_2_MG,KM3_2_M3

      use mesh,          only : &
         IsLatLon,nzmax,z_cc_pd

      use Output_Vars,   only : &
         pr_ash,CLOUDCON_THRESH

      use io_data,       only : &
         Site_vprofile,x_vprofile,y_vprofile,cdf_b3l1,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap,ntmax,time_native

      integer,intent (in) :: vprof_ID

      logical           :: HaveIconFile
      character(len=76) :: title_plot
      character(len=30) :: cstr_xlabel
      character(len=30) :: cstr_ylabel
      character(len=30) :: cstr_zlabel
      character(len=30) :: cstr_volcname
      character(len=30) :: cstr_run_date
      character(len=30) :: cstr_windfile
      character(len=40) :: cstr_ErStartT
      character(len=27) :: cstr_ErHeight
      character(len=30) :: cstr_ErDuratn
      character(len=38) :: cstr_ErVolume
      character(len=45) :: cstr_note

      character(len=10) :: filename_root
      character(len=13) :: filename_script
      character(len=14) :: filename_outdata
      character(len=14) :: filename_png
      character(len=27) :: coord_str
      character(len=80) :: plotcom
      integer           :: i,k
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      integer           :: iw,iwf
      character(len= 80):: linebuffer080
      character(len=200):: cmd
      integer,parameter :: fid_script   = 55
      integer,parameter :: fid_outdata  = 54

      ! Plotting variables

      real(kind=ip) :: tmin    , zmin    , cmin      ! graph minima
      real(kind=ip) :: tmax    , zmax    , cmax      ! graph maxima
      real(kind=ip) :: tlab1   , zlab1   , clab1     ! graph first label
      real(kind=ip) :: tlabstep, zlabstep, clabstep  ! graph label increment
      real(kind=ip) :: cloudcon_thresh_mgm3
      real(kind=ip)  :: dtg
      real(kind=ip)  :: dzg

      ! Python variables

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8  ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dprof_PNG_python"
      endif;enddo

      ! Initialization
      cstr_xlabel = 'Time (hours after eruption)'
      cstr_ylabel = 'Height (km)'
      cstr_zlabel = 'Ash conc. mg/m3'

      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)

      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions > 1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'

      write(filename_root,52)vprof_ID
 52   format('vprof_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".py"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      ! Get min/max and label interval for all three axies.
      tmin=real(0,kind=ip)
      tmax=real(ceiling(time_native(ntmax)),kind=ip)
      tlab1    = 0.0_ip
      if(tmax > 240.0_ip)then
        tlabstep = 48.0_ip
      elseif(tmax > 120.0_ip)then
        tlabstep = 24.0_ip
      elseif(tmax > 30.0_ip)then
        tlabstep = 10.0_ip
      elseif(tmax > 15.0_ip)then
        tlabstep = 5.0_ip
      elseif(tmax > 6.0_ip)then
        tlabstep = 2.0_ip
      else
        tlabstep = 1.0_ip
      endif

      zmin=real(0,kind=ip)
      zmax=real(z_cc_pd(nzmax),kind=ip)
      zlab1    = 0.0_ip
      if(zmax > 30.0_ip)then
        zlabstep = 10.0_ip
      elseif(zmax > 15.0_ip)then
        zlabstep = 5.0_ip
      elseif(zmax > 6.0_ip)then
        zlabstep = 2.0_ip
      else
        zlabstep = 1.0_ip
      endif

      cloudcon_thresh_mgm3 = CLOUDCON_THRESH * KG_2_MG / KM3_2_M3  ! convert from kg/km3 to mg/m3
      cmin=real(0,kind=ip)
      cmax=real(maxval(pr_ash(:,:,vprof_ID)),kind=ip)    ! Get the max value for this profile
      cmin=real(min(cmin,cloudcon_thresh_mgm3),kind=ip)  ! Do not let cmax drop below the threshold
      if    (cmax > 4.0e4_ip)then
          clabstep = 5.0e3_ip
      elseif(cmax > 1.0e4_ip)then
          clabstep = 2.0e3_ip
      elseif(cmax > 4.0e3_ip)then
          clabstep = 5.0e2_ip
      elseif(cmax > 1.0e3_ip)then
          clabstep = 2.0e2_ip
      elseif(cmax > 4.0e2_ip)then
          clabstep = 5.0e1_ip
      elseif(cmax > 1.0e2_ip)then
          clabstep = 2.0e1_ip
      elseif(cmax > 4.0e1_ip)then
          clabstep = 5.0e0_ip
      elseif(cmax > 1.0e1_ip)then
          clabstep = 2.0e0_ip
      elseif(cmax > 1.0e0_ip)then
          clabstep = 5.0e-1_ip
      else
          clabstep = 1.0e-1_ip
      endif
      clab1    = 0.0_ip

      dtg = (tmax-tmin)/100.0_ip
      dzg = (zmax-zmin)/100.0_ip

      ! Prep data: python uses a csv file with one header line
      open(unit=fid_outdata,file=filename_outdata,status='replace')
      write(fid_outdata,*)'Time                   ,  Height                 ,    Concen'
      do i = 1,ntmax
        do k = 1,nzmax
          write(fid_outdata,*)time_native(i),', ',z_cc_pd(k),', ',pr_ash(k,i,vprof_ID)
        enddo
        write(fid_outdata,*)""
      enddo
      close(fid_outdata)

      ! Build the plot title
      if(IsLatLon)then
        write(coord_str,101)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      else
        write(coord_str,102)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      endif
 101  format(' (lon=',f7.2,', lat=',f6.2,')')
 102  format(' (x=',f9.3,', y=',f9.3,')')
      write(title_plot,*)trim(adjustl(Site_vprofile(vprof_ID))),coord_str

      ! Set up to plot via python script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary python script for producing vertical profiles for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"# You will need the packages conda-forge, geopandas, matplotlib"
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"import pandas as pd"
      write(fid_script,'(g0)')"import matplotlib.image as mpimg"
      write(fid_script,'(g0)')"import matplotlib.pyplot as plt"
      write(fid_script,'(g0)')"import numpy as np"
      write(fid_script,'(g0)')"import matplotlib.tri as tri"
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"# Institutional logo (Defaults to USGS)"
      linebuffer080 = "logo_file = '" // trim(adjustl(Instit_IconFile)) // "'"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')" "

      linebuffer080 = 'data_file="' // trim(adjustl(filename_outdata)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = 'fig_name="' // trim(adjustl(filename_png)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = 'title_plot="' // trim(adjustl(title_plot)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))

      write(fid_script,'(g0)')" "
      linebuffer080 = 'txt_vname_dat="' // trim(adjustl(VolcanoName)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = 'txt_RunDate_dat="' // trim(adjustl(os_time_log)) // '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      read(cdf_b3l1,*,iostat=iostatus) iw,iwf
      write(linebuffer080,'(a18,i2,a1)')'txt_Windfile_dat="' , iwf , '"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(linebuffer080,'(a18,a20,a1)')'txt_ESrtTime_dat="',HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap),'"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(linebuffer080,'(a15,g10.5,a1)')'txt_EPlmH_dat="',real(e_PlumeHeight(1),kind=4),'"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(linebuffer080,'(a14,g10.5,a1)')'txt_EDur_dat="',real(e_Duration(1),kind=4),'"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(linebuffer080,'(a14,g10.5,a1)')'txt_EVol_dat="',real(e_Volume(1),kind=4),'"'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')" "
      write(fid_script,'(g0)')"#######################################"

      linebuffer080 ='txt_vname="'    // trim(adjustl(cstr_volcname)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 ='txt_RunDate="'  // trim(adjustl(cstr_run_date)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 ='txt_Windfile="' // trim(adjustl(cstr_windfile)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 ='txt_ESrtTime="' // trim(adjustl(cstr_ErStartT)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 ='txt_EPlmH="'    // trim(adjustl(cstr_ErHeight)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 ='txt_EDur="'     // trim(adjustl(cstr_ErDuratn)) // '"'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 ='txt_EVol="'     // trim(adjustl(cstr_ErVolume)) // '"'
      write(fid_script,'(g0)')linebuffer080

      write(fid_script,'(g0)')" "
      linebuffer080 = 'annotation_text1 = txt_vname    + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_RunDate  + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_Windfile'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = 'annotation_text2 = txt_ESrtTime + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_EPlmH    + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_EDur     + "\n" + ' // bs
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      linebuffer080 = '                   txt_EVol'
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))
      write(fid_script,'(g0)')' '

      write(fid_script,'(g0)')'####################### OPEN ASH DATA FILE #######################'
      write(fid_script,'(g0)')'## Open data file'
      write(fid_script,'(g0)')'df = pd.read_csv(data_file)'
      write(fid_script,'(g0)')'t_column = df.iloc[:, 0]'
      write(fid_script,'(g0)')'z_column = df.iloc[:, 1]'
      write(fid_script,'(g0)')'c_column = df.iloc[:, 2]'
      write(fid_script,'(g0)')' '
      write(fid_script,'(a7,i6)')'npts = ',ntmax*nzmax
      write(fid_script,'(g0)')'ngridt = 100'
      write(fid_script,'(g0)')'ngridz = 100'
      write(fid_script,'(g0)')' '
      write(fid_script,'(g0)')'# Create grid values first.'
      write(fid_script,'(a20,f8.3,a9)')'ti = np.linspace(0, ',tmax,', ngridt)'
      write(fid_script,'(a20,f8.3,a9)')'zi = np.linspace(0, ',zmax,', ngridz)'
      write(fid_script,'(g0)')' '
      write(fid_script,'(g0)')'# Linearly interpolate the data (x, y) on a grid defined by (ti, zi).'
      write(fid_script,'(g0)')'triang = tri.Triangulation(t_column, z_column)'
      write(fid_script,'(g0)')'interpolator = tri.LinearTriInterpolator(triang, c_column)'
      write(fid_script,'(g0)')'Ti, Zi = np.meshgrid(ti, zi)'
      write(fid_script,'(g0)')'coni = interpolator(Ti, Zi)'
      write(fid_script,'(g0)')'# '
      write(fid_script,'(g0)')'############################## PLOT ######################################'
      write(fid_script,'(g0)')'## Create figure'
      write(fid_script,'(g0)')'main_fig = plt.figure(figsize=(8.5, 6))'
      write(fid_script,'(g0)')'ax1 = main_fig.add_subplot(4,1,(1,3))'
      write(fid_script,'(g0)')"ax1.contour(ti, zi, coni, levels=10, linewidths=0.5, colors='k')"
      write(fid_script,'(g0)')"cntr1 = ax1.contourf(ti, zi, coni, levels=8, cmap='jet')"
      linebuffer080 = "main_fig.colorbar(cntr1, ax=ax1, label='" // cstr_zlabel // "')"
      write(fid_script,'(g0)')linebuffer080
      write(linebuffer080,'(a17,f8.3,a12,f8.3,a2)')'ax1.set(xlim=(0, ',tmax,'), ylim=(0, ',zmax,'))'
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 = "ax1.set_xlabel('" // cstr_xlabel // "')"
      write(fid_script,'(g0)')linebuffer080
      linebuffer080 = "ax1.set_xlabel('" // cstr_ylabel // "')"
      write(fid_script,'(g0)')linebuffer080
      write(fid_script,'(g0)')''
      write(fid_script,'(g0)')''
      write(fid_script,'(g0)')'# Draw USGS logo'
      write(fid_script,'(g0)')'logo = mpimg.imread(logo_file)'
      write(fid_script,'(g0)')'main_fig.figimage(logo, 700, 50, zorder=3, alpha=0.7)'
      write(fid_script,'(g0)')'# Adjust position, zorder, and alpha as needed'
      write(fid_script,'(g0)')' '
      write(fid_script,'(g0)')'# Annotations'
      write(fid_script,'(g0)')"ax1.annotate(annotation_text1,"
      write(fid_script,'(g0)')"            xy=(0.1, 0.05),xycoords='figure fraction',xytext=(20, 20),"
      write(fid_script,'(g0)')"            textcoords='offset points',va='bottom',ha='left')"
      write(fid_script,'(g0)')"ax1.annotate(annotation_text2,"
      write(fid_script,'(g0)')"            xy=(0.4, 0.05),xycoords='figure fraction',xytext=(20, 20),"
      write(fid_script,'(g0)')"            textcoords='offset points',va='bottom',ha='left')"
      write(fid_script,'(g0)')' '
      write(fid_script,'(g0)')'main_fig.tight_layout()'
      write(fid_script,'(g0)')' '
      write(fid_script,'(g0)')'plt.title(title_plot)'
      linebuffer080 = "main_fig.savefig(f'" // trim(adjustl(filename_png)) // "',dpi=100)"
      write(fid_script,'(g0)')trim(adjustl(linebuffer080))

      write(plotcom,'(a11,a14)')'python ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      if(iostatus /= 0)then
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"WARNING: python command is returing a non-zero error code:", iostatus
          write(errlog(io),*)"         Maybe your python installation is incomplete"
          write(errlog(io),*)"         Make sure you install the following in your conda environment:"
          write(errlog(io),*)"           conda install -c conda-forge geopandas"
          write(errlog(io),*)"           conda install -c scitools cartopy"
          write(errlog(io),*)"           conda install -c conda-forge gdal"
          write(errlog(io),*)"         Then activate your environment:"
          write(errlog(io),*)"           conda create --name geo_env"
          write(errlog(io),*)"           conda activate geo_env"
        endif;enddo
        stop 1
      endif

      ! Clean up
      if (CleanScripts_python) then
        cmd = "rm -f vprof_*.dat vprof_*.py"
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dprof_PNG_python"
      endif;enddo

      return
      end subroutine write_2Dprof_PNG_python

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_DepPOI_TS_PNG_python
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    pt_indx       = index of point in Ash3d netcdf output file
!
!  This subroutine creates a png plot of the transient deposit accumulation at
!  the airport/POI given by pt_index using the python graphics package.
!
!  To invoke:
!   ASH3DPLOT=6 ./Ash3d_PostProc 3d_tephra_fall.nc 8 2
!
!   Example script:
!      ##########################################################################
!      # Temporary python script for producing deposit time-series plots for Ash3d_PostProc
!      # Adjust to suit your needs.
!      # You will need the packages conda-forge, geopandas, matplotlib
!      ##########################################################################
!      import pandas as pd
!      import matplotlib.pyplot as plt
!      import numpy as np
!
!      data_file="depTS_0001.dat"
!      fig_name="depTS_0001.png"
!      title_plot="Cuernavaca, Mexico"
!      plt.title(title_plot)
!      ####################### OPEN ASH DATA FILE #######################
!      ## Open data file
!      df = pd.read_csv(data_file)
!      t_column = df.iloc[:, 0]
!      z_column = df.iloc[:, 1]
!
!      ############################## PLOT ######################################
!      ## Create figure
!      main_fig = plt.figure(figsize=(4, 3))
!      ax1 = main_fig.add_subplot(4,1,(1,3))
!      plt.plot(t_column, z_column, color='grey') # Plot the line
!      plt.fill_between(t_column, z_column, color='grey', alpha=0.7)
!      ax1.set(xlim=(0,          25 ), ylim=(0,           1 ))
!      ax1.set_xlabel('Time (hours after eruption)   ')
!      ax1.set_ylabel('Deposit (mm)                   ')
!      main_fig.tight_layout()
!      plt.title(title_plot)
!      main_fig.savefig(f'depTS_0001.png',dpi=100)
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_DepPOI_TS_PNG_python(pt_indx)

      use Output_Vars,   only : &
         THICKNESS_THRESH

      use Airports,      only : &
         Airport_Name,Airport_Thickness_TS

      use io_data,       only : &
         nWriteTimes,WriteTimes

      use time_data,     only : &
         Simtime_in_hours

      integer,intent(in) :: pt_indx

      real(kind=dp) :: ymaxpl
      character(len=40) :: title_plot
      character(len=10) :: filename_root
      character(len=14) :: filename_script
      character(len=14) :: filename_outdata
      character(len=14) :: filename_png
      integer           :: i
      character(len=25) :: plotcom
      integer,save      :: plot_index = 0
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      character(len=200):: cmd
      integer,parameter :: fid_outdata  = 54
      integer,parameter :: fid_script   = 55


      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_DepPOI_TS_PNG_python"
      endif;enddo

      if(Airport_Thickness_TS(pt_indx,nWriteTimes) < THICKNESS_THRESH)then
        return
      else
        plot_index = plot_index + 1
      endif

      write(filename_root,52)plot_index
 52   format('depTS_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".py"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      open(unit=fid_outdata,file=filename_outdata,status='replace')
      write(fid_outdata,*)'Time                   ,  Deposit         '
      do i = 1,nWriteTimes
        write(fid_outdata,*)WriteTimes(i),', ',Airport_Thickness_TS(pt_indx,i)
      enddo
      close(fid_outdata)

      if(Airport_Thickness_TS(plot_index,nWriteTimes) < THICKNESS_THRESH)then
        ymaxpl = 1.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes) < 1.0_dp)then
        ymaxpl = 1.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes) < 5.0_dp)then
        ymaxpl = 5.0_dp
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes) < 25.0_dp)then
        ymaxpl = 25.0_dp
      else
        ymaxpl = 100.0_dp
      endif
      title_plot = Airport_Name(pt_indx)

      ! Set up to plot via python script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary python script for producing deposit time-series plots for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"# You will need the packages conda-forge, geopandas, matplotlib"
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"import pandas as pd"
      write(fid_script,'(g0)')"import matplotlib.pyplot as plt"
      write(fid_script,'(g0)')"import numpy as np"
      write(fid_script,'(g0)')" "
      cmd = 'data_file="' // trim(adjustl(filename_outdata)) // '"'
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = 'fig_name="' // trim(adjustl(filename_png)) // '"'
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = 'title_plot="' // trim(adjustl(title_plot)) // '"'
      write(fid_script,'(g0)')trim(adjustl(cmd))

      write(fid_script,'(g0)')'plt.title(title_plot)'

      cmd = "####################### OPEN ASH DATA FILE #######################"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "## Open data file"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "df = pd.read_csv(data_file)"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "t_column = df.iloc[:, 0]"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "z_column = df.iloc[:, 1]"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = " "
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "############################## PLOT ######################################"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "## Create figure"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "main_fig = plt.figure(figsize=(4, 3))"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "ax1 = main_fig.add_subplot(4,1,(1,3))"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "plt.plot(t_column, z_column, color='grey') # Plot the line"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "plt.fill_between(t_column, z_column, color='grey', alpha=0.7)"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      write(cmd,*)"ax1.set(xlim=(0,",ceiling(Simtime_in_hours),"), ylim=(0,", &
                               nint(ymaxpl),"))"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "ax1.set_xlabel('Time (hours after eruption)   ')"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "ax1.set_ylabel('Deposit (mm)                   ')"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "main_fig.tight_layout()"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "plt.title(title_plot)"
      write(fid_script,'(g0)')trim(adjustl(cmd))

      cmd = "main_fig.savefig(f'" // trim(adjustl(filename_png)) // "',dpi=100)"
      write(fid_script,'(g0)')trim(adjustl(cmd))

      write(plotcom,'(a11,a14)')'python ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      if(iostatus /= 0)then
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"WARNING: python command is returing a non-zero error code:", iostatus
          write(errlog(io),*)"         Maybe your python installation is incomplete"
          write(errlog(io),*)"         Make sure you install the following in your conda environment:"
          write(errlog(io),*)"           conda install -c conda-forge geopandas"
          write(errlog(io),*)"           conda install -c scitools cartopy"
          write(errlog(io),*)"           conda install -c conda-forge gdal"
          write(errlog(io),*)"         Then activate your environment:"
          write(errlog(io),*)"           conda create --name geo_env"
          write(errlog(io),*)"           conda activate geo_env"
        endif;enddo
        stop 1
      endif

      ! Clean up
      if (CleanScripts_python) then
        cmd = "rm -f depTS_*.dat depTS_*.py"
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_DepPOI_TS_PNG_python"
      endif;enddo

      return
      end subroutine write_DepPOI_TS_PNG_python

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      end module Ash3d_PostProc_python

!##############################################################################
