!##############################################################################
!
! Ash3d_PostProc_GMT module
!
! This module provides the subroutines that use GMT for creating 2d maps,
! 2d vertical profiles, and the little deposit accumulation plots linked to
! the airport arrival kml (ash_arrivaltimes_airports.kml).
! These subroutines create temporary script files that are run if GMT is
! installed on the local system.
!   https://www.generic-mapping-tools.org/
! Third party fortran API is available with gmt-fortran
!   https://github.com/GenericMappingTools/gmt-fortran
!
!      subroutine write_2Dmap_PNG_GMT
!      subroutine write_2Dprof_PNG_GMT
!      subroutine write_DepPOI_TS_PNG_GMT
!
!##############################################################################

      module Ash3d_PostProc_GMT

      use precis_param

      use io_units

      use global_param,  only : &
         EPS_SMALL

      use io_data,       only : &
         Instit_IconFile

#if USEGMT
      ! This is only for the experimental GMT API
      use gmt
#endif

      implicit none
      !implicit none (type, external)

        ! Set everything to private by default
      private

        ! Publicly available subroutines/functions
      public write_2Dmap_PNG_GMT,  &
             write_2Dprof_PNG_GMT, &
             write_DepPOI_TS_PNG_GMT

        ! Publicly available variables
      logical, public :: CleanScripts_GMT

      contains
      !------------------------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dmap_PNG_GMT
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    nx            = x length of output array OutVar
!    ny            = y length of output array OutVar
!    iprod         = product ID
!    itime         = time index from netcdf data file
!    OutVar        = 2-d array to be written to ASCII file
!    Fill_Value    = NaN value
!    writeContours = logical
!
!  This subroutine creates a png map of the variable in OutVar using the GMT
!  graphics package.  Annotations and contour levels are indicated via the
!  product ID (iprod).  If writeContours is set to true, then this subroutine
!  is only used for generating and storing the contours (for GMT, this is
!  through output files generated by the script) with no png written.
!  If timestep = -1, then use the last step in file
!
!  To invoke:
!   ASH3DPLOT=4 ./Ash3d_PostProc 3d_tephra_fall.nc 5 3
!
!   Example script:
!      #!/bin/bash
!      ##########################################################################
!      # Temporary GMT script for producing 2d maps for Ash3d_PostProc
!      # Adjust to suit your needs.
!      ##########################################################################
!      gmt gmtset PS_MEDIA=letter
!      gmt gmtset PROJ_ELLIPSOID Sphere
!      gmt psbasemap -X1.5i -Y2i -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Ba2 -B+t"Final Deposit Thickness (mm)     " -K > temp.ps
!      gmt pscoast -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Dh -G220/220/220 -W  -K -O >> temp.ps
!      gmt xyz2grd outvar.dat -R260.025/17.513/264.975/264.975/20.987r -I0.050d0.025d -Gout.grd
!      echo "        0.01000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,214/222/105 -K -O >> temp.ps
!      echo "        0.03000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,249/167/113 -K -O >> temp.ps
!      echo "        0.10000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,128/0/128 -K -O >> temp.ps
!      echo "        0.30000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,0/0/255 -K -O >> temp.ps
!      echo "        1.00000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,0/128/255 -K -O >> temp.ps
!      echo "        3.00000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,0/255/128 -K -O >> temp.ps
!      echo "       10.00000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,195/195/0 -K -O >> temp.ps
!      echo "       30.00000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,255/128/0 -K -O >> temp.ps
!      echo "      100.00000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,255/0/0 -K -O >> temp.ps
!      echo "      300.00000   C" > c.lev
!      gmt grdcontour out.grd -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Cc.lev -A- -W3,128/0/0 -K -O >> temp.ps
!      echo  -99.128   19.427 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -98.193   19.049 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -96.123   19.185 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -99.667   19.283 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -96.903   19.533 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -99.221   18.921 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -98.755   20.120 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -99.501   17.552 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo  -98.237   19.310 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      echo    0.000    0.000 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Sc0.05i -Gblack -Wthinnest -K -O >> temp.ps
!      gmt pstext cities.xy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -D0.1/0.1 -V -K -O >> temp.ps
!      echo  -98.622   19.023 '1.0' | gmt psxy -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -St0.1i -Gmagenta -Wthinnest -K -O >> temp.ps
!      gmt pslegend leg1.txt -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Dx-1.0i/-1.5i/3.0i/1.0i/BL -K -O >> temp.ps
!      gmt pslegend leg2.txt -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Dx2.0i/-1.5i/4.0i/1.0i/BL -K -O >> temp.ps
!      gmt pslegend leg3.txt -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Dx6.0i/-2.3i/2.0i/1.0i/BL -K -O >> temp.ps
!      gmt pslegend leg4.txt -R260.000/17.500/265.000/21.000r -JM-98.622/19.023/7.0i -Dx8.0i/2.0i/1.25i/2.5i/BL -F -O >> temp.ps
!      gmt psconvert temp.ps -A -Tg
!      convert temp.png -resize 850x600 -alpha off temp.png
!      mv temp.png Ash3d_Deposit____final.png
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dmap_PNG_GMT(nx,ny,iprod,itime,OutVar,Fill_Value,writeContours)

      use mesh,          only : &
         IsLatLon,lon_cc_pd,lat_cc_pd,de,dn, &
         dx,dy,                              &
         latLL,lonLL,latUR,lonUR,            &
         xLL,yLL,xUR,yUR,                    &
         A3d_iprojflag,A3d_lam0,A3d_phi0,A3d_phi1,A3d_phi2,A3d_k0,A3d_Re

      use Output_Vars,   only : &
         ContourFilled, &
         Con_Cust,Con_Cust_N,Con_Cust_RGB,Con_Cust_Lev,&
         Con_DepThick_mm_N,Con_DepThick_mm_Lev,Con_DepThick_mm_RGB, &
         Con_DepThick_in_N,Con_DepThick_in_Lev,Con_DepThick_in_RGB, &
         Con_DepTime_N,Con_DepTime_Lev,Con_DepTime_RGB, &
         Con_CloudCon_N,Con_CloudCon_Lev,Con_CloudCon_RGB, &
         Con_CloudTop_N,Con_CloudTop_RGB,Con_CloudTop_Lev, &
         Con_CloudBot_N,Con_CloudBot_RGB,Con_CloudBot_Lev, &
         Con_CloudLoad_N,Con_CloudLoad_RGB,Con_CloudLoad_Lev, &
         Con_CloudRef_N,Con_CloudRef_RGB,Con_CloudRef_Lev, &
         Con_CloudTime_N,Con_CloudTime_RGB,Con_CloudTime_Lev, &
         ContourDataX,ContourDataY,ContourDataNcurves,ContourDataNpoints,&
         CloudArrivalTime,Mask_Deposit,Mask_Cloud,&
         CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS,ContourLev,nConLev

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap

      use io_data,       only : &
         WriteTimes,cdf_b3l1,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight,lon_volcano,lat_volcano

      use citywriter

      use Ash3d_ASCII_IO,  only : &
           write_2D_ASCII

      use projection,    only : &
           PJ_proj_inv

      integer      ,intent(in) :: nx
      integer      ,intent(in) :: ny
      integer      ,intent(in) :: iprod
      integer      ,intent(in) :: itime
      real(kind=ip),intent(in) :: OutVar(nx,ny)
      real(kind=ip),intent(in) :: Fill_Value
      logical      ,intent(in) :: writeContours

      logical            :: mask(nx,ny)
      character(len=6)   :: Fill_Value_str
      character(len=200) :: cmd

      integer :: ii,jj
      real(kind=ip) :: tmp_ip
      integer,dimension(:,:),allocatable :: zrgb
      character(len=40) :: title_plot
      !character(len=30) :: cstr_xlabel = 'Longitude'
      !character(len=30) :: cstr_ylabel = 'Latitude'
      character(len=30) :: cstr_zlabel
      character(len=30) :: cstr_volcname
      character(len=30) :: cstr_run_date
      character(len=30) :: cstr_windfile
      character(len=40) :: cstr_ErStartT
      character(len=27) :: cstr_ErHeight
      character(len=30) :: cstr_ErDuratn
      character(len=38) :: cstr_ErVolume
      character(len=45) :: cstr_note
      character(len=20) :: varname
      character(len= 9) :: cio
      character(len= 4),parameter :: outfile_ext = '.png'
      character(len=10) :: units
      integer           :: ioerr
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      integer           :: iw,iwf
      logical           :: IsThere1
      logical           :: HaveIconFile
      character(len=80) :: linebuffer080
      character         :: testkey

      ! Plot dimensions
      real(kind=ip)  :: xmin
      real(kind=ip)  :: xmax
      real(kind=ip)  :: ymin
      real(kind=ip)  :: ymax
      logical        :: IsRegGrid

      ! Aux. File names
      character(len= 8) :: filename_root
      character(len=10) :: filename_script
      character(len=10) :: filename_outdata
      character(len=40) :: filename_png
      character(len=10) :: filename_contourdata
      !character(len=80) :: filename_coastline
      character(len=16) :: filename_ps

      ! Citywriter variables
      integer :: icty
      integer :: ncities
!      integer :: cityname_offset_px = 30
      real(kind=ip),dimension(:),allocatable     :: lon_cities
      real(kind=ip),dimension(:),allocatable     :: lat_cities
      character (len= 26),dimension(:),allocatable :: name_cities

      ! Contour variables
      integer           :: substr_pos1  ! for parsing contour text files
      integer           :: ilev         ! number of contour levels
      integer           :: icurve       ! number of curves for level ilev
      integer           :: npts         ! number of points in curve ilev,icurve

      ! Plotting variables
      real(kind=ip)  :: plotw
      real(kind=ip)  :: ploth
      real(kind=ip)  :: asprat

      ! GMT variables
      character(len=25) :: plotcom
      character(len=20),dimension(25) :: penstr
      character(len=80),dimension(25) :: legpenstr
      character(len=17) :: dumstr17
!      character(len=48) :: dumstr48
      character(len=10) :: flt_str
      character(len=50) :: base_str
      character(len=60) :: title_str
      character(len=4 ) :: detail_str
      character(len=50) :: proj_str
      character(len=50) :: projX_str
      character(len=50) :: area_str
      character(len=50) :: area2_str
      character(len=50) :: coast_str
      character(len=50) :: river_str
      character(len=50) :: start_ps
      character(len=50) :: contn_ps
      character(len=50) :: incr_str
      character(len=50) :: end_ps

      real(kind=dp)     :: olam,ophi

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8  ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dmap_PNG_GMT"
      endif;enddo

      ! Initialization
      filename_ps  = "temp.ps"
      plotw  = 7.0_ip


      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)
      ! Assume coastline file is present if gmt is installed

      ncities = 20
      allocate(lon_cities(ncities))
      allocate(lat_cities(ncities))
      allocate(name_cities(ncities))

      filename_root        = "outvar"
      filename_outdata     = trim(adjustl(filename_root)) // ".dat"
      filename_script      = trim(adjustl(filename_root)) // ".gmt"
      filename_contourdata = trim(adjustl(filename_root)) // ".con"


      if(iprod == 5.or.iprod == 6)then
        cio='____final'
      else
        if (WriteTimes(itime) < 10.0_ip) then
          write(cio,1) WriteTimes(itime)
1         format('00',f4.2,'hrs')
        elseif (WriteTimes(itime) < 100.0_ip) then
          write(cio,2) WriteTimes(itime)
2         format('0',f5.2,'hrs')
        else
          write(cio,3) WriteTimes(itime)
3         format(f6.2,'hrs')
        endif
      endif

      if(Con_Cust)then
        nConLev = Con_Cust_N
        allocate(zrgb(nConLev,3))
        allocate(ContourLev(nConLev))
        ContourLev(1:nConLev) = Con_Cust_Lev(1:nConLev)
        zrgb(1:nConLev,1:3) = Con_Cust_RGB(1:nConLev,1:3)
      endif

      if(iprod == 3)then       ! deposit at specified times (mm)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 4)then   ! deposit at specified times (inches)
        varname = "depothick"
        write(filename_png,'(a15,a9,a4)')'Ash3d_Deposit_t',cio,outfile_ext
        write(title_plot,'(a20,f7.2,a6)')'Deposit Thickness t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 5)then       ! deposit at final time (mm)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        cstr_zlabel = 'Dep.Thick.(mm)'
        units = " (mm)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_mm_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_mm_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_mm_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 6)then   ! deposit at final time (inches)
        varname = "depothickFin"
        write(filename_png,'(a13,a9,a4)')'Ash3d_Deposit',cio,outfile_ext
        title_plot = 'Final Deposit Thickness'
        cstr_zlabel = 'Dep.Thick.(in)'
        units = " (in)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepThick_in_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepThick_in_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepThick_in_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 7)then   ! ashfall arrival time (hours)
        varname = "depotime"
        write(filename_png,'(a22)')'DepositArrivalTime.png'
        write(title_plot,'(a20)')'Ashfall arrival time'
        cstr_zlabel = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_DepTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_DepTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_DepTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 8)then   ! ashfall arrival at airports/POI (mm)
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for airport arrival time data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_GMT"
        endif;enddo
        stop 1
      elseif(iprod == 9)then   ! ash-cloud concentration
        varname = "ashcon_max"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudCon_t',cio,outfile_ext
        write(title_plot,'(a26,f7.2,a6)')'Ash-cloud concentration t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Max.Con.(mg/m3)'
        units = " (mg/m3)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudCon_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudCon_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudCon_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 10)then   ! ash-cloud height
        varname = "cloud_height"
        write(filename_png,'(a19,a9,a4)')'Ash3d_CloudHeight_t',cio,outfile_ext
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud height t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Height(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTop_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTop_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTop_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 11)then   ! ash-cloud bottom
        varname = "cloud_bottom"
        write(filename_png,'(a16,a9,a4)')'Ash3d_CloudBot_t',cio,outfile_ext
        write(title_plot,'(a19,f7.2,a6)')'Ash-cloud bottom t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Bot.(km)'
        units = " (km)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudBot_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudBot_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudBot_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 12)then   ! ash-cloud load
        varname = "cloud_load"
        write(filename_png,'(a17,a9,a4)')'Ash3d_CloudLoad_t',cio,outfile_ext
        write(title_plot,'(a17,f7.2,a6)')'Ash-cloud load t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Load(T/km2)'
        units = " (T/km2)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudLoad_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudLoad_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudLoad_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 13)then  ! radar reflectivity
        varname = "radar_reflectivity"
        write(filename_png,'(a20,a9,a4)')'Ash3d_CloudRadRefl_t',cio,outfile_ext
        write(title_plot,'(a24,f7.2,a6)')'Ash-cloud radar refl. t=',WriteTimes(itime),' hours'
        cstr_zlabel = 'Cld.Refl.(dBz)'
        units = " (dBz)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudRef_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudRef_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudRef_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 14)then   ! ashcloud arrival time (hours)
        varname = "ash_arrival_time"
        write(filename_png,'(a20)')'CloudArrivalTime.png'
        write(title_plot,'(a22)')'Ash-cloud arrival time'
        cstr_zlabel = 'Time (hours)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = Con_CloudTime_N
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev(1:nConLev) = Con_CloudTime_Lev(1:nConLev)
          zrgb(1:nConLev,1:3) = Con_CloudTime_RGB(1:nConLev,1:3)
        endif
      elseif(iprod == 15)then   ! topography
        varname = "topography"
        write(filename_png,'(a14)')'Topography.png'
        write(title_plot,'(a10)')'Topography'
        cstr_zlabel = 'Elevation (km)'
        units = " (hours)"
        Fill_Value_str = '-9999.'
        if(.not.Con_Cust)then
          nConLev = 8
          allocate(zrgb(nConLev,3))
          allocate(ContourLev(nConLev))
          ContourLev = [1.0_ip, 2.0_ip, 3.0_ip, 4.0_ip, &
                        5.0_ip, 6.0_ip, 7.0_ip, 8.0_ip]
        endif
      elseif(iprod == 16)then   ! profile plots
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"ERROR: No map PNG output option for vertical profile data."
          write(errlog(io),*)"       Should not be in write_2Dmap_PNG_GMT"
        endif;enddo
        stop 1
      else
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(errlog(io),*)"ERROR: unexpected variable"
          write(errlog(io),*)"         iprod = ",iprod
          write(errlog(io),*)"       Cannot map this variable."
        endif;enddo
        stop 1
      endif
      ! Now have string vars (varname,cstr_zlabel, etc.) and contour info (nConLev,zrgb,ContourLev)

      ! When we run this subroutine via a GMT script (as opposed to the API), we
      ! write out OutVar to an ESRI ASCII file to be read by the script
      ! Now mask out non-cloud values
      if(iprod == 10.or.&  ! CloudHeight
         iprod == 11)then  ! CloudHeightBot
        mask(1:nx,1:ny) = Mask_Cloud(1:nx,1:ny)
      elseif(iprod == 7)then  ! DepArrivalTime
        mask(1:nx,1:ny) = Mask_Deposit(1:nx,1:ny)
      elseif(iprod == 14)then
        ! cloud mask based on cloud load does not work in this case the cloud load mask
        ! is a function of time
        mask(1:nx,1:ny) = .true.
        do ii=1,nx
          do jj=1,ny
            if(CloudArrivalTime(ii,jj) < 0.0_ip)mask(ii,jj) = .false.
          enddo
        enddo
      else
        mask = .true.
      endif

      if(writeContours)then
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Running GMT to calculate contours lines"
        endif;enddo
      else
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Running GMT to generate contour plot"
        endif;enddo
      endif

      ! This is the section where we actually start plotting the map
      ! Evaluate grid
      if(IsLatLon)then
        if(lonUR-lonLL >= 360.0_ip)then
          lonLL = 0.0_ip
          lonUR = 360.0_ip
        endif
        xmin = lonLL
        xmax = lonUR
        ymin = latLL
        ymax = latUR
        asprat = (ymax-ymin)/(xmax-xmin)
        if(abs(dn-de) < 1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
      else
        xmin = xLL
        xmax = xUR
        ymin = yLL
        ymax = yUR
        asprat = (ymax-ymin)/(xmax-xmin)
        if(abs(dx-dy) < 1.0e-4_ip)then
          IsRegGrid = .true.
        else
          IsRegGrid = .false.
        endif
        call PJ_proj_inv(real(xmin,kind=dp), real(ymin,kind=dp),  &
                      A3d_iprojflag, A3d_lam0,A3d_phi0,A3d_phi1,A3d_phi2, &
                      A3d_k0,A3d_Re, &
                      olam,ophi)
        lonLL = real(olam,kind=ip)
        latLL = real(ophi,kind=ip)
        call PJ_proj_inv(real(xmax,kind=dp), real(ymax,kind=dp),  &
                      A3d_iprojflag, A3d_lam0,A3d_phi0,A3d_phi1,A3d_phi2, &
                      A3d_k0,A3d_Re, &
                      olam,ophi)
        lonUR = real(olam,kind=ip)
        latUR = real(ophi,kind=ip)
      endif

      ! write out the data in a form that GMT can read
      ! ESRI ASCII for reg grids, 3-column for irregular
      if(IsRegGrid)then
        ! If the grid is regular (dx=dy) then we can write an ESRI ASCII file and convert to grd
        ! via gmt grdconvert outvar.dat=ef out.grd
        varname = "outvar"
        call write_2D_ASCII(nx,ny,OutVar,mask,Fill_Value_str,varname)
      else
        ! Irregular grids are problematic, call special ASCII interpolator
        !call write_2D_ASCII_flt_regular(nx,ny,IsLatLon,real(xmin,kind=sp),real(ymin,kind=sp),.true., &
        !                   real(de,kind=sp),real(dn,kind=sp),Fill_Value_str,&
        !                   real(OutVar,kind=sp),filename_outdata)
        ! Alternatively, write out data in column format and have GMT handle it
!        write(filename_outdata,53) "outvar.dat"
        open(unit=fid_outdata,file=filename_outdata,status='replace')
        do ii = 1,nx
          do jj = 1,ny
            if(lon_cc_pd(1) < 180.0_ip)then
              tmp_ip = lon_cc_pd(ii)
            else
              tmp_ip = lon_cc_pd(ii)-360.0_ip
            endif
            if(abs(OutVar(ii,jj)-Fill_Value) < EPS_SMALL)then
              write(fid_outdata,*)tmp_ip,lat_cc_pd(jj),"NaN"
            else
              write(fid_outdata,*)tmp_ip,lat_cc_pd(jj),OutVar(ii,jj)
            endif
          enddo
        enddo
        close(fid_outdata)
      endif
      ! Finished temporary data file

      call citylist(1,                        &  ! 1 is for external file in GMT format
                    xmin,xmax,ymin,ymax,      &
                    ncities,                  &
                    lon_cities,               &
                    lat_cities,               &
                    name_cities)
      if(IsLatLon)then
        if(lon_volcano > xmax)lon_volcano=lon_volcano-360.0_ip
      endif
      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions > 1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'

      ! write contour pen specifications to strings
      do ilev=1,nConLev
        write(flt_str,'(i3)')zrgb(ilev,1)
        penstr(ilev)="-W3," // trim(adjustl(flt_str))
        legpenstr(ilev)="S 0.1i - 0.15i black 3.0p," // trim(adjustl(flt_str))
        write(flt_str,'(i3)')zrgb(ilev,2)
        penstr(ilev)= trim(penstr(ilev)) // "/" // trim(adjustl(flt_str))
        legpenstr(ilev)=trim(legpenstr(ilev)) // "/" // trim(adjustl(flt_str))
        write(flt_str,'(i3)')zrgb(ilev,3)
        penstr(ilev)= trim(penstr(ilev)) // "/" // trim(adjustl(flt_str))
        legpenstr(ilev)=trim(legpenstr(ilev)) // "/" // trim(adjustl(flt_str))
        write(flt_str,'(g10.3)')ContourLev(ilev)
        legpenstr(ilev)=trim(legpenstr(ilev)) // " 0.3i " // trim(adjustl(flt_str))
      enddo

      if(writeContours)then
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(outlog(io),*)"Running GMT to calculate contours lines"
        endif;enddo
        write(filename_png,'(a14)')'tmp.png'
        allocate(ContourDataNcurves(nConLev))
        allocate(ContourDataNpoints(nConLev,CONTOUR_MAXCURVES))
        allocate(ContourDataX(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        allocate(ContourDataY(nConLev,CONTOUR_MAXCURVES,CONTOUR_MAXPOINTS))
        ContourDataNcurves(:)   = 0
        ContourDataNpoints(:,:) = 0
        ContourDataX(:,:,:)     = 0.0_ip
        ContourDataY(:,:,:)     = 0.0_ip
      else
        do io=1,2;if(VB(io) <= verbosity_error)then
          write(outlog(io),*)"Running GMT to generate contour plot"
        endif;enddo
      endif

!      write(filename_contourdata,53) "outvar.con"
!      write(filename_script,53) "outvar.gmt"
! 53   format(a10)

      ! Set up to plot via GMT script
      open(unit=fid_script,file=filename_script,status='replace')

      ! Write annotations to several legends
      !  Left panel
      open(unit=fid_misc,file="leg1.txt",status='replace')
      linebuffer080 = "T " // trim(adjustl(cstr_volcname))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_run_date))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_windfile))
      write(fid_misc,'(g0)')linebuffer080
      close(fid_misc)

      !  Right panel
      open(unit=fid_misc,file="leg2.txt",status='replace')
      linebuffer080 = "T " // trim(adjustl(cstr_ErStartT))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_ErHeight))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_ErDuratn))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_ErVolume))
      write(fid_misc,'(g0)')linebuffer080
      close(fid_misc)

      if(HaveIconFile)then
        open(unit=fid_misc,file="leg3.txt",status='replace')
        write(fid_misc,'(g0)')"I " // trim(adjustl(Instit_IconFile)) // " 2i C"
        close(fid_misc)
      endif

      !  Contour legend
      open(unit=fid_misc,file="leg4.txt",status='replace')
      write(fid_misc,'(a7)')"C black"
      write(fid_misc,'(g0)')"H 12 1 " // trim(adjustl(cstr_zlabel))
      write(fid_misc,'(a3)')"N 1"
      do ilev=1,nConLev
        write(fid_misc,'(g0)')trim(adjustl(legpenstr(ilev)))
      enddo
      close(fid_misc)

      ! Start writing the gmt bits
      ! BASE string:
      if(lonUR-lonLL <= 2.0_ip)then
        base_str   = "-Ba0.25"
        detail_str = "-Dh"
      elseif(lonUR-lonLL <= 5.0_ip)then
        base_str   = "-Ba1"
        detail_str = "-Dh"
      elseif(lonUR-lonLL <= 10.0_ip)then
        base_str   = "-Ba2"
        detail_str = "-Dh"
      elseif(lonUR-lonLL <= 20.0_ip)then
        base_str   = "-Ba5"
        detail_str = "-Dh"
      elseif(lonUR-lonLL <= 40.0_ip)then
        base_str   = "-Ba10"
        detail_str = "-Dl"
      elseif(lonUR-lonLL <= 100.0_ip)then
        base_str   = "-Ba20"
        detail_str = "-Dl"
      else
        base_str    = "-Ba20"
        detail_str  = "-Dl"
      endif
      title_str = '-B+t"' // trim(adjustl(title_plot)) // units // '"'

      ! AREA string:    AREA="-R$lonmin/$lonmax/$latmin/$latmax"
      area_str = " -R"
      write(flt_str,'(f8.3)')lonLL
      area_str = trim(area_str) // trim(adjustl(flt_str))
      write(flt_str,'(f8.3)')latLL
      area_str = trim(area_str) // "/" // trim(adjustl(flt_str))
      write(flt_str,'(f8.3)')lonUR
      area_str = trim(area_str) // "/" // trim(adjustl(flt_str))
      write(flt_str,'(f8.3)')latUR
      area_str = trim(area_str) // "/" // trim(adjustl(flt_str)) // "r"
      area2_str = " -R"
      if(IsLatLon)then
        if(lonUR-lonLL <= 100.0_ip)then
          write(flt_str,'(f8.3)')lonLL+de*0.5_ip
          area2_str = trim(area2_str) // trim(adjustl(flt_str))
          write(flt_str,'(f8.3)')latLL+dn*0.5_ip
          area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f8.3)')lonUR-de*0.5_ip
          area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str))
        else
          write(flt_str,'(f8.3)')0.0_sp
          area2_str = trim(area2_str) // trim(adjustl(flt_str))
          write(flt_str,'(f8.3)')latLL+dn*0.5_ip
          area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f8.3)')360.0_sp
          area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str))
        endif
        write(flt_str,'(f8.3)')lonUR-de*0.5_ip
        area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str))
        write(flt_str,'(f8.3)')latUR-dn*0.5_ip
        area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str)) // "r"
        ! Increment string:-I0.263d/0.127d
        incr_str = " -I"
        write(flt_str,'(f8.3)')de
        incr_str = trim(incr_str) // trim(adjustl(flt_str)) // "d"
        write(flt_str,'(f8.3)')dn
        incr_str = trim(incr_str) // trim(adjustl(flt_str)) // "d"
      else
        write(flt_str,'(f8.3)')lonLL+dx*0.5_ip
        area2_str = trim(area2_str) // trim(adjustl(flt_str))
        write(flt_str,'(f8.3)')latLL+dy*0.5_ip
        area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str))
        write(flt_str,'(f8.3)')lonUR-dx*0.5_ip
        area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str))
        write(flt_str,'(f8.3)')latUR-dy*0.5_ip
        area2_str = trim(area2_str) // "/" // trim(adjustl(flt_str)) // "r"
        ! Increment string:-I0.263d/0.127d
        incr_str = " -I"
        write(flt_str,'(f8.3)')dx
        incr_str = trim(incr_str) // trim(adjustl(flt_str)) // "d"
        write(flt_str,'(f8.3)')dy
        incr_str = trim(incr_str) // trim(adjustl(flt_str)) // "d"
      endif

      ploth = plotw*asprat

      if (IsLatLon) then
        ! For lon/lat grids, default to a Mercator projection
        ! PROJ string:    PROJ="-JM${VCLON}/${VCLAT}/20"
        if(lonUR-lonLL <= 100.0_ip)then
          proj_str = " -JM"
        else
          proj_str = " -JQ"
        endif
        write(flt_str,'(f8.3)')lon_volcano
        proj_str = trim(proj_str) // trim(adjustl(flt_str))
        write(flt_str,'(f8.3)')lat_volcano
        proj_str = trim(proj_str) // "/" // trim(adjustl(flt_str))
        write(flt_str,'(f3.1)')plotw
        proj_str = trim(proj_str) // "/" // trim(adjustl(flt_str)) // "i"
      else
        select case (A3d_iprojflag)
        case(0)
          ! Non-geographic projection, (x,y) only
          proj_str = " -JX"
          write(flt_str,'(f3.1)')plotw
          proj_str = trim(proj_str) // trim(adjustl(flt_str)) // "i/"
          write(flt_str,'(f3.1)')ploth
          proj_str = trim(proj_str) // trim(adjustl(flt_str)) // "i"
        case(1)
          ! Polar stereographic
          ! e.g.  -JS-135/90/7i"
          proj_str= " -JS"
          write(flt_str,'(f8.1)')A3d_lam0
          proj_str=trim(proj_str) // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi0
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f3.1)')plotw
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str)) // "i"
        case(2)
          ! Albers Equal Area
          ! e.g.  -JB198.475/20.0/12c
          proj_str= " -JB"
          write(flt_str,'(f8.1)')A3d_lam0
          proj_str=trim(proj_str) // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi0
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi1
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi2
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f3.1)')plotw
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str)) // "i"
        case(3)
          ! UTM
        case(4)
          ! Lambert conformal conic
          ! e.g.  -JM198.475/20.0/12c
          proj_str= " -JL"
          write(flt_str,'(f8.1)')A3d_lam0
          proj_str=trim(proj_str) // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi0
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi1
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi2
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f3.1)')plotw
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str)) // "i"
        case(5)
          ! Mercator
          ! e.g.  -JM198.475/20.0/12c
          proj_str= " -JM"
          write(flt_str,'(f8.1)')A3d_lam0
          proj_str=trim(proj_str) // trim(adjustl(flt_str))
          write(flt_str,'(f8.1)')A3d_phi0
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str))
          write(flt_str,'(f3.1)')plotw
          proj_str=trim(proj_str) // "/" // trim(adjustl(flt_str)) // "i"
        case default
          ! No projection code provided, use non-geographic projection, (x,y) only
          proj_str = " -JX"
          write(flt_str,'(f3.1)')plotw
          proj_str = trim(proj_str) // trim(adjustl(flt_str)) // "i/"
          write(flt_str,'(f3.1)')ploth
          proj_str = trim(proj_str) // trim(adjustl(flt_str)) // "i"
        end select

        ! This is the xy grid for contours that will be overlain on the lon/lat grid
        projX_str = " -JX"
        write(flt_str,'(f3.1)')plotw
        projX_str = trim(projX_str) // trim(adjustl(flt_str)) // "i/"
        write(flt_str,'(f3.1)')ploth
        projX_str = trim(projX_str) // trim(adjustl(flt_str)) // "i"
      endif

      ! COAST string
      coast_str = " -G220/220/220 -W"

      ! RIVER string
      !if()then ! small domain, include rivers
      !  river_str = " -I1/1p,blue -I2/0.25p,blue"
      !else
        river_str = ""
      !endif

      ! Initial pscoast command to start the ps file
      start_ps = "-K > "     // trim(adjustl(filename_ps))
      contn_ps = "-K -O >> " // trim(adjustl(filename_ps))
      end_ps   = "-O >> "    // trim(adjustl(filename_ps))

      ! Set up to plot via GMT script
      write(fid_script,'(g0)')'#!/bin/bash'
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary GMT script for producing 2d maps for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"gmt gmtset PS_MEDIA=letter"
      if(.not.writeContours)write(fid_script,'(g0)')'gmt gmtset PROJ_ELLIPSOID Sphere'
      cmd = 'gmt psbasemap -X1.5i -Y2i'  // " " // &
              trim(adjustl(area_str))    // " " // &
              trim(adjustl(proj_str))    // " " // &
              trim(adjustl(base_str))    // " " // &
              trim(adjustl(title_str))   // " " // &
              trim(adjustl(start_ps))
      if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))

      cmd = "gmt pscoast"               // " " // &
              trim(adjustl(area_str))   // " " // &
              trim(adjustl(proj_str))   // " " // &
              trim(adjustl(detail_str)) // " " // &
              trim(adjustl(coast_str))  // " " // &
              trim(adjustl(river_str))  // " " // &
              trim(adjustl(contn_ps))
      if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Get grid to contour, converting the ASCII file generated above
      ! We need this line regardless of if we are just making contours or not
      if(IsRegGrid)then
        cmd = "gmt grdconvert " // trim(adjustl(filename_outdata)) // "=ef out.grd"
      else
        cmd = "gmt xyz2grd " // trim(adjustl(filename_outdata)) // " " // &
              trim(adjustl(area2_str)) // " " // &
              trim(adjustl(incr_str))   // " " // &
              trim(adjustl(" -Gout.grd"))
      endif
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! write contour
      if(ContourFilled)then
        ! Filled contours not yet implemented
      else
        !gmt grdcontour out.grd $AREA $PROJ $BASE -Cdpm_1.lev    -A- -W3,0/128/255   -O -K >> temp.ps
        do ilev=1,nConLev
          write(fid_script,'(a6,f15.5,a13)')'echo "',real(ContourLev(ilev),kind=4), '   C" > c.lev'


          if(writeContours)then
            ! write contours to files
            write(filename_contourdata,54) "out",ilev,".con"
 54         format(a3,i0.2,a4)  ! write contour file name with level zero-padded
            !gmt grdcontour out.grd $AREA $PROJ $BASE -Cc.lev    -A- -W3,0/128/255 -Dcfile.xyz
!            write(fid_script,*)'echo "',real(ContourLev(i),kind=4), '   C" > c.lev'

            if (IsLatLon) then
              cmd = "gmt grdcontour out.grd"      // " " // &
                      trim(adjustl(area_str))     // " " // &
                      trim(adjustl(proj_str))     // " " // &
                      "-Cc.lev -A-"               // " " // &
                      trim(adjustl(penstr(ilev))) // " " // &
                      "-D"                        // &
                      trim(adjustl(filename_contourdata))
            else
              cmd = "gmt grdcontour out.grd"      // " " // &
                      trim(adjustl(projX_str))    // " " // &
                      "-Cc.lev -A-"               // " " // &
                      trim(adjustl(penstr(ilev))) // " " // &
                      "-D"                        // &
                      trim(adjustl(filename_contourdata))
            endif
            write(fid_script,'(g0)')trim(adjustl(cmd))
          else
            if (IsLatLon) then
              cmd = "gmt grdcontour out.grd"      // " " // &
                      trim(adjustl(area_str))     // " " // &
                      trim(adjustl(proj_str))     // " " // &
                      "-Cc.lev -A-"               // " " // &
                      trim(adjustl(penstr(ilev))) // " " // &
                      trim(adjustl(contn_ps))
            else
              cmd = "gmt grdcontour out.grd"      // " " // &
                      trim(adjustl(projX_str))    // " " // &
                      "-Cc.lev -A-"               // " " // &
                      trim(adjustl(penstr(ilev))) // " " // &
                      trim(adjustl(contn_ps))
            endif
            write(fid_script,'(g0)')trim(adjustl(cmd))
          endif
        enddo
      endif

      ! Add cities.
      do icty=1,ncities
        write(dumstr17,'(f8.3,1x,f8.3)')lon_cities(icty),lat_cities(icty)
        cmd = "echo " // dumstr17 // " '1.0' | gmt psxy " // &
                trim(adjustl(area_str))        // " " // &
                trim(adjustl(proj_str))        // " " // &
                "-Sc0.05i -Gblack -Wthinnest"  // " " // &
                trim(adjustl(contn_ps))
        if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))
      enddo
      cmd = "gmt pstext cities.xy " // &
              trim(adjustl(area_str))  // " " // &
              trim(adjustl(proj_str))  // " " // &
              "-D0.1/0.1 -V"           // " " // &
              trim(adjustl(contn_ps))
      ! cities.xy has the following format for each line:
      !     -99.1276   19.4270  10  0  9  BL    Mexico City
      ! if this file doesn't exist for some reason, we should write equivalent commands
      ! to the script
      inquire( file="cities.xy", exist=IsThere1)
      if(IsThere1)then
        if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))
      endif

      ! Last gmt command is to plot the volcano and close out the ps file
      ! echo $VCLON $VCLAT '1.0' | ${GMTpre[GMTv]} psxy $AREA $PROJ -St0.1i -Gblack -Wthinnest -O >> temp.ps
      write(dumstr17,'(f8.3,1x,f8.3)')lon_volcano,lat_volcano
      cmd = "echo " // dumstr17 // " '1.0' | gmt psxy " // &
              trim(adjustl(area_str))  // " " // &
              trim(adjustl(proj_str))  // " " // &
              "-St0.1i -Gmagenta -Wthinnest " // &
              trim(adjustl(contn_ps))
      if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Add descriptive footer here
      !gmt pslegend leg1.txt -R-134.500/-97.500/33.500/52.500  -JM-122.117/42.933/7i -Dx-1.0i/-1.5i/3.0i/1.0i/BL -K -O  >> temp.ps
      cmd = "gmt pslegend leg1.txt"   // " " // &
              trim(adjustl(area_str)) // " " // &
              trim(adjustl(proj_str)) // " " // &
              "-Dx-1.0i/-1.5i/3.0i/1.0i/BL " // &
              trim(adjustl(contn_ps))
      if(.not.writeContours)write(fid_script,'(g0)') trim(adjustl(cmd))

      !gmt pslegend leg2.txt -R-134.500/-97.500/33.500/52.500  -JM-122.117/42.933/7i -Dx2.0i/-1.5i/4.0i/1.0i/BL -K -O  >> temp.ps
      cmd = "gmt pslegend leg2.txt"   // " " // &
              trim(adjustl(area_str)) // " " // &
              trim(adjustl(proj_str)) // " " // &
              "-Dx2.0i/-1.5i/4.0i/1.0i/BL "  // &
              trim(adjustl(contn_ps))
      if(.not.writeContours)write(fid_script,'(g0)') trim(adjustl(cmd))

      !gmt pslegend leg3.txt -R-134.500/-97.500/33.500/52.500  -JM-122.117/42.933/7i -Dx6.0i/-2.3i/2.0i/1.0i/BL -K -O  >> temp.ps
      inquire( file="leg3.txt", exist=IsThere1)
      if(IsThere1)then
        cmd = "gmt pslegend leg3.txt"        // " " // &
                trim(adjustl(area_str))      // " " // &
                trim(adjustl(proj_str))      // " " // &
                "-Dx6.0i/-2.3i/2.0i/1.0i/BL" // " " // &
                trim(adjustl(contn_ps))
        if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))
      endif
      ! Add contour legend here
      cmd = "gmt pslegend leg4.txt"     // " " // &
              trim(adjustl(area_str))   // " " // &
              trim(adjustl(proj_str))   // " " // &
              "-Dx8.0i/2.0i/1.25i/2.5i/BL -F " // &
              trim(adjustl(end_ps))
      if(.not.writeContours)write(fid_script,'(g0)')  trim(adjustl(cmd))

      !gmt pslegend leg4.txt -R-134.500/-97.500/33.500/52.500  -JM-122.117/42.933/7i -Dx8.0i/2.0i/1.25i/2.5i/BL -F -O  >> temp.ps

      ! This command converts temp.ps to temp.png
      cmd = "gmt psconvert temp.ps -A -Tg"
      if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Might need to add this check in the GMT script on version 5 vs 6 (5 needs rotation)
      !GMTv=`gmt --version | cut -c1`
      !if [ $GMTv -eq 5 ] ; then
      !  convert -rotate 90 temp.png -resize 630x500 -alpha off temp.gif
      !if [ $GMTv -eq 5 ] ; then
      cmd = "convert temp.png -resize 850x600 -alpha off temp.png"
      if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Move this png to the final filename
      cmd = "mv temp.png " // filename_png
      if(.not.writeContours)write(fid_script,'(g0)')trim(adjustl(cmd))

      close(fid_script)
      write(plotcom,'(a3,a14)')'sh ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      ! Clean up
      if (CleanScripts_GMT) then
        cmd = "rm -f gmt.conf c.lev out.grd temp.ps leg*.txt outvar.dat outvar.gmt cities.xy gmt.history gmt.conf"
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      ! GMT script has been run, now we need to read the contour lines if we want
      ! to write a shapefile
      do io=1,2;if(VB(io) <= verbosity_info)then
        write(outlog(io),*)'Finished running GMT script. Now processing contour files if necessary.'
      endif;enddo

      if(writeContours)then
        ContourDataNcurves(:) = 0
        do ilev=1,nConLev
          write(filename_contourdata,54) "out",ilev,".con"
          ! Read filename_contourdata
          do io=1,2;if(VB(io) <= verbosity_info)then
            write(outlog(io),*)"Now trying to read contour file and loading contour data.",&
                trim(adjustl(filename_contourdata))
          endif;enddo
          inquire( file=trim(adjustl(filename_contourdata)), exist=IsThere1)
          if(IsThere1)then
            open(unit=fid_contourdata,file=filename_contourdata,status='old')
          else
            ! File does not exist; try next contour level
            cycle
          endif
        ! In the GMT contour files, all contours of a have a header in the following
        ! format:
        !> 0.01 contour -Z0.01
        ! Each curve for that level is separated by a line containing '>'

        read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
        do while(iostatus >= 0)
          ! Check if this is a header line
          read(linebuffer080,*,iostat=ioerr,iomsg=iomessage)testkey
          if(ioerr < 0)then
            ! If reading one character fails, then there is a blank line
            ! shouldn't happen with  GMT v 5 or 6
            ! Log zero contours for this level
            ioerr = -1
            ContourDataNcurves(ilev) = 0
            do io=1,2;if(VB(io) <= verbosity_debug2)then
              write(outlog(io),*)'  File exists, but has no content. Setting ncurves for this level to 0.'
            endif;enddo
            cycle

          elseif(testkey == '>')then
            ! This is a header line
            !   n it will have this format:> 0.03 contour -Z0.03
            substr_pos1 = index(linebuffer080,'contour')

            if(substr_pos1 == 0)then
              ! key > is present, but 'contour' is not
              read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
              cycle
            else
              ! Contours are all written to separate files
              ! Increment the number of curves for this level
              ContourDataNcurves(ilev) = ContourDataNcurves(ilev) + 1
              if(ContourDataNcurves(ilev) > CONTOUR_MAXCURVES)then
                do io=1,2;if(VB(io) <= verbosity_error)then
                  write(errlog(io),*)"ERROR: Maximum number of curves for this level exceeded by GMT"
                  write(errlog(io),*)"       Current maximum set to CONTOUR_MAXCURVES = ",CONTOUR_MAXCURVES
                  write(errlog(io),*)"       Please increase CONTOUR_MAXCURVES and recompile."
                  write(errlog(io),*)"  Output_Vars.f90:CONTOUR_MAXCURVES"
                endif;enddo
                stop 1
              endif
              icurve = ContourDataNcurves(ilev)
            endif
          else
            ! This is the data section
            ! Increment the number of points
            ContourDataNpoints(ilev,icurve) = ContourDataNpoints(ilev,icurve) + 1
            if(ContourDataNpoints(ilev,icurve) > CONTOUR_MAXPOINTS)then
              do io=1,2;if(VB(io) <= verbosity_error)then
                write(errlog(io),*)"ERROR: Maximum number of points for this curve exceeded by GMT"
                write(errlog(io),*)"       Current maximum set to CONTOUR_MAXPOINTS = ",CONTOUR_MAXPOINTS
                write(errlog(io),*)"       Please increase CONTOUR_MAXPOINTS and recompile."
                write(errlog(io),*)"  Output_Vars.f90:CONTOUR_MAXPOINTS"
              endif;enddo
              stop 1
            endif
            npts = ContourDataNpoints(ilev,icurve)
            read(linebuffer080,*,iostat=iostatus,iomsg=iomessage) &
                 ContourDataX(ilev,icurve,npts),ContourDataY(ilev,icurve,npts)
          endif

          ! Try to read the next line
          read(fid_contourdata,'(a80)',iostat=iostatus,iomsg=iomessage)linebuffer080
          enddo    ! iostatus >= 0
        close(unit=fid_contourdata)
        enddo    ! ilev=1,nConLev

        ! Loop through all the levels and curves and trim any curves with zero length
        do ilev=1,nConLev
          ! start at the last contour level
          icurve = CONTOUR_MAXCURVES + 1
          do ii = CONTOUR_MAXCURVES,1,-1
            if(ContourDataNpoints(ilev,ii) <= 0)then
              ! log each curve number with no points
              icurve = ii
            endif
          enddo
          ContourDataNcurves(ilev) = max(0,icurve-1)
        enddo
      endif


      ! This is a test section that uses the GMT API
      !character(16) filedat,filename_ps
      !character(200) cmd
      !
      !filedat="ex01-xy.dat"
      !filename_ps="ex01.ps"
      !
      !! create GMT session
      !call sGMT_Create_Session("Test")
      !
      !! call psxy
      !cmd="psxy "//trim(filedat)//" -JX16c/24c -R0/11/0/110 -Bx2+lx -By20+ly -BWS+tFig. -Sa1c -N -P ->"//trim(filename_ps)
      !call sGMT(cmd)
      !print *,trim(cmd)
      !
      !! call ps2raster
      !cmd="ps2raster "//trim(filename_ps)//" -Tg"
      !call sGMT(cmd)
      !print *,trim(cmd)
      !
      !! clean up
      !call sGMT_Destroy_Session()

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dmap_PNG_GMT"
      endif;enddo

      return

      end subroutine write_2Dmap_PNG_GMT

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_2Dprof_PNG_GMT
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    vprof_ID        = ID of the profile (number in list from Ash3d control file)
!
!  This subroutine creates a png plot of the transient vertical profile of ash
!  concentration above the profile point (vprof_ID) using the GMT graphics
!  package.
!
!  To invoke:
!   ASH3DPLOT=4 ./Ash3d_PostProc 3d_tephra_fall.nc 16 3
!
!   Example script:
!      #!/bin/bash
!      ##########################################################################
!      # Temporary GMT script for producing vertical profiles for Ash3d_PostProc
!      # Adjust to suit your needs.
!      ##########################################################################
!      gmt gmtset PS_MEDIA=letter
!      gmt makecpt -Cjet -T0/49.6/0.25 > my.cpt
!      gmt surface vprof_0001.dat -R0/25.000/0/14.800 -I0.250/ -Gout.grd
!      gmt grdmath out.grd 0 MAX = out.grd
!      gmt psbasemap -X3i -Y3i -R0/25.000/0/14.800 -JX5i/4i -B+t"Cuernavaca (lon= -99.26, lat= 18.83) " -K > temp.ps
!      gmt grdimage out.grd -Cmy.cpt  -R0/25.000/0/14.800 -JX5i/4i -Bxa2+l"Time (hours after eruption)" -Bya2+l"Height (km)" -BWS -K -O >> temp.ps
!      gmt psscale -Cmy.cpt -DDR+o1c/0c+w10c/0.5c -Baf+l"Ash conc. mg/m3" -J -R -X0.5i -Y0.0i -DJMR -K -O >> temp.ps
!      gmt pslegend leg1.txt -R0/25.000/0/14.800 -JX5i/4i -Dx-2.0i/-2.0i/3.0i/1.0i/BL -K -O >> temp.ps
!      gmt pslegend leg2.txt -R0/25.000/0/14.800 -JX5i/4i -Dx1.0i/-2.0i/4.0i/1.0i/BL -K -O >> temp.ps
!      gmt pslegend leg3.txt -R0/25.000/0/14.800 -JX5i/4i -Dx5.0i/-2.7i/2.0i/1.0i/BL -O >> temp.ps
!      gmt psconvert temp.ps -A -Tg
!      convert temp.png -resize 850x600 -alpha off temp.png
!      mv temp.png vprof_0001.png
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_2Dprof_PNG_GMT(vprof_ID)

      use global_param,  only : &
         KG_2_MG,KM3_2_M3

      use mesh,          only : &
         IsLatLon,nzmax,z_cc_pd

      use Output_Vars,   only : &
         pr_ash,CLOUDCON_THRESH

      use io_data,       only : &
         Site_vprofile,x_vprofile,y_vprofile,cdf_b3l1,VolcanoName

      use Source,        only : &
         neruptions,e_Volume,e_Duration,e_StartTime,e_PlumeHeight

      use time_data,     only : &
         os_time_log,SimStartHour,BaseYear,useLeap,ntmax,time_native

      integer,intent(in) :: vprof_ID

      logical            :: HaveIconFile
      character(len=76)  :: title_plot
      character(len=30)  :: cstr_xlabel
      character(len=30)  :: cstr_ylabel
      character(len=30)  :: cstr_zlabel
      character(len=30)  :: cstr_volcname
      character(len=30)  :: cstr_run_date
      character(len=30)  :: cstr_windfile
      character(len=40)  :: cstr_ErStartT
      character(len=27)  :: cstr_ErHeight
      character(len=30)  :: cstr_ErDuratn
      character(len=38)  :: cstr_ErVolume
      character(len=45)  :: cstr_note

      character(len=10)  :: filename_root
      character(len=14)  :: filename_script
      character(len=14)  :: filename_outdata
      character(len=14)  :: filename_png
      character(len=27)  :: coord_str
      character(len=80)  :: plotcom
      integer            :: i,k
      integer            :: iostatus
      integer            :: cstat
      character(len=120) :: iomessage
      integer            :: iw,iwf
      character(len= 80) :: linebuffer080
      !character(len=130) :: linebuffer130
      character(len=200) :: cmd
      integer,parameter  :: fid_script   = 55
      integer,parameter  :: fid_outdata  = 54

      ! Plotting variables
      real(kind=ip) :: tmin    , zmin    , cmin      ! graph minima
      real(kind=ip) :: tmax    , zmax    , cmax      ! graph maxima
      real(kind=ip) :: tlab1   , zlab1   , clab1     ! graph first label
      real(kind=ip) :: tlabstep, zlabstep, clabstep  ! graph label increment
      real(kind=ip) :: cloudcon_thresh_mgm3
      real(kind=ip)  :: dtg
      real(kind=ip)  :: dzg

      ! GMT variables
      character(len=8)  :: flt_str
      character(len=70) :: base_str
      character(len=50) :: title_str
      character(len=50) :: proj_str
      character(len=50) :: area_str
      character(len=50) :: start_ps
      character(len=50) :: contn_ps
      character(len=50) :: incr_str
      character(len=50) :: end_ps

      logical           :: IsThere1

      character(len=16)  :: filename_ps

      INTERFACE
        character (len=20) function HS_xmltime(HoursSince,byear,useLeaps)
          implicit none
          !implicit none (type, external)
          integer        ,parameter  :: dp        = 8  ! double precision
          real(kind=dp)  ,intent(in) :: HoursSince
          integer        ,intent(in) :: byear
          logical        ,intent(in) :: useLeaps
        end function HS_xmltime
      END INTERFACE

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_2Dprof_PNG_GMT"
      endif;enddo

      ! Initialization
      cstr_xlabel = 'Time (hours after eruption)'
      cstr_ylabel = 'Height (km)'
      cstr_zlabel = 'Ash conc. mg/m3'
      filename_ps  = "temp.ps"

      ! Test for icon file
      inquire( file=trim(adjustl(Instit_IconFile)), exist=HaveIconFile)

      ! Build strings with run info for legend
      ! Volcano:     Erup.start:
      ! Run date:    Plm Height:
      ! Windfile:    Duration:
      !              Volume:
      write(cstr_volcname,'(a10,a20)')'Volcano:  ' ,VolcanoName
      write(cstr_run_date,'(a10,a20)')'Run Date: ',os_time_log
      read(cdf_b3l1,*,iostat=iostatus,iomsg=iomessage) iw,iwf
      write(cstr_windfile,'(a10,i5)')'Windfile: ',iwf
      if(neruptions > 1)then
        write(cstr_note,'(a45)')'WARNING: Multiple eruptions, only first given'
      endif

      !e_StartTime,e_PlumeHeight,e_Duration,e_Volume
      write(cstr_ErStartT,'(a20,a20)')'Erup. Start Time:   ',&
            HS_xmltime(SimStartHour+e_StartTime(1),BaseYear,useLeap)
      write(cstr_ErHeight,'(a20,f4.1,a3)')'Erup. Plume Height: ',e_PlumeHeight(1),' km'
      write(cstr_ErDuratn,'(a20,f4.1,a6)')'Erup. Duration:     ',e_Duration(1),' hours'
      write(cstr_ErVolume,'(a20,f8.5,a10)')'Erup. Volume:       ',e_Volume(1),' km3 (DRE)'

      write(filename_root,52)vprof_ID
 52   format('vprof_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".gmt"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      ! Get min/max and label interval for all three axies.
      tmin=real(0,kind=ip)
      tmax=real(ceiling(time_native(ntmax)),kind=ip)
      tlab1    = 0.0_ip
      if(tmax > 240.0_ip)then
        tlabstep = 48.0_ip
      elseif(tmax > 120.0_ip)then
        tlabstep = 24.0_ip
      elseif(tmax > 30.0_ip)then
        tlabstep = 10.0_ip
      elseif(tmax > 15.0_ip)then
        tlabstep = 5.0_ip
      elseif(tmax > 6.0_ip)then
        tlabstep = 2.0_ip
      else
        tlabstep = 1.0_ip
      endif

      zmin=real(0,kind=ip)
      zmax=real(z_cc_pd(nzmax),kind=ip)
      zlab1    = 0.0_ip
      if(zmax > 30.0_ip)then
        zlabstep = 10.0_ip
      elseif(zmax > 15.0_ip)then
        zlabstep = 5.0_ip
      elseif(zmax > 6.0_ip)then
        zlabstep = 2.0_ip
      else
        zlabstep = 1.0_ip
      endif

      cloudcon_thresh_mgm3 = CLOUDCON_THRESH * KG_2_MG / KM3_2_M3  ! convert from kg/km3 to mg/m3
      cmin=real(0,kind=ip)
      cmax=real(maxval(pr_ash(:,:,vprof_ID)),kind=ip)    ! Get the max value for this profile
      cmin=real(min(cmin,cloudcon_thresh_mgm3),kind=ip)  ! Do not let cmax drop below the threshold
      if    (cmax > 4.0e4_ip)then
          clabstep = 5.0e3_ip
      elseif(cmax > 1.0e4_ip)then
          clabstep = 2.0e3_ip
      elseif(cmax > 4.0e3_ip)then
          clabstep = 5.0e2_ip
      elseif(cmax > 1.0e3_ip)then
          clabstep = 2.0e2_ip
      elseif(cmax > 4.0e2_ip)then
          clabstep = 5.0e1_ip
      elseif(cmax > 1.0e2_ip)then
          clabstep = 2.0e1_ip
      elseif(cmax > 4.0e1_ip)then
          clabstep = 5.0e0_ip
      elseif(cmax > 1.0e1_ip)then
          clabstep = 2.0e0_ip
      elseif(cmax > 1.0e0_ip)then
          clabstep = 5.0e-1_ip
      else
          clabstep = 1.0e-1_ip
      endif
      clab1    = 0.0_ip
      dtg = (tmax-tmin)/100.0_ip
      dzg = (zmax-zmin)/100.0_ip

      ! Prep data: GMT will load x y z data in column format
      open(unit=fid_outdata,file=filename_outdata,status='replace')
      do i = 1,ntmax
        do k = 1,nzmax
          write(fid_outdata,*)time_native(i),z_cc_pd(k),pr_ash(k,i,vprof_ID)
        enddo
        write(fid_outdata,'(g0)')""
      enddo
      close(fid_outdata)

      ! Build the plot title
      if(IsLatLon)then
        write(coord_str,101)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      else
        write(coord_str,102)x_vprofile(vprof_ID),y_vprofile(vprof_ID)
      endif
 101  format(' (lon=',f7.2,', lat=',f6.2,')')
 102  format(' (x=',f9.3,', y=',f9.3,')')
      write(title_plot,*)trim(adjustl(Site_vprofile(vprof_ID))),coord_str

      ! Write annotations to several legends
      !  Left panel
      open(unit=fid_misc,file="leg1.txt",status='replace')
      linebuffer080 = "T " // trim(adjustl(cstr_volcname))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_run_date))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_windfile))
      write(fid_misc,'(g0)')linebuffer080
      close(fid_misc)

      !  Right panel
      open(unit=fid_misc,file="leg2.txt",status='replace')
      linebuffer080 = "T " // trim(adjustl(cstr_ErStartT))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_ErHeight))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_ErDuratn))
      write(fid_misc,'(g0)')linebuffer080
      write(fid_misc,'(a5)')"G0.2i"
      linebuffer080 = "T " // trim(adjustl(cstr_ErVolume))
      write(fid_misc,'(g0)')linebuffer080
      close(fid_misc)

      if(HaveIconFile)then
        open(unit=fid_misc,file="leg3.txt",status='replace')
        write(fid_misc,'(g0)')"I " // trim(adjustl(Instit_IconFile)) // " 2i C"
        close(fid_misc)
      endif

      ! Set up to plot via GMT script
      open(unit=fid_script,file=filename_script,status='replace')

      ! AREA string:    AREA="-R$lonmin/$lonmax/$latmin/$latmax"
      area_str = "-R0/"
      write(flt_str,'(f8.3)')tmax
      area_str = trim(area_str) // trim(adjustl(flt_str)) // "/0/"
      write(flt_str,'(f8.3)')zmax
      area_str = trim(area_str) // trim(adjustl(flt_str))

          ! Non-geographic projection, (x,y) only
      proj_str = " -JX5i/4i"

      ! Initial pscoast command to start the ps file
      start_ps = "-K > "     // trim(adjustl(filename_ps))
      contn_ps = "-K -O >> " // trim(adjustl(filename_ps))
      end_ps   = "-O >> "    // trim(adjustl(filename_ps))

      ! Set up to plot via GMT script
      write(fid_script,'(g0)')'#!/bin/bash'
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary GMT script for producing vertical profiles for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"gmt gmtset PS_MEDIA=letter"
      ! write out to CPT.
      write(flt_str,'(f7.1)')cmax
      cmd = 'gmt makecpt -Cjet -T0/' // trim(adjustl(flt_str)) // "/0.25 > my.cpt"
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Resample profile data to regular grid
      incr_str = " -I"
      write(flt_str,'(f8.3)')dtg
      incr_str = trim(incr_str) // trim(adjustl(flt_str)) // "/"
      write(flt_str,'(f8.3)')dzg
      cmd = 'gmt surface'                     // " " // &
              trim(adjustl(filename_outdata)) // " " // &
              trim(adjustl(area_str))         // " " // &
              trim(adjustl(incr_str))         // " " // &
              '-Gout.grd'
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Make sure there are no negative concentrations (might happen from regridding)
      cmd = 'gmt grdmath out.grd 0 MAX = out.grd'
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Write basemap
      title_plot = trim(adjustl(Site_vprofile(vprof_ID))) // coord_str // '"'
      title_str  = '-B+t"' // trim(adjustl(title_plot))
      cmd = 'gmt psbasemap -X3i -Y3i'    // " " // &
              trim(adjustl(area_str))    // " " // &
              trim(adjustl(proj_str))    // " " // &
              trim(adjustl(title_str))   // " " // &
              trim(adjustl(start_ps))
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Contour data
      base_str = '-Bxa2+l"' // trim(adjustl(cstr_xlabel)) // &
                     '" -Bya2+l"' // trim(adjustl(cstr_ylabel)) // '" -BWS'
      cmd = "gmt grdimage out.grd -Cmy.cpt " // " " // &
              trim(adjustl(area_str))   // " " // &
              trim(adjustl(proj_str))   // " " // &
              trim(adjustl(base_str))    // " " // &
              trim(adjustl(contn_ps))
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Plot scalebar
      cmd = 'gmt psscale -Cmy.cpt -DDR+o1c/0c+w10c/0.5c -Baf+l"' // &
             trim(adjustl(cstr_zlabel)) // '" ' // &
            '-J -R -X0.5i -Y0.0i -DJMR' // " " // &
            trim(adjustl(contn_ps))
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Add descriptive footer here
      !gmt pslegend leg1.txt -R-134.500/-97.500/33.500/52.500  -JM-122.117/42.933/7i -Dx-1.0i/-1.5i/3.0i/1.0i/BL -K -O  >> temp.ps
      cmd = "gmt pslegend leg1.txt"   // " " // &
              trim(adjustl(area_str)) // " " // &
              trim(adjustl(proj_str)) // " " // &
              "-Dx-2.0i/-2.0i/3.0i/1.0i/BL " // &
              trim(adjustl(contn_ps))
      write(fid_script,'(g0)') trim(adjustl(cmd))

      !gmt pslegend leg2.txt -R-134.500/-97.500/33.500/52.500  -JM-122.117/42.933/7i -Dx2.0i/-1.5i/4.0i/1.0i/BL -K -O  >> temp.ps
      cmd = "gmt pslegend leg2.txt"   // " " // &
              trim(adjustl(area_str)) // " " // &
              trim(adjustl(proj_str)) // " " // &
              "-Dx1.0i/-2.0i/4.0i/1.0i/BL "  // &
              trim(adjustl(contn_ps))
      write(fid_script,'(g0)') trim(adjustl(cmd))

      !gmt pslegend leg3.txt -R-134.500/-97.500/33.500/52.500  -JM-122.117/42.933/7i -Dx6.0i/-2.3i/2.0i/1.0i/BL -K -O  >> temp.ps
      inquire( file="leg3.txt", exist=IsThere1)
      if(IsThere1)then
        cmd = "gmt pslegend leg3.txt"        // " " // &
                trim(adjustl(area_str))      // " " // &
                trim(adjustl(proj_str))      // " " // &
                "-Dx5.0i/-2.7i/2.0i/1.0i/BL" // " " // &
                trim(adjustl(end_ps))
        write(fid_script,'(g0)')trim(adjustl(cmd))
      endif

      ! This command converts temp.ps to temp.png
      cmd = "gmt psconvert temp.ps -A -Tg"
      write(fid_script,'(g0)')trim(adjustl(cmd))

      cmd = "convert temp.png -resize 850x600 -alpha off temp.png"
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Move this png to the final filename
      cmd = "mv temp.png " // filename_png
      write(fid_script,'(g0)')trim(adjustl(cmd))

      close(fid_script)
      write(plotcom,'(a3,a14)')'sh ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      ! Clean up
      if (CleanScripts_GMT) then
        cmd = "rm -f gmt.conf gmt.history leg*.txt my.cpt out.grd temp.ps vprof_*.gmt vprof_*.dat"
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_2Dprof_PNG_GMT"
      endif;enddo

      return

      end subroutine write_2Dprof_PNG_GMT

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  write_DepPOI_TS_PNG_GMT
!
!  Called from: Ash3d_PostProc.f90
!  Arguments:
!    pt_indx       = index of point in Ash3d netcdf output file
!
!  This subroutine creates a png plot of the transient deposit accumulation at
!  the airport/POI given by pt_index using the GMT graphics package.
!
!  To invoke:
!   ASH3DPLOT=4 ./Ash3d_PostProc 3d_tephra_fall.nc 8 2
!
!   Example script:
!     #!/bin/bash
!     ##########################################################################
!     # Temporary GMT script for producing deposit time-series plots for Ash3d_PostProc
!     # Adjust to suit your needs.
!     ##########################################################################
!     gmt gmtset PS_MEDIA=300x400
!     gmt psbasemap -R/0/25.000/0/1.000 -JX4.0i/2.5i -B+t"Cuernavaca, Mexico"  -K > temp.ps
!     gmt psbasemap -R/0/25.000/0/1.000 -JX4.0i/2.5i  -Bxa$dxg+l"Time (hours after eruption)" -Bya$dyg+l"Deposit Thickness (mm)" -BWS -K -O >> temp.ps
!     gmt psxy -R/0/25.000/0/1.000 -JX4.0i/2.5i  -Ggrey -L+yb depTS_0001.dat -W0.5p -BWS -X0.0i -Y0.0i -O >> temp.ps
!     gmt psconvert temp.ps -Tg
!     convert temp.png -rotate 90 -resize 400x300 -alpha off temp.png
!     mv temp.png depTS_0001.png
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      subroutine write_DepPOI_TS_PNG_GMT(pt_indx)

      use Output_Vars,   only : &
         THICKNESS_THRESH

      use Airports,      only : &
         Airport_Name,Airport_Thickness_TS

      use io_data,       only : &
         nWriteTimes,WriteTimes

      use time_data,     only : &
         Simtime_in_hours

      integer,intent(in) :: pt_indx

      real(kind=dp) :: ymaxpl
      real(kind=ip) :: dxg
      real(kind=ip) :: dyg

      character(len=40) :: title_plot
      character(len=8)  :: flt_str
      character(len=50) :: title_str
      character(len=50) :: proj_str
      character(len=50) :: area_str
      character(len=50) :: start_ps
      character(len=50) :: contn_ps
      character(len=50) :: end_ps

      character(len=16) :: filename_ps
      character(len=10) :: filename_root
      character(len=14) :: filename_script
      character(len=14) :: filename_outdata
      character(len=14) :: filename_png
      character(len=80) :: plotcom
      integer           :: i
      integer           :: iostatus
      integer           :: cstat
      character(len=120):: iomessage
      character(len=200):: cmd

      integer,save      :: plot_index = 0
      integer,parameter :: fid_script  = 55
      integer,parameter :: fid_outdata = 54

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Entered Subroutine write_DepPOI_TS_PNG_GMT"
      endif;enddo

      ! Initialization
      filename_ps  = "temp.ps"

      if(Airport_Thickness_TS(pt_indx,nWriteTimes) < THICKNESS_THRESH)then
        return
      else
        plot_index = plot_index + 1
      endif

      write(filename_root,52)plot_index
 52   format('depTS_',i4.4)
      filename_outdata = trim(adjustl(filename_root)) // ".dat"
      filename_script  = trim(adjustl(filename_root)) // ".gmt"
      filename_png     = trim(adjustl(filename_root)) // ".png"

      open(unit=fid_outdata,file=filename_outdata,status='replace')
      do i = 1,nWriteTimes
        write(fid_outdata,*)WriteTimes(i),Airport_Thickness_TS(pt_indx,i)
      enddo
      close(fid_outdata)

      if(Airport_Thickness_TS(plot_index,nWriteTimes) < THICKNESS_THRESH)then
        ymaxpl = 1.0_dp
        dyg = 0.1_ip
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes) < 1.0_dp)then
        ymaxpl = 1.0_dp
        dyg = 0.1_ip
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes) < 5.0_dp)then
        ymaxpl = 5.0_dp
        dyg = 0.5_ip
      elseif(Airport_Thickness_TS(plot_index,nWriteTimes) < 25.0_dp)then
        ymaxpl = 25.0_dp
        dyg = 2.0_ip
      else
        ymaxpl = 100.0_dp
        dyg = 10.0_ip
      endif

      ! Set up to plot via GMT script
      open(unit=fid_script,file=filename_script,status='replace')
      write(fid_script,'(g0)')'#!/bin/bash'
      write(fid_script,'(g0)')"##########################################################################"
      write(fid_script,'(g0)')"# Temporary GMT script for producing deposit time-series plots for Ash3d_PostProc"
      write(fid_script,'(g0)')"# Adjust to suit your needs."
      write(fid_script,'(g0)')"##########################################################################"


      title_plot = Airport_Name(pt_indx)
      title_str  = '-B+t"' // trim(adjustl(title_plot)) // '"'
      !write(title_str,*)'-B+t"',trim(adjustl(title_plot)),'"'

      ! AREA string:    AREA="-R$lonmin/$lonmax/$latmin/$latmax"
      area_str = " -R/0/"
      write(flt_str,'(f8.3)')real(ceiling(Simtime_in_hours),kind=dp)
      area_str = trim(area_str) // trim(adjustl(flt_str)) // '/0/'
      write(flt_str,'(f8.3)')real(nint(ymaxpl),kind=ip)
      area_str = trim(area_str) // trim(adjustl(flt_str))

          ! Non-geographic projection, (x,y) only
      proj_str = " -JX4.0i/2.5i"

      ! Initial pscoast command to start the ps file
      start_ps = "-K > "     // trim(adjustl(filename_ps))
      contn_ps = "-K -O >> " // trim(adjustl(filename_ps))
      end_ps   = "-O >> "    // trim(adjustl(filename_ps))

      if(ceiling(Simtime_in_hours) < 1.0_ip)then
        dxg = 0.25_ip
      elseif(ceiling(Simtime_in_hours) < 5.0_ip)then
        dxg = 0.5_ip
      elseif(ceiling(Simtime_in_hours) < 15.0_ip)then
        dxg = 1.0_ip
      elseif(ceiling(Simtime_in_hours) < 30.0_ip)then
        dxg = 5.0_ip
      elseif(ceiling(Simtime_in_hours) < 80.0_ip)then
        dxg = 10.0_ip
      else
        dxg = 25.0_ip
      endif

      write(fid_script,'(g0)')"gmt gmtset PS_MEDIA=300x400"
      cmd = "gmt psbasemap " // &
                 trim(adjustl(area_str))  // " " // &
                 trim(adjustl(proj_str))  // " " // &
                 trim(adjustl(title_str)) // " " // " " // &
                 start_ps
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = 'gmt psbasemap ' // &
                 trim(adjustl(area_str)) // " " // &
                 trim(adjustl(proj_str)) // " " // &
                 ' -Bxa$dxg+l"Time (hours after eruption)" -Bya$dyg+l"Deposit Thickness (mm)" -BWS' // " " // &
                 contn_ps
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = 'gmt psxy ' // &
                 trim(adjustl(area_str)) // " " // &
                 trim(adjustl(proj_str)) // " " // &
                 ' -Ggrey -L+yb '               // &
                 filename_outdata               // &
                 ' -W0.5p -BWS -X0.0i -Y0.0i' // " " // &
                 end_ps
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "gmt psconvert temp.ps -Tg"
      write(fid_script,'(g0)')trim(adjustl(cmd))
      cmd = "convert temp.png -rotate 90 -resize 400x300 -alpha off temp.png"
      write(fid_script,'(g0)')trim(adjustl(cmd))

      ! Move this png to the final filename
      cmd = "mv temp.png " // filename_png
      write(fid_script,'(g0)')trim(adjustl(cmd))

      close(fid_script)

      write(plotcom,'(a3,a14)')'sh ',filename_script
      call execute_command_line(plotcom,&
                                wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)

      ! Clean up
      if (CleanScripts_GMT) then
        cmd = "rm -f gmt.conf gmt.history temp.ps depTS_*.gmt depTS_*.dat"
        do io=1,2;if(VB(io) <= verbosity_info)then
          write(outlog(io),*)"Cleaning up temporary files with command:"
          write(outlog(io),*)trim(adjustl(cmd))
        endif;enddo
        call execute_command_line(trim(adjustl(cmd)),&
                                  wait=.true., exitstat=iostatus, cmdstat=cstat, cmdmsg=iomessage)
      endif

      do io=1,2;if(VB(io) <= verbosity_debug1)then
        write(outlog(io),*)"     Exited Subroutine write_DepPOI_TS_PNG_GMT"
      endif;enddo

      return

      end subroutine write_DepPOI_TS_PNG_GMT

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      end module Ash3d_PostProc_GMT

!##############################################################################
