      subroutine help_input(blockID)

      use io_units

      implicit none

      integer,intent(in) :: blockID
      
      ! The idea with the blockID is that help for only a particular block could be
      ! called if there is an error reading something in the input file.  For now, all
      ! blocks are printed.
      !open(11,file='Example_Ash3d_input_file.inp',status='replace')
      
      !DO i=1,2
      !ifile = i*5+1
      1        format(a103)
      do io=1,2;if(VB(io).le.verbosity_error)then
      ! This is not really an error, but we want a high priority for printing this message
      ! if the user request it.
      write(outlog(io),1)'#The following is an input file to the model Ash3d, v.1.0                                              '
      write(outlog(io),1)'#Created by L.G. Mastin, R.P. Denlinger and H.F. Schwaiger, U.S. Geological Survey, 2009.              '
      write(outlog(io),1)'#                                                                                                      '
      write(outlog(io),1)'#GENERAL SOURCE PARAMETERS. DO NOT DELETE ANY LINES                                                    '
      write(outlog(io),1)'#  The first line of this block identifies the volcano by name.                                        '
      write(outlog(io),1)'#  If the volcano name begins with either 0 or 1, then the volcano                                     '
      write(outlog(io),1)'#  is assumed to be in the Smithonian database and default values for                                  '
      write(outlog(io),1)'#  Plume Height, Duration, Mass Flux Rate, Volume, and mass fraction of                                '
      write(outlog(io),1)'#  fines are loaded.  These can be over-written by entering non-negative                               '
      write(outlog(io),1)'#  values in the appropriate locations in this input file.                                             '
      write(outlog(io),1)'#                                                                                                      '
      write(outlog(io),1)'#  The second line of this block identifies the projection used and the form of                        '
      write(outlog(io),1)'#  the input coordinates and is of the following format:                                               '
      write(outlog(io),1)'#    latlonflag, projflag,  followed by a variable list of projection parameters                       '
      write(outlog(io),1)'#  projflag should describe the projection used for both the windfile(s) and                           '
      write(outlog(io),1)'#  the input coordinates.  Currently, these need to be the same projection.                            '
      write(outlog(io),1)'#  For a particular projflag, additional values are read defining the projection.                      '
      write(outlog(io),1)'#    latlonflag = 0 if the input coordinates are already projected                                     '
      write(outlog(io),1)'#               = 1 if the input coordinates are in lat/lon                                            '
      write(outlog(io),1)'#    projflag   = 1 -- polar stereographic projection                                                  '
      write(outlog(io),1)'#           lambda0 -- longitude of projection point                                                   '
      write(outlog(io),1)'#           phi0    -- latitude of projection point                                                    '
      write(outlog(io),1)'#           k0      -- scale factor at projection point                                                '
      write(outlog(io),1)'#           radius  -- earth radius for spherical earth                                                '
      write(outlog(io),1)'#               = 2 -- Alberts Equal Area ( not yet verified !!)                                       '
      write(outlog(io),1)'#           lambda0 --                                                                                 '
      write(outlog(io),1)'#           phi0    --                                                                                 '
      write(outlog(io),1)'#           phi1    --                                                                                 '
      write(outlog(io),1)'#           phi2    --                                                                                 '
      write(outlog(io),1)'#               = 3 -- UTM ( not yet verified !!)                                                      '
      write(outlog(io),1)'#           zone    -- zone number                                                                     '
      write(outlog(io),1)'#           north   -- flag indication norther (1) or southern (0) hemisphere                          '
      write(outlog(io),1)'#               = 4 -- Lambert conformal conic                                                         '
      write(outlog(io),1)'#           lambda0 -- longitude of origin                                                             '
      write(outlog(io),1)'#              phi0 -- latitude of origin                                                              '
      write(outlog(io),1)'#              phi1 -- latitude of secant1                                                             '
      write(outlog(io),1)'#              phi2 -- latitude of secant2                                                             '
      write(outlog(io),1)'#            radius -- earth radius for a spherical earth                                              '
      write(outlog(io),1)'#                                                                                                      '
      write(outlog(io),1)'# The vent coordinates can optionally include a third value for elevation in km.                       '
      write(outlog(io),1)'# If the vent elevation is not given, 0 is used if topography is turned off.                           '
      write(outlog(io),1)'# If it is turned on, the vent elevation is assigned the topographic value of the                      '
      write(outlog(io),1)'# vent cell.                                                                                           '
      write(outlog(io),1)'******************* BLOCK 1 ***************************************************                        '
      write(outlog(io),1)'Eyjafjallajokull               #Volcano name (character*30)                                            '
      write(outlog(io),1)'1 1 0.0 90.0 0.933 6367.470    #Proj flags and params                                                  '
      write(outlog(io),1)'-25.0    45.0                  #x, y of LL corner of grid (km, or deg. if latlongflag=1)               '
      write(outlog(io),1)'55.0     25.0                  #grid width and height (km, or deg. if latlonflag=1)                    '
      write(outlog(io),1)'-19.62   63.63                 #vent location         (km, or deg. if latlonflag=1)                    '
      write(outlog(io),1)'3.0      3.0                   #DX, DY of grid cells  (km, or deg.)                                    '
      write(outlog(io),1)'1.0                            #DZ of grid cells      (always km)                                      '
      write(outlog(io),1)'0.     4.                      #diffusion coefficient (m2/s), Suzuki constant                          '
      write(outlog(io),1)'9                              #neruptions, number of eruptions or pulses                              '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#ERUPTION LINES (number = neruptions)                                                                  '
      write(outlog(io),1)'#In the following line, each line represents one eruptive pulse.                                       '
      write(outlog(io),1)'#Parameters are (1) start time (yyyy mm dd h.hh (UT)); (2) duration (hrs);                             '
      write(outlog(io),1)'#               (3) plume height;                      (4) eruped volume (km3)                         '
      write(outlog(io),1)'#If neruptions=1 and the year is 0, then the model run in forecast mode where mm dd h.hh are           '
      write(outlog(io),1)'#interpreted as the time after the start of the windfile.  In this case, duration, plume               '
      write(outlog(io),1)'#height and erupted volume are replaced with ESP if the values are negative.                           '
      write(outlog(io),1)'******************* BLOCK 2 ***************************************************                        '
      write(outlog(io),1)'2010 4 14 9  3 7.4 8.46E-004                                                                           '
      write(outlog(io),1)'2010 4 14 12 3 8.4 1.38E-003                                                                           '
      write(outlog(io),1)'2010 4 14 15 3 6.8 6.11E-004                                                                           '
      write(outlog(io),1)'2010 4 14 18 3 5.6 2.89E-004                                                                           '
      write(outlog(io),1)'2010 4 14 21 3 5.1 2.01E-004                                                                           '
      write(outlog(io),1)'2010 4 15 0  3 5.3 2.33E-004                                                                           '
      write(outlog(io),1)'2010 4 15 3  3 5.2 2.17E-004                                                                           '
      write(outlog(io),1)'2010 4 15 6  3 5.3 2.33E-004                                                                           '
      write(outlog(io),1)'2010 4 15 9  3 5.7 3.09E-004                                                                           '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#WIND OPTIONS                                                                                          '
      write(outlog(io),1)'#Ash3d will read from either a single 1-D wind sounding, or gridded, time-                             '
      write(outlog(io),1)'#dependent 3-D wind data, depending on the value of the parameter iwind.                               '
      write(outlog(io),1)'#For iwind = 1, read from a 1-D wind sounding                                                          '
      write(outlog(io),1)'#            2, read from 3D gridded ASCII files generated by the Java script                          '
      write(outlog(io),1)'#               ReadNAM216forAsh3d or analogous.                                                       '
      write(outlog(io),1)'#            3, read directly from a single NetCDF file.                                               '
      write(outlog(io),1)'#            4, read directly from multiple single-timestep NetCDF files.                              '
      write(outlog(io),1)'#            5, read directly from multiple multi-timestep NetCDF files.                               '
      write(outlog(io),1)'#The parameter iwindformat specifies the format of the wind files, as follows:                         '
      write(outlog(io),1)'# iwindformat =  1: ASCII files (this is redundant with iwind=2                                        '
      write(outlog(io),1)'#                2: NAM_216pw 45km files (provided by Peter Webley)                                    '
      write(outlog(io),1)'#                3: NARR_221 32km (see http://dss.ucar.edu/pub/narr)                                   '
      write(outlog(io),1)'#                4: NARR_221 32km a-files (ftp://nomads.ncdc.noaa.gov/NARR)                            '
      write(outlog(io),1)'#                5: NAM_216 files from idd.unidata.ucar.edu                                            '
      write(outlog(io),1)'#                6: AWIPS_105 90km from idd.unidata.ucar.edu                                           '
      write(outlog(io),1)'#                7: CONUS_212 40km from idd.unidata.ucar.edu                                           '
      write(outlog(io),1)'#                8: NAM_218 12km                                                                       '
      write(outlog(io),1)'#                9:   unassigned                                                                       '
      write(outlog(io),1)'#               10: NAM_242 11km http://motherlode.ucar.edu/                                           '
      write(outlog(io),1)'#               20: NCEP GFS 0.5 degree files (http://www.nco.ncep.noaa.gov/pmb/products/gfs/)         '
      write(outlog(io),1)'#               21: ECMWF 0.25deg for Hekla intermodel comparison                                      '
      write(outlog(io),1)'#               22: NCEP GFS 2.5 degree files                                                          '
      write(outlog(io),1)'#               23: NCEP DOE Reanalysis 2.5 degree files (http://dss.ucar.edu/pub/reanalysis2)         '
      write(outlog(io),1)'#               24: NASA MERRA-2 0.625/0.5 degree reanalysis                                           '
      write(outlog(io),1)'#               25: NCEP1 2.5 global reanlysis (1948-pres)                                             '
      write(outlog(io),1)'#                     Note: use nWindFiles=1 for iwindformat=25                                        '
      write(outlog(io),1)'#               26: GFS (same as iwf20, but with 5 more pres levels to 100Pa)                          '
      write(outlog(io),1)'#               27: NOAA-CIRES II 2-deg global reanlysis (1870-2010)                                   '
      write(outlog(io),1)'#                     http://rda.ucar.edu/datasets/ds131.1/docs/more.html                              '
      write(outlog(io),1)'#                                                                                                      '
      write(outlog(io),1)'#Many plumes extend  higher than the maximum height of mesoscale models.                               '
      write(outlog(io),1)'#Ash3d handles this as determined by the parameter iHeightHandler, as follows:                         '
      write(outlog(io),1)'#for iHeightHandler = 1, stop the program if the plume height exceeds mesoscale height                 '
      write(outlog(io),1)'#                     2, wind velocity at levels above the highest node                                '
      write(outlog(io),1)'#                        equal that of the highest node.  Temperatures in the                          '
      write(outlog(io),1)'#                        upper nodes do not change between 11 and 20 km; above                         '
      write(outlog(io),1)'#                        20 km they increase by 2 C/km, as in the Standard                             '
      write(outlog(io),1)'#                        atmosphere.  A warning is written to the log file.                            '
      write(outlog(io),1)'#Checking divergence:  Some wind modeled wind fields are not very good at                              '
      write(outlog(io),1)'#                      conserving mass, meaning that the divergence of velocity                        '
      write(outlog(io),1)'#                      in each cell is not close to zero.  The model can check                         '
      write(outlog(io),1)'#                      the divergence of the wind field if desired.                                    '
      write(outlog(io),1)'******************* BLOCK 3 ***************************************************                        '
      write(outlog(io),1)'4  20               #iwind, iwindformat                                                                '
      write(outlog(io),1)'2                   #iHeightHandler                                                                    '
      write(outlog(io),1)'60                  #Simulation time in hours                                                          '
      write(outlog(io),1)'no                  #stop computation when 99% of erupted mass has deposited?                          '
      write(outlog(io),1)'16                  #nWindFiles, number of gridded wind files (used if iwind>1)                        '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#OUTPUT OPTIONS:                                                                                       '
      write(outlog(io),1)'#The list below allows users to specify the output options                                             '
      write(outlog(io),1)'#All but the final deposit file can be written out at specified                                        '
      write(outlog(io),1)'#times using the following parameters:                                                                 '
      write(outlog(io),1)'#nWriteTimes   = if >0,  number of times output are to be written. The following                       '
      write(outlog(io),1)'#                 line contains nWriteTimes numbers specifying the times of output                     '
      write(outlog(io),1)'#                if =-1, it specifies that the following line gives a constant time                    '
      write(outlog(io),1)'#                 interval in hours between write times.                                               '
      write(outlog(io),1)'#WriteTimes    = Hours between output (if nWritetimes=-1), or                                          '
      write(outlog(io),1)'#                Times (hours since start of first eruption) for each output                           '
      write(outlog(io),1)'#                (if nWriteTimes >1)                                                                   '
      write(outlog(io),1)'******************* BLOCK 4 ***************************************************                        '
      write(outlog(io),1)'no      #Write out ESRI ASCII file of final deposit thickness?                                         '
      write(outlog(io),1)'yes     #Write out        KML file of final deposit thickness?                                         '
      write(outlog(io),1)'no      #Write out ESRI ASCII deposit files at specified times?                                        '
      write(outlog(io),1)'no      #Write out        KML deposit files at specified times?                                        '
      write(outlog(io),1)'no      #Write out ESRI ASCII files of ash-cloud concentration?                                        '
      write(outlog(io),1)'no      #Write out        KML files of ash-cloud concentration ?                                       '
      write(outlog(io),1)'no      #Write out ESRI ASCII files of ash-cloud height?                                               '
      write(outlog(io),1)'no      #Write out        KML files of ash-cloud height?                                               '
      write(outlog(io),1)'yes     #Write out        KML files of ash-cloud load (T/km2) at specified times?                      '
      write(outlog(io),1)'yes     #Write ASCII file of deposit arrival times?                                                    '
      write(outlog(io),1)'yes     #Write KML file of deposit arrival times?                                                      '
      write(outlog(io),1)'yes     #write ASCII file of cloud arrival times?                                                      '
      write(outlog(io),1)'yes     #Write KML file of cloud arrival times?                                                        '
      write(outlog(io),1)'yes     #Write out 3-D ash concentration at specified times?                                           '
      write(outlog(io),1)'netcdf  #format of ash concentration files     (ascii, binary, or netcdf)                              '
      write(outlog(io),1)'-1      #nWriteTimes                                                                                   '
      write(outlog(io),1)'1       #WriteTimes (hours since eruption start)                                                       '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#WIND INPUT FILES                                                                                      '
      write(outlog(io),1)'#The following block of data contains names of wind files.                                             '
      write(outlog(io),1)'#If we are reading from a 1-D wind sounding (i.e. iwind=1) then there should                           '
      write(outlog(io),1)'#be only one wind file.                                                                                '
      write(outlog(io),1)'# If we are reading gridded data there should be iWinNum wind files, each having                       '
      write(outlog(io),1)'# the format volcano_name_yyyymmddhh_FHhh.win                                                          '
      write(outlog(io),1)'#For iwindformat=25 (continuous wind data from 1948-pres), just give                                   '
      write(outlog(io),1)'# the directory with the windfiles (e.g. Wind_nc)                                                      '
      write(outlog(io),1)'******************* BLOCK 5 ***************************************************                        '
      write(outlog(io),1)'Wind_nc/gfs_4_20100414_0000_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100414_0600_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100414_1200_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100414_1800_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100415_0000_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100415_0600_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100415_1200_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100415_1800_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100416_0000_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100416_0600_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100416_1200_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100416_1800_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100417_0000_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100417_0600_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100417_1200_000.nc                                                                     '
      write(outlog(io),1)'Wind_nc/gfs_4_20100417_1800_000.nc                                                                     '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#AIRPORT LOCATION FILE                                                                                 '
      write(outlog(io),1)'#The following lines allow the user to specify whether times of ash arrival                            '
      write(outlog(io),1)'#at airports & other locations will be written out, and which file                                     '
      write(outlog(io),1)'#to read for a list of airport locations.                                                              '
      write(outlog(io),1)'#PLEASE NOTE:  Each line in the airport location file should contain the                               '
      write(outlog(io),1)'#              airport latitude, longitude, projected x and y coordinates,                             '
      write(outlog(io),1)'#              and airport name.  if you are using a projected grid,                                   '
      write(outlog(io),1)'#              THE X AND Y MUST BE IN THE SAME PROJECTION as the wind files.                           '
      write(outlog(io),1)'#              Alternatively, if proj4 is compiled, you can have Proj4                                 '
      write(outlog(io),1)'#              find the projected coordinates by typing "yes" to the last parameter                    '
      write(outlog(io),1)'******************* BLOCK 6 ***************************************************                        '
      write(outlog(io),1)'no                            #Write out ash arrival times at airports to ASCII FILE?                  '
      write(outlog(io),1)'no                            #Write out grain-size distribution to ASCII airports file?               '
      write(outlog(io),1)'no                            #Write out ash arrival times to kml file?                                '
      write(outlog(io),1)'GlobalAirports.txt            #Name of file containing aiport locations                                '
      write(outlog(io),1)'no                            #Have Proj4 calculate projected coordinates?                             '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#GRAIN SIZE GROUPS                                                                                     '
      write(outlog(io),1)'******************* BLOCK 7 ***************************************************                        '
      write(outlog(io),1)'# The first line must contain the number of settling velocity groups, but                              '
      write(outlog(io),1)'# can optionally also include a flag for the fall velocity model to be used.                           '
      write(outlog(io),1)'#    FV_ID = 1, Wilson and Huang                                                                       '
      write(outlog(io),1)'#          = 2, Wilson and Huang + Cunningham slip                                                     '
      write(outlog(io),1)'#          = 3, Wilson and Huang + Mod by Pfeiffer Et al.                                              '
      write(outlog(io),1)'#          = 4, Ganser (assuming prolate ellipsoids)                                                   '
      write(outlog(io),1)'#          = 5, Stokes flow for spherical particles + slip                                             '
      write(outlog(io),1)'# If no fall model is specified, FV_ID = 1, by default                                                 '
      write(outlog(io),1)'# The grain size bins can be enters with 2, 3, or 4 parameters.                                        '
      write(outlog(io),1)'# If TWO are given, they are read as:   FallVel (in m/s), mass fraction                                '
      write(outlog(io),1)'# If THREE are given, they are read as: diameter (mm), mass fraction, density (kg/m3)                  '
      write(outlog(io),1)'# If FOUR are given, they are read as:  diameter (mm), mass fraction, density (kg/m3), Shape F         '
      write(outlog(io),1)'# The shape factor is given as in Wilson and Huang: F=(b+c)/(2*a), but converted                       '
      write(outlog(io),1)'# to sphericity (assuming b=c) for the Ganser model.                                                   '
      write(outlog(io),1)'# If a shape factor is not given, a default value of F=0.4 is used.                                    '
      write(outlog(io),1)'#                                                                                                      '
      write(outlog(io),1)'#If the last grain size bin has a negative diameter, then the remaining mass fraction                  '
      write(outlog(io),1)'# will be distributed over the previous bins via a log-normal distribution in phi.                     '
      write(outlog(io),1)'# The last bin would be interpreted as:                                                                '
      write(outlog(io),1)'# diam (neg value) , phi_mean, phi_stddev                                                              '
      write(outlog(io),1)'#                              # nsmax FV_ID                                                           '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'0.0010 1.0000 2500.0     #grain size (mm), mass fraction, density (kg/m3)                              '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#Options for writing vertical profiles                                                                 '
      write(outlog(io),1)'#The first line below gives the number of locations (nlocs) where vertical                             '
      write(outlog(io),1)'# profiles are to be written.  That is followed by nlocs lines, each of which                          '
      write(outlog(io),1)'#contain the location, in the same coordinate system specified above for the                           '
      write(outlog(io),1)'#volcano.                                                                                              '
      write(outlog(io),1)'******************* BLOCK 8 ***************************************************                        '
      write(outlog(io),1)'4                             #number of locations for vertical profiles (nlocs)                       '
      write(outlog(io),1)'12.4  51.4                    #Leipzig                                                                 '
      write(outlog(io),1)'11.3  48.2                    #Munich (Maisach)                                                        '
      write(outlog(io),1)'11.0  47.4                    #Schneefernerhaus (Zugspitze)                                            '
      write(outlog(io),1)'11.0  47.8                    #Hohenpeissenberg                                                        '
      write(outlog(io),1)'*******************************************************************************                        '
      write(outlog(io),1)'#netCDF output options                                                                                 '
      write(outlog(io),1)'# This last block is optional.                                                                         '
      write(outlog(io),1)'# The output file name can be give, but will default to 3d_tephra_fall.nc if absent                    '
      write(outlog(io),1)'# The title and comment lines are passed through to the netcdf header of the                           '
      write(outlog(io),1)'# output file.                                                                                         '
      write(outlog(io),1)'# If use topography is yes, then the topography format must be specified                               '
      write(outlog(io),1)'#  topoFormat = 1, ETOPO1 (1-minute global topo/batho) http://www.ngdc.noaa.gov/mgg/global/global.html '
      write(outlog(io),1)'#             = 2, GEBCO 08 (30-second global topo/batho) http://www.gebco.net/                        '
      write(outlog(io),1)'# The smoothing radius is always given in km and will only be invoked if it is larger                  '
      write(outlog(io),1)'# than the grid spacing of the simulation.                                                             '
      write(outlog(io),1)'******************* BLOCK 9 ***************************************************                        '
      write(outlog(io),1)'3d_tephra_fall.nc             # Name of output file                                                    '
      write(outlog(io),1)'Eyjafjallajokull              # Title of simulation                                                    '
      write(outlog(io),1)'no comment                    # Comment                                                                '
      endif;enddo     
      end subroutine help_input

